### ISSUE TITLE
Création d'un Webservice qui expose les Logs des ican

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#1]
C'est mettre à disposition d'entités tiers genre Clovis Location les informations traduites par nous des logs issus des Ican.
exposer les logs à partir d'une date par défaut les derniers 15 j

**Comment by AlainPierreSDPV** [comment]
Récupérer l'immat avec 3A

**Comment by MamboJoel** [comment]
Recevoir
======
Date de début
Date de fin

Renvoyer 
======
Des VehicleLog avec :
Index km
Alertes tableau de bord (colonne Status en français ?)
Coordonnées géographique

**Comment by MamboJoel** [comment]
@AlainPierreSDPV j'ai un doute soudain : Gerausiv ne nous retourne des véhicules que lorsqu'on l’interroge avec une immat non ?

**Comment by MamboJoel** [comment]
En fait non. J'ai l'impression qu'on peut l'interroger avec un VIN.

**Comment by AlainPierreSDPV** [comment]
Oui dans Fleet Reception nous utilisons les 2 méthode

**Comment by MamboJoel** [comment]
Je poursuis la conversation ici.

Voici le message de Thierry :

> Le web service semble fonctionner. (je n’ai pas remonté d’alertes mais c’est sans doute normal : à vérifier).
> Avec Alain nous avons constaté que les dates remontées par le web service sont décalées par rapport à celles affichées dans fleet. D’où ma question : à quoi correspond la date remontée ?
> Et le sens de ma question : si je remonte les alertes entre midi et midi dix, et qu’ensuite je remonte entre midi onze et midi vingt, y a-t-il un risque de louper des alertes ? Si oui, comment s’assurer que j’e n’aurais ni doublons ni loupés ?

Il y avait une erreur dans le choix des dates. Désormais il s'agit de la date d'arrêt du véhicule, relevée par le boîtier.
Voici le filtre que nous effectuons : 
```
StopDate >= @From
And
StopDate <= @To
```
Ainsi les deux recherches suivantes ne laisseront rien échapper entre 12:00 et 12:20 :
- From : 12:00 , To : 12:10
- From : 12:10, To : 12:20

**Comment by MamboJoel** [comment]
Thierry,

Avec ce système de date, au cas où tu crains d'importer d'importer deux fois un même Log j'ai ajouté à la class Log le chant unique ID. En PJ la nouvelle version de la documentation.
[VehicleLog.txt](https://github.com/groupe-gac/FleetOne/files/526898/VehicleLog.txt)

Par ailleurs je mets aussi en PJ quelques logs qui contiennent des alertes tableau de bord. Je pense que tu peux en avoir besoin pour tester.
[Logs avec statuts.xlsx](https://github.com/groupe-gac/FleetOne/files/526901/Logs.avec.statuts.xlsx)

Nicolas

**Comment by ThierryBrehon** [comment]
Bonjour Nicolas,

OK je prends en compte la modification de signature du WS.
Je suis surpris par le contenu de ta log. En discutant avec Alain, j’avais cru comprendre qu’il y aurait une alerte par ligne, alors que dans cette log, il y a plusieurs alertes sur une seule ligne.



Cordialement
Thierry BRÉHON

[cid:image001.jpg@01D22560.95205D20]

Responsable Informatique



Tél : +33 4 37 91 25 98
Tél : +33 6 80 61 17 28



Email : t.brehon@clovislocation.com<mailto:t.brehon@clovislocation.com>

Adresse : Le Britannia – Bâtiment C – 20 Bd Eugène Deruelle – 69432 LYON CEDEX 03

[cid:image002.jpg@01D22560.95205D20]<http://www.clovislocation.com/>

De : Nicolas Taret [mailto:notifications@github.com]
Envoyé : jeudi 13 octobre 2016 13:08
À : groupe-gac/FleetOne <FleetOne@noreply.github.com>
Cc : Thierry Brehon <thierry.brehon@coservices.fr>; Assign <assign@noreply.github.com>
Objet : Re: [groupe-gac/FleetOne] Création d'un Webservice qui expose les Logs des ican (#1)


Thierry,

Avec ce système de date, au cas où tu crains d'importer d'importer deux fois un même Log j'ai ajouté à la class Log le chant unique ID. En PJ la nouvelle version de la documentation.
VehicleLog.txt<https://github.com/groupe-gac/FleetOne/files/526898/VehicleLog.txt>

Par ailleurs je mets aussi en PJ quelques logs qui contiennent des alertes tableau de bord. Je pense que tu peux en avoir besoin pour tester.
Logs avec statuts.xlsx<https://github.com/groupe-gac/FleetOne/files/526901/Logs.avec.statuts.xlsx>

Nicolas

**Comment by ThierryBrehon** [comment]
pas de problème, le web service tel qu'il est là me convient. Il est au plus proche de ce que le boitier renvoie et c'est le principe de ce développement. Ceux qui veulent autre chose (dont moi) devront développer selon leurs attentes.

**Comment by ThierryBrehon** [comment]
Bonjour Nicolas,

Le web service ne répond plus depuis le 12/01 20h14


Cordialement
Thierry BRÉHON

[cid:image005.jpg@01D26D80.A8A85010]

Responsable Informatique



Tél : +33 4 37 91 25 98
Tél : +33 6 80 61 17 28



Email : t.brehon@clovislocation.com<mailto:t.brehon@clovislocation.com>

Adresse : Le Britannia – Bâtiment C – 20 Bd Eugène Deruelle – 69432 LYON CEDEX 03

[cid:image006.jpg@01D26D80.A8A85010]<http://www.clovislocation.com/>

De : Nicolas Taret [mailto:notifications@github.com]
Envoyé : jeudi 12 janvier 2017 14:47
À : groupe-gac/FleetOne <FleetOne@noreply.github.com>
Cc : Thierry Brehon <thierry.brehon@coservices.fr>; Assign <assign@noreply.github.com>
Objet : Re: [groupe-gac/FleetOne] Création d'un Webservice qui expose les Logs des ican (#1)


Closed #1<https://github.com/groupe-gac/FleetOne/issues/1>.

**Comment by MamboJoel** [comment]
Salut Thierry,

Le service était down car le domaine sdpv.com était arrivé a expiration. Une situation aussi incongrue qu'inédite. Nous avons effectué le transfert de tous les domaines du compte Waybis à NTLM et Namebay, notre fournisseur de DNS, ne nous a pas prévenu de l'échéance comme il le faisait d'ordinaire.

Nicolas
