### ISSUE TITLE
Nom du  fournisseur qui n'apparait pas facture importée GAC invoive non affectée

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#10]
CM-410-CN
Facture : 20/09/2016 D-0-2016-242620
Fournisseur :???????
Client : GIC DOLE
OR : 13/07/2016 0124363
Montant : 3342,38
Créée le : 22/09/2016
il semble que ce soit toujours le cas pour le fournisseur D-O qui est Dôle PL
http://f2.sdpv.com/mj/#url=/Member/Index/&CompanyID=m.1545&HasAlert=true&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=&AlertID=&VisitID=&MemberTab=InvoiceList

**Comment by MamboJoel** [comment]
Je ne reproduis pas parce qu'entretemps la facture a certainement été traité. Mais je pense avoir compris pourquoi le fournisseur n'apparaissait plus. C'est parce que la concession n'était plus "Actif".
Le fournisseur est une concession qui semble être **GIC 25** ConcessionID = 364

C'est un problème assez profond.
Fleet liste des GacInvoice.Invoice
Celles-ci comportent une propriété Fournisseur Reseau (qui est en fait le fournisseur de la facture) qui pointe sur une vue Reseau de FleetR (Fleet Reception) qui pointe sur la table Concession de GestionSDPV1 en filtrant sur le champ Actif = 1.
J'ai passé cette concession de Actif = 0 à Actif = 1

`GacInvoice.InvoiceID = 3221265
SDPVGestion.Concession.ID = 364
GIC 25`
