### ISSUE TITLE
Alerte Ican non récupérée dans le WS mis à diposition de Clovis

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#103]
dans le profil du véhicule ci-dessous
http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=c.14924&HasAlert=false&HasMandatoryAlert=false&MonthsForAlert=3&VehicleID=53127&AlertID=&VisitID=&IsStoped=false&HasIncomingVisit=false&IsHot=false&HasLicence=false&Licence=&Display=&tab=Visits

une alerte jaune" Disfonctionnement pneu" a été récupérée d'un log de l'ican 793 le 10/01/2017

Cette information n'a pas été récupérée dans le WS mis à disposition de Clovis Location

**Comment by MamboJoel** [comment]
Nous avons trouvé la source du problème et l'avons corrigé.

L'appel au webservice suivant (sur la journée du 10) donne bien un log ayant pour statut " Disfonctionnement pneu" :
```C#
var r = srv.GetVehicleLogs(userName, password, new DateTime(2017, 1, 10), new DateTime(2017, 1, 11));
var l = r.Logs.Where(x => x.ID == 74580).FirstOrDefault();
```

![image](https://cloud.githubusercontent.com/assets/3832009/21981235/b5ea599c-dbe6-11e6-9a48-67e2fcfdf2f0.png)

Pouvez-vous confirmer et clore ?
Merci.
