### ISSUE TITLE
FleetOne : Problème véhicule archivé avec une date de fin de gestion en 2020

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#104]
Le véhicule DD-742-DA est archivé alors que la date de fin de gestion est le 31/08/2020.

http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=c.9374&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=39128&AlertID=&VisitID=&ClientTab=Users&FromDate=01/01/2016&ToDate=31/12/2016&VisitReference=813446&Display=&tab=Edit&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=DD-742-DA&MessageID=&VehicleTab=VehicleInfo&EquipmentID=&VehicleTS=1484211741783&MemberTab=Users&ProfileCategoryID=288&ProfileID=8330&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017

![image](https://cloud.githubusercontent.com/assets/22617815/21985438/fa99a89a-dbfa-11e6-9a4a-290eac0eba93.png)

![image](https://cloud.githubusercontent.com/assets/22617815/21985448/074af508-dbfb-11e6-8399-9f2ed7a4f7f6.png)

**Comment by MamboJoel** [comment]
Comment constates-tu qu'il est archivé ?

**Comment by PIEGAY** [comment]
il possède un cadenas lorsque je recherche son immatriculation : 

![image](https://cloud.githubusercontent.com/assets/22617815/21991375/a4c06fae-dc12-11e6-9481-15c2693a597e.png)

Il n’apparaît pas lorsque je regarde l'ensemble des véhicules actifs du client "IAFRATE" : 

![image](https://cloud.githubusercontent.com/assets/22617815/21991427/d6584172-dc12-11e6-8711-08a078b6c0dd.png)

**Comment by PIEGAY** [comment]
Est-ce que tu as trouvé le problème ?

**Comment by Portekoi** [comment]
@MamboJoel De ce que je constate, dans la table `Vehicle`, le champ "isactive" est à 0 pour ce cas.

Par contre, si je regarde la classe `Vehicle`, je vois que la propriété `IsActive()` ne s'appuie pas sur ce champ mais sur un test :

`Return (Not ManagementStartDate.HasValue OrElse ManagementStartDate.Value < Now) And (Not ManagementEndDate.HasValue OrElse ManagementEndDate.Value > Now)`

Sauf que la liste ci-dessus utilise le champ `IsActive` de la base. Mais je ne trouve pas comment modifier cela car c'est un dataReader qui utilisé dans `VehicleProxy` et je n'ai pas accès aux champs du test ci-dessus.

**Comment by Portekoi** [comment]
Je remonte 24 cas de véhicules qui sont "actifs" au niveau des dates mais inactifs au niveau du champ `IsAtive=0` et `IsArchive=0` dans le cas ci-dessus

`Select * from vehicle where (datein is null or datein < getdate()) AND (dateout is not null and dateout > getdate()) and Isactive = 0`

**Comment by Portekoi** [comment]
Solution proposée : modifier la vue `FleetVehicleWithArchive` pour y ajouter DateIn et DateOut de `Vehicle` et effectuer le même test dans une méthode *static* qui prend en entrée ces deux valeurs comme la méthode `IsActive()` (qui pointerait vers cette nouvelle *static*

**Comment by Portekoi** [comment]
Je pense qu le champ isArchive a été mis à jour depuis la v1

**Comment by PIEGAY** [comment]
Bingo !! Le gestionnaire de parc avait archivé le véhicule dans V1 puis changer la date dans V2.... 
J'ai réintégré le véhicule depuis V1 et ... miracle il n'est plus archivé !! 
Ils vont me rendre fou...
