### ISSUE TITLE
BUG FLEETONE : Problème alertes réglementaires (Danger)

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#106]
Sur le parc du franchisé "CLOVISLOCATION78" - Id 2747

http://f2.sdpv.com/mj/#url=/Vehicle/Index/&CompanyID=m.2747&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=&AlertID=&VisitID=&ClientTab=Users&FromDate=01/01/2016&ToDate=31/12/2016&VisitReference=813446&Display=&tab=Visits&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=60130514&MessageID=&VehicleTab=Equipment-41636&EquipmentID=41636&VehicleTS=1484211741783&MemberTab=Supplier&ProfileCategoryID=288&ProfileID=5057&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017

Nous avons un nombre important de véhicules (78) qui ont les alertes "Contrôle annuel du limiteur de vitesse", "Contrôle contrôlographe numérique" et "VGP levage 6mois" en défaut alors que les visites associées ont bien été réalisées. 

Exemple : CW-976-FV : 

 http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.2747&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=35723&AlertID=&VisitID=&ClientTab=Users&FromDate=01/01/2016&ToDate=31/12/2016&VisitReference=813446&Display=&tab=Visits&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=60130514&MessageID=&VehicleTab=Equipment-41636&EquipmentID=41636&VehicleTS=1484211741783&MemberTab=Supplier&ProfileCategoryID=288&ProfileID=5057&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017

Contrôle annuel du limiteur de vitesse : 
- Date du dernier = 01/06/2016 - Prochaine = 01/06/2016 au lieu de 01/06/2017

Contrôle contrôlographe numérique : 
- Date du dernier = 11/02/2015 - Prochaine = 11/02/2015 au lieu de 11/02/2017

![image](https://cloud.githubusercontent.com/assets/22617815/22057619/c7136de6-dd65-11e6-912b-52289b81045f.png)

Listes des immatriculations concernées : 

![image](https://cloud.githubusercontent.com/assets/22617815/22057717/3cee4572-dd66-11e6-92c2-36de78ed18c3.png)

**Comment by MamboJoel** [comment]
Cyril, les dernières interventions n'ont pas de résultat réglementaire défini. Si tu regardes [la visite du 01/06/2016](http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.2747&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=35723&AlertID=&VisitID=781842&ClientTab=Users&FromDate=01/01/2016&ToDate=31/12/2016&VisitReference=813446&Display=&tab=Visits&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=60130514&MessageID=&VehicleTab=Equipment-41636&EquipmentID=41636&VehicleTS=1484211741783&MemberTab=Supplier&ProfileCategoryID=288&ProfileID=5057&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017) elle présente bien le résultat du "Contrôle annuel du limiteur de vitesse" avec la mention "A", mais c'est simplement parce que c'est la première de la liste.

Comment est-on arrivé à ce stade ? Est-ce des véhicules sur lesquels vous nous avez commandé des traitements en batch ?

Je peux effectuer des transformations et valider tous les contrôles puis recalculer les plannings, seulement ce serait plus commode si tu me donnais une liste d'immatriculation en texte plutôt qu'en image.

Merci !

**Comment by MamboJoel** [comment]
Si je cherche les véhicule du membre 2747 j'en trouve 812. Quel autre filtre dois-je appliquer ?

**Comment by PIEGAY** [comment]
Je suis en assemblée générale et je n ai pas accès à FleetOne.
J'avais sélectionné l'ensemble des véhicules avec une alerte réglementaire sous clovislocation78.
Je serai pour valider l'ensemble des véhicules du franchise en "A".
C'est validé avec le franchisé.

Le 18 janv. 2017 à 14:43, "Nicolas Taret" <notifications@github.com<mailto:notifications@github.com>> a écrit :


Si je cherche les véhicule du membre 2747 j'en trouve 812. Quel autre filtre dois-je appliquer ?

-

**Comment by MamboJoel** [comment]
Ok je fais ça.

**Comment by MamboJoel** [comment]
J'ai appliqué le résultat positif à toutes les interventions. Relancé la routine de calcul sur 812 véhicules.
Tu peux clore si c'est ok.

**Comment by PIEGAY** [comment]
Parfait
