### ISSUE TITLE
Modification de rattachement client  Groupe BRUNAUD

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#108]
Les clients en piéce jointe sont gérés par le Membre Translocacentre  MemberID 362
ils n'ont ni parentID ni enfants.
il faut les faire gérer par le membre Régitrucks MemberID 370 

[VEH SOCIETES.xlsx](https://github.com/groupe-gac/FleetOne/files/718864/VEH.SOCIETES.xlsx)

**Comment by MamboJoel** [comment]
OK !

**Comment by AlainPierreSDPV** [comment]
Il y a encore 3 clients à muter 
[VEH.SOCIETES-2.xlsx](https://github.com/groupe-gac/FleetOne/files/726942/VEH.SOCIETES-2.xlsx)

**Comment by MamboJoel** [comment]
Ok !
