### ISSUE TITLE
Ergonomie : élargir la boîte "Nature" d'une intervention

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#110]
Pour voir le problème, aller sur [cette visite par exemple](http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.2747&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=35723&AlertID=&VisitID=&ClientTab=Users&FromDate=01/01/2016&ToDate=31/12/2016&VisitReference=813446&Display=&tab=Visits&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=60130514&MessageID=&VehicleTab=Equipment-41636&EquipmentID=41636&VehicleTS=1484211741783&MemberTab=Supplier&ProfileCategoryID=288&ProfileID=5057&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017), puis cocher l'intervention "Echange cartouche filtre AdBlu". Constater alors l'aspect disgracieux de la boîte "Nature".

**Comment by MamboJoel** [comment]
@Portekoi je risque de perdre beaucoup de temps et d'espérance de vie à résoudre ce problème CSS quand je pense que tu es en mesure de le faire sans trop de drame. Est-ce que tu peux te pencher dessus ? 
J'ai commité une première tentative qui élargit la cellule, qu'il faut que tu récupères. Mais le résultat est insuffisant.
Merci !

**Comment by Portekoi** [comment]
@MamboJoel Fait et commité

**Comment by MamboJoel** [comment]
J'ai peut-être fait une erreur dans la publication. J'obtiens toujours cette surcharge :

![image](https://cloud.githubusercontent.com/assets/3832009/22330887/c0980a94-e3c8-11e6-9eb6-8b95436b212f.png)

**Comment by MamboJoel** [comment]
Tu peux intervenir dans le CSS aussi, si besoin, pour agrandir la cellule.

**Comment by Portekoi** [comment]
Je pensais que c'était le menu qui ne convenait pas : 
Avant :
![image](https://cloud.githubusercontent.com/assets/1560754/22331417/9df27634-e3cb-11e6-9ea8-f327d933f385.png)

Après :
![image](https://cloud.githubusercontent.com/assets/1560754/22331385/789e105a-e3cb-11e6-8913-14f434e9b86f.png)

**Comment by MamboJoel** [comment]
Mais t'as refait un commit ? J'obtiens pas ce résultat avec le commit "Correction Nature".

**Comment by Portekoi** [comment]
Tu as vidé ton cache et livré le fichier fleet-widgets.js ?

**Comment by MamboJoel** [comment]
Bravo, t'es un cador.

![image](https://cloud.githubusercontent.com/assets/3832009/22337521/70abaab4-e3e5-11e6-83da-4306bca9d2ec.png)

En revanche je l'avais vidé ce cache, et publié.

**Comment by AlainPierreSDPV** [comment]
Le problème subsiste avec FF (cache vide, etc)

![Uploading image.png…]()

http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.261&HasAlert=true&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=40589&AlertID=&VisitID=&Display=&tab=Visits

**Comment by Portekoi** [comment]
Je n'ai pas le problème sur FF. Ma résolution est suffisamment large pour afficher tout le tableau. Est-ce aussi votre cas? Si je réduis la fenêtre en largeur, j'ai effectivement la superposition qui se met mais à partir passer par un menu moins joli, je ne vois pas de solution à cela.

**Comment by AlainPierreSDPV** [comment]
La résolution de mon écran de PC  15'' est de 1920 x 1080  c'est le maximum permis.
Je ne souhaite pas que l'on modifie le menu, j'ai vérifié que sur des écrans de 20'' le problème ne se pose pas  et le standard des gestionnaires de parc  est  supérieur à cela.
Merci pour cette modification
