### ISSUE TITLE
VehicleService Km Index pour Geudet

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#111]
@Portekoi est-ce que tu peux me dire si tu arrive à connecter ce webservice :

http://mvc.fleet2.gestionparc.com/webservices/VehicleService.asmx

On me dit qu'il retourne une 403.1

**Comment by Portekoi** [comment]
@MamboJoel Il me demande username, password et domain. Tu peux me les donner?

**Comment by MamboJoel** [comment]
C'est ok alors. Merci.

**Comment by AlainPierreSDPV** [comment]
Si ils ont besoin d’accéder à Fleet je viens de créer un utilisateur que soficoservices peut utiliser
login : cyrille.Verniseau@soficoservices.fr
PW : carsysteme
memberID = 1363
