### ISSUE TITLE
suppression du filtre année ds le reporting client "Recherche par VI"

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#112]
pour tester 
login: simon.aylagas@paredes.fr
PW: ***
page http://rep.gestionparc.com/Full/Historique.aspx
prendre le véhicule 636BGY69  (premier de la liste) l'historique s'affiche en haut de page avec le détail des intervention constater qu'il n'y a que les visites des  années 2016 2015 2014
constater dans Fleet  que ce véhicule à des visites enregistrées depuis 2009
pemiére visiteID = 192444

demande 
Ne pas mettre de filtre pour avoir l'historique complet des interventions

**Comment by Portekoi** [comment]
@MamboJoel : Je ne retrouve pas cette IHM dans les branches : "gestion parc".  Tu peux m'en dire plus que je regarde?

**Comment by MamboJoel** [comment]
Oui, tu peux regarder. C'est une autre solution qu tu trouveras dans [ce repository](https://github.com/ntlm-technologies/sdpv-fleet-reporting). Tu ne pourras pas compiler (moi non plus du reste), car il faut devexpress, mais la plupart des requêtes ne nécessitent pas de compilation car elles sont présente soit dans les pages aspx soit dans les vues / fonctions / procédures stockées.

**Comment by Portekoi** [comment]
Dans la base FleetDW : la table "Orders" ne contient pas de données antérieures à 2014
Par contre, la base Fleet, table "Order" qui a une structure s'en rapprochant, nous avons bien des enregistrements à 2009.

Depuis la BD FleetDW : 
```
select * from Fleet.Dbo.[Order] where EquipmentID = 26128

select * from Orders where Orders.EquipmentID = 26128

```

Solutions : Soit réinjecter les données manquantes dans Orders et OrderDetail, soit modifier la requête par celle-ci :
```

SELECT Equipment.Type as Equipement, Orders.ApprouvalNumber as  [N° Accord], Orders.RvDateIn as Date, company.Name as Prestataire, 
Orders.KmIndex, Organ.Name, OpeType.Name,  ope.Name, 
            OrderDetail.Total as HT FROM Equipment INNER JOIN Fleet.Dbo.[Order] as Orders 
ON Equipment.ID = Orders.EquipmentID INNER JOIN Fleet.Dbo.OrderDetail ON Orders.ID = OrderDetail.OrderID 
inner join Fleet.Dbo.Operation as ope on OrderDetail.OperationID = ope.ID
inner join Fleet.Dbo.Organ on ope.OrganID = Organ.ID
left outer join fleet.dbo.OperationType as OpeType on OrderDetail.NatureID =  OpeType.ID
inner join fleet.dbo.company on Orders.SupplierID = company.ID
           WHERE(Equipment.VehicleID = @VehicleID) order by  Orders.RvDateIn desc


```

*A noter que le champo "NatureID" semble avoir été ajouté après 2012*.

**Comment by Portekoi** [comment]
@AlainPierreSDPV Peux tu tester? Merci

**Comment by AlainPierreSDPV** [comment]
C'est Ok merci je cloture cette issue

**Comment by Portekoi** [comment]
Ma correction était temporaire, le temps de trouver pourquoi il n'y avait que 4 ans en ligne.

@MamboJoel J'ai trouvé la procédure (`[dbo].[UpdateOrders]`) qui importe les données de `Fleet.dbo.Order` dans `FleetDw.dbo.Orders`. Le souci étant que si j'enlève le filtre des 4 ans (`and YEAR(o.RvDateIn)> Year(getdate()) - 4`), cela va ajouter le double de lignes, soit 400 000. 
Voir au niveau des ressources si tout te parait bon.

**Comment by MamboJoel** [comment]
@meillere 
Damien a effectué un correctif suite à cette demande d'Alain. 
Seulement il croise le Datawarehouse avec la base en production. Il faudrait, comme il l'établit dans le message précédent, modifier plutôt la routine d'importation.

**Comment by MamboJoel** [comment]
@meillere
