### ISSUE TITLE
Anomalie reporting client PHM

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#113]
Pour reproduire
login:  isabelle.martinat@phm-group.com
PW : choupette
onglet reporting choisir "financier"
http://rep.gestionparc.com/Full/ReportFindem.aspx
Filtres sur "Niv2" = MRCI18  sur fournisseur "SA BRUNAUD ET FILS"    Exercice = 2016  Mois = Janvier
à titre d'exemple (tous les mois ont la même anomalie)  le montant est de 3282.36 € 
cliquer sur le montant 
dans le tableau la visite 749802  constater qu'il y a un montant de 1306.05 € et que dans Fleet  cette visite à pour entité facturée "Garantie" 
Ce reporting concerne que les dépenses que le client paye donc il faut filtrer les opérations pour ne laisser visible que les opérations dont l'imputation est "Client"

Ce comportement est nouveau le reporting était conforme les mois précédents

**Comment by Portekoi** [comment]
Je ne trouve pas le filtre sur le fournisseur : 
![image](https://cloud.githubusercontent.com/assets/1560754/22804363/098de2ea-ef19-11e6-952f-3fb9fdbe43b5.png)
Qu'ai-je manqué?

**Comment by Portekoi** [comment]
Serait-ce lié à cette issue : https://github.com/groupe-gac/FleetOne/issues/85 ?

**Comment by AlainPierreSDPV** [comment]
Non c'était lié au fait que le client PHM n'avait pas le niveau 4 de reporting de déclaré dans la fiche client
http://membre.force-reseau-gp.com/mj/#url=/Client/Index/&CompanyID=c.8820&HasAlert=false&HasMandatoryAlert=false&MonthsForAlert=3&VehicleID=53597&AlertID=&VisitID=&IsStoped=false&HasIncomingVisit=false&IsHot=false&HasLicence=false&Licence=&ClientTab=Info&tab=Logs&VehicleTab=VehicleInfo&EquipmentID=&VehicleTS=1486561031141
