### ISSUE TITLE
Basculement équipement EG081 sur véhicule DA-810-EB

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#114]
Nicolas, 

Merci de basculer l'équipement EG081 (Id 54978) du véhicule BC-425-NS (Id 45073) vers le véhicule DA-810-EB (Id 45059). 

Bonne journée

**Comment by AlainPierreSDPV** [comment]
je ne sais pas si il faut basculer ou recréer à cause du reporting UGAP
le fait de changer cet équipement de CEI et de district les facturations SDPV ne seront plus en phase avec le reporting
est ce important ?

**Comment by PIEGAY** [comment]
le client est informé.
il faut bien faire le basculement.

Merci

**Comment by MamboJoel** [comment]
@Portekoi c'est l'occasion de te familiariser avec ces manipulations. Il s'agit de changer la valeur du champ Equipment.VehicleID. **Puis il faut recalculer le planning.** Vehicle.ComputeAlerts(). Il existe un test unitaire qui effectue cet appel. Ou tu peux en écrire un toi-même.

Il est possible qu'il y ait un problème d'équipement principal. Bien que cela soit redondant, pour diverses raisons historiques et techniques, le principe de l'équipement principal est implémenté de deux manières : 

- Vehicle.MainEquipmentID : designe l'ID de l'équipement principal au niveau de la table Vehicle.
- Equipment.IsMain : booléen spécifiant si cet équipement est principal.

Et il faut respecter l'intégrité logique entre ces deux champs. Il ne peut y avoir qu'un seul équipement principal par véhicule. @PIEGAY j'ai l'impression que dans ce cas de basculement il s'agit de toute façon d'équipement secondaire.

@Portekoi à ta disposition par téléphone pour plus d'information. Par ailleurs, je t'invite à écrire ces procédure dans notre wiki interne. A terme on les compulsera pour envisager des formules d'automatisation de ces manipulation.

**Comment by AlainPierreSDPV** [comment]
Cette issue et en relation avec #37

**Comment by AlainPierreSDPV** [comment]
précision:
dans #37 c'est reproduire la fonctionnalité de V1 qui est de permettre à gestionnaire de pouvoir transférer un équipement secondaire d'un véhicule à l'autre chez un même membre. Ici c'est le transfert d'un équipement secondaire "UGAP" d'un membre à un autre membre

**Comment by Portekoi** [comment]
@MamboJoel Je peux pas passer par le service via DirtyProfile() ? 
Je modifie le VehicleID de rattachement et j'insère dans la table DirtyProfile. Pour déclencher, je "modifie" sans rien toucher un "Profile".

**Comment by MamboJoel** [comment]
Ca fonctionnerait, mais ce serait pas très net, car cette table liste des profils à traiter et non des véhicules.

**Comment by Portekoi** [comment]
Oui effectivement. Je vais voir.

**Comment by Portekoi** [comment]
Je pense avoir fait le nécessaire. @AlainPierreSDPV Peux tu vérifier? Merci.

**Comment by PIEGAY** [comment]
C'est bon ! 
Merci

**Comment by AlainPierreSDPV** [comment]
Non il y a un Pb le profil de l'equipement EG081 n'apparait pas dans les visites, l'hitorique non plus

**Comment by PIEGAY** [comment]
J'ai bien l'historique dans FleetOne : 

![image](https://cloud.githubusercontent.com/assets/22617815/22596931/d8b0a152-ea2d-11e6-8024-24b69789f269.png)

**Comment by AlainPierreSDPV** [comment]
Ok pour l’historique mais je n’ai pas accès à l’équipement pour une nouvelle visite

[cid:image001.png@01D27E3B.76647130]

De : PIEGAY [mailto:notifications@github.com]
Envoyé : vendredi 3 février 2017 16:29
À : groupe-gac/FleetOne <FleetOne@noreply.github.com>
Cc : Alain Pierre <alain.pierre@sdpv.com>; State change <state_change@noreply.github.com>
Objet : Re: [groupe-gac/FleetOne] Basculement équipement EG081 sur véhicule DA-810-EB (#114)


J'ai bien l'historique dans FleetOne :

[image]<https://cloud.githubusercontent.com/assets/22617815/22596931/d8b0a152-ea2d-11e6-8024-24b69789f269.png>

**Comment by Portekoi** [comment]
Je ne connais pas encore très le système. Comment je peux constater ce problème?

Je suis allé ici :
http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.2747&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=45059&AlertID=&VisitID=&ClientTab=Users&FromDate=01/01/2016&ToDate=31/12/2016&VisitReference=813446&Display=&tab=Visits&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=DA-810-EB&MessageID=&VehicleTab=VehicleInfo&EquipmentID=&VehicleTS=1484211741783&MemberTab=Supplier&ProfileCategoryID=288&ProfileID=5057&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017

Mais j'ai bien "Nouvelle visite" dans le menu.

**Comment by Portekoi** [comment]
Et ceci en bas de l'équipement concerné : 
![image](https://cloud.githubusercontent.com/assets/1560754/22597839/8db98caa-ea31-11e6-9d55-4e794eeeab5e.png)

**Comment by AlainPierreSDPV** [comment]
c'est dans la visite que je constate cela

http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.261&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=45059&AlertID=&VisitID=&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=EG081&Display=&tab=Visits

**Comment by MamboJoel** [comment]
Je reproduis l'anomalie comme @AlainPierreSDPV .
@Portekoi typiquement la page du planning affiche la liste des alertes du véhicule. Si l'équipement n'a pas d'alerte, il n'y aura donc pas de linge qui correspond à l'équipement.
J'en conclue donc que les alertes n'ont pas été recalculées.

**Comment by AlainPierreSDPV** [comment]
je constate que je n'ai plus l'anomalie aprés avoir cliqué sur le lien de damien
http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.2747&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=45059&AlertID=&VisitID=&ClientTab=Users&FromDate=01/01/2016&ToDate=31/12/2016&VisitReference=813446&Display=&tab=Visits&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=DA-810-EB&MessageID=&VehicleTab=VehicleInfo&EquipmentID=&VehicleTS=1484211741783&MemberTab=Supplier&ProfileCategoryID=288&ProfileID=5057&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017

**Comment by Portekoi** [comment]
Ok, tant mieux.
