### ISSUE TITLE
Problème logo sur les bons de commande FleetOne

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#115]
Sur les bons de commande nous avons 2 logos : 
- Force Réseau 
- FleetOne 

http://f2.sdpv.com/Visit/Document2/824677

Est-ce que tu peux supprimer le logo "FleetOne" ? 

![image](https://cloud.githubusercontent.com/assets/22617815/22641033/6a5c8b56-ec55-11e6-8cd6-53a09fc72763.png)

Merci

**Comment by Portekoi** [comment]
Je viens de corriger. Merci de valider.

**Comment by Portekoi** [comment]
@PIEGAY Cela a été réglé non?

**Comment by PIEGAY** [comment]
Sous SDPV GRANDS COMPTES nous avons toujours 2 logos en haut du bon de commande dont 1 noir qu'il faudrait supprimer.

Envoyé de mon iPhone

Le 16 mars 2017 à 08:38, "Portekoi" <notifications@github.com<mailto:notifications@github.com>> a écrit :


@PIEGAY<https://github.com/PIEGAY> Cela a été réglé non?

**Comment by Portekoi** [comment]
Est-il possible d'avoir un lien vers la page en question? Merci

**Comment by AlainPierreSDPV** [comment]
celui qui est au début de cette issue suffit il ?
http://f2.sdpv.com/Visit/Document2/824677

**Comment by Portekoi** [comment]
Autant pour moi. Je regarde.

**Comment by Portekoi** [comment]
C'est corrigé. Merci de valider et de clôturer si c'est bon pour vous.

**Comment by AlainPierreSDPV** [comment]
C'est Ok
