### ISSUE TITLE
Problème calcul alerte réglementaire - Véhicule 90330035

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#116]
Sur le véhicule 90330035 : 
http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=c.9171&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=41750&AlertID=&VisitID=811609&ClientTab=Users&FromDate=01/12/2016&ToDate=31/12/2016&VisitReference=824166&Display=&tab=Edit&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=90330035&MessageID=&VehicleTab=Equipment-49756&EquipmentID=49756&VehicleTS=1486394345485&MemberTab=Supplier&ProfileCategoryID=412&ProfileID=9024&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017

- Dernier CT : 26/09/2016 - Prochain : 20/10/2015 au lieu de 26/09/2017

![image](https://cloud.githubusercontent.com/assets/22617815/22652866/49cbbf78-ec88-11e6-8023-cc989ba3127b.png)

**Comment by Portekoi** [comment]
Je n'accède plus au portail : 
Veuillez associer vos comptes Force Réseau - Gestion de parc et coservice.
Mais impossible de le faire

**Comment by PIEGAY** [comment]
Vous êtes avec quel "Login" ?

**Comment by Portekoi** [comment]
alain.pierre@sdpv.com

**Comment by PIEGAY** [comment]
maintenant l'adresse est : alain.pierre@force-reseau.com

**Comment by PIEGAY** [comment]
nous avons changé de nom aujourd'hui

**Comment by Portekoi** [comment]
OK. Quid du mot de passe?

**Comment by PIEGAY** [comment]
c'est le même. 
La partie de gauche de l'identification reste identique
Seule la partie de droite change

**Comment by Portekoi** [comment]
J'arrive pas à me connecter sur la partie de gauche avec 
alain.pierre@force-reseau.com
le mot de passe qui commence par 2 chiffres...

**Comment by PIEGAY** [comment]
sur la partie de gauche, l'adresse mail reste en SDPV...
La partie de gauche reste inchangé. 
ils n'ont pas fait simple !

**Comment by Portekoi** [comment]
Et si j'utilise les anciens à gauche, cela fonctionne mais je n'ai plus le lien vers Coservice

**Comment by Portekoi** [comment]
Et rien à faire : à droite,  avec alain.pierre@force-reseau.com, ca passe pas non plus.

**Comment by Portekoi** [comment]
Ah si, c'est passé :)

**Comment by PIEGAY** [comment]
Super !

**Comment by AlainPierreSDPV** [comment]
C’est le même qu’avant

De : Portekoi [mailto:notifications@github.com]
Envoyé : lundi 6 février 2017 16:34
À : groupe-gac/FleetOne <FleetOne@noreply.github.com>
Cc : Alain Pierre <alain.pierre@force-reseau.com>; Assign <assign@noreply.github.com>
Objet : Re: [groupe-gac/FleetOne] Problème calcul alerte réglementaire - Véhicule 90330035 (#116)


OK. Quid du mot de passe?

**Comment by Portekoi** [comment]
J'ai corrigé la date manuellement.

**Comment by PIEGAY** [comment]
Est-ce que l'origine du BUG a été détecté ?

**Comment by Portekoi** [comment]
Non, je n'ai pas encore trouvé.

**Comment by Portekoi** [comment]
Je pense avoir trouvé mais je préfère que @MamboJoel valide car je ne connais pas encore assez bien l'applicatif.

Dans le fichier ProfileProgrammation à la ligne 112 se trouve cette instruction :
`startDate = LastIntervention.PrescribingIntervention.MandatoryDate`

Pour le cas ci-dessus, cela a pour valeur 20/10/2014 soit + 1 an => 20/10/2015 avec un rappel au 19/09/2015

A mon sens, il faut prendre la date de la dernière intervention, et non la date de la première vsite (si je me trompe pas sur ce qu'est PrescribingIntervention) soit  :
`startDate = LastIntervention.MandatoryDate`

Avec cette modification, la date est correcte soit : 26/09/2017 avec un rappel au 26/08/2017

Je n'ai rien archivé car la modification n'est peut être pas valide. @MamboJoel : A toi de me dire :)

**Comment by Portekoi** [comment]
@MamboJoel Je viens de comprendre : ce pavé concerne la contre visite pour un CT ce qui est notre cas.

Du coup, le script reprend la date de la visite initiale pour calculer la prochaine alerte. 
Sauf que pour notre cas, il n'y a pas eu de contre visite d'où le décalage.

Quel est le délai max pour une contre visite? L'absence de contre visite doit elle générer une alerte? Ces règles métiers m'échappent.

**Comment by Portekoi** [comment]
J'ai l'impression que tous les CT depuis 2014 exclu, sont considérés comme des contre-visites.

**Comment by Portekoi** [comment]
Le dernier CT datant du 26/09/2016 contient une valeur dans  le champ `[Orderdetail].PrescribingOrderDetailID` qui est 932896, qui lui même renvoi vers le CT de 2014.

**Comment by MamboJoel** [comment]
**L'anomalie**

Le problème vient, non du calcul des alertes, mais de données suspectes dans la base. J'ignore comment elles sont parvenues à s'introduire. Certainement via l'usage combiné de V1 et de V2, via le formulaire d'administration dont l'usage abusif permettait d'initialiser sans cesse les véhicules plutôt que de passer par la gestion. @PIEGAY tu peux peut-être investiguer de ce coté-là s'il est nécessaire vraiment d'aller au bout d'une enquête pour un cas qui me semble singulier et rare.

Ce tableau présente le dernier contrôle technique, qui est une contre-visite, ainsi que le contrôle originel, qui a donc fait l'objet d'une contre-visite :

![image](https://cloud.githubusercontent.com/assets/3832009/22691307/1d3981ae-ed3a-11e6-89f0-a622a9da5e9c.png)

Ce qui est suspect, et que l'application ne permet pas, est mis en gras et surligné en jaune :

- Le contrôle technique originel a pour résultat "A" et n'aurait donc pas dû faire l'objet d'une CV.
- Il n'est pas une visite d'initialisation, quand la CV qu'il a suscité l'est.

Clairement ça ressemble à un cas d'abus de l'ancien formulaire V1 d'initialisation.

**Le patch**

Je résous le problème par programmation, en enrichissant le calcul, pour l'avenir, plutôt que de changer ponctuellement les données. 

- Pour calculer l'échéance suivante le programme se fonde, comme l'entend la législation, sur la date du CT originel et non sur celle de la CV. Or ici, le CT originel est suspect. Désormais le programme requalifie en CT une CV dont le prétendu CT originel est antérieur de plus du sursis prévu par la loi (1 mois). Ainsi, dans ce cas, le programme considère que la CV du 26/09/2016 est un CT et non une CV, car son prétendu CT originel a plus d'un mois. @PIEGAY , peut-être que ce délai devrait être augmenté. Car une CV en retard d'un jour sur le sursis serait donc considéré comme un CT et projetterait l'échéance à une date injustement avantageuse.
Cette implémentation est encapsulée dans `Intervention.IsCounterVisit`.

- Par ailleurs, lors de la sauvegarde d'une visite, le programme appelle `Visit.ManageMandatoryPrescription()` qui analyse la visite pour déterminer si c'est une CV et, dans ce cas, lui assigner un CT originel. J'y ai implémenté l'annulation du lien entre CV et CT dans ce cas.

**NB**

@Portekoi c'est vraiment un cas rare de données suspectes. D'ordinaire les problèmes de calcul d'alerte relèvent de règles que l'on affine avec le temps, [comme cette demande](https://github.com/groupe-gac/FleetOne/issues/61) sur laquelle je t'invite d'ailleurs à te pencher.
