### ISSUE TITLE
Transfert Clients UGAP

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#117]
Message original de Yves :

> Bonjour Jacques,
>  
> Ci-joint dans la dernière colonne le changement d'affectation des marchés (situés dans l'avant-dernière colonne).
> Merci de ton intervention.
> Cordialement,

[Arbo rep 08.02.2017.xlsx](https://github.com/groupe-gac/FleetOne/files/764523/Arbo.rep.08.02.2017.xlsx)

**Comment by Portekoi** [comment]
J'ai déplacé le premier uniquement : EST-ENSEMBLE depuis COMMUNAUTES D'AGGLOS vers ETS PUBLICS LOCAUX
Pouvez-vous me confirmer que c'est bon?

**Comment by YvesMadec** [comment]
C’est bon pour Est Ensemble
Cordialement,
Y.M.

De : Portekoi [mailto:notifications@github.com]
Envoyé : jeudi 9 février 2017 19:30
À : groupe-gac/FleetOne
Cc : Yves Madec; Assign
Objet : Re: [groupe-gac/FleetOne] Transfert Clients UGAP (#117)


J'ai déplacé le premier uniquement : EST-ENSEMBLE depuis COMMUNAUTES D'AGGLOS vers ETS PUBLICS LOCAUX
Pouvez-vous me confirmer que c'est bon?

**Comment by Portekoi** [comment]
`COMMUNAUTE URBAINE D'ALENCON` / `LIMOGES METROPOLE` / `SAINT ETIENNE METROPOLE` ont été déplacés.

Pour `NCA `et `METROPOLE EUROPEENNE DE LILLE`, je dois créer un nouveau niveau 2 : `METROPOLE` mais je ne sais pas comment faire. Si quelqu'un peut me renseigner. Merci

**Comment by Portekoi** [comment]
@MamboJoel @YvesMadec J'ai fini par trouvé comment ajouter un "sous-client"

`NCA` et `METROPOLE EUROPEENNE DE LILLE` ont été affectés à `METROPOLE`

**Comment by YvesMadec** [comment]
Bonjour,
NCA et Métropole européenne de Lille ont toujours « Ville » comme parent et non « Métropole »
Cordialement,

Yves MADEC

[cid:image001.png@01D283A9.0470D1E0]



Directeur Grands Comptes

Tél: 06 30 56 53 90

Fax : 04 72 13 90 27

Email : yves.madec@force-reseau.com NOUVEAU !


Adresse : 20 Bd Eugène Deruelle - Le Britannia – Bât C –  69432 LYON Cedex 03

[cid:image002.png@01D283A9.0470D1E0]

www.force-reseau.com<http://www.force-reseau.com/> – Découvrez vite notre nouveau site !




De : Portekoi [mailto:notifications@github.com]
Envoyé : vendredi 10 février 2017 13:58
À : groupe-gac/FleetOne
Cc : Yves Madec; Mention
Objet : Re: [groupe-gac/FleetOne] Transfert Clients UGAP (#117)


@MamboJoel<https://github.com/MamboJoel> @YvesMadec<https://github.com/YvesMadec> J'ai fini par trouvé comment ajouter un "sous-client"

NCA et METROPOLE EUROPEENNE DE LILLE ont été affectés à METROPOLE

**Comment by Portekoi** [comment]
Pourtant, j'ai bien ceci pour NCA et Métropole Européenne de Lille :

![image](https://cloud.githubusercontent.com/assets/1560754/22828538/191374a2-ef9e-11e6-81b1-26d74671c171.png)

**Comment by YvesMadec** [comment]
Et moi, j’ai ça dans le reporting (PJ)…Mais c’est peut-être normal jusqu’à demain…

De : Portekoi [mailto:notifications@github.com]
Envoyé : vendredi 10 février 2017 14:35
À : groupe-gac/FleetOne
Cc : Yves Madec; Mention
Objet : Re: [groupe-gac/FleetOne] Transfert Clients UGAP (#117)


Pourtant, j'ai bien ceci pour NCA et Métropole Européenne de Lille :

[image]<https://cloud.githubusercontent.com/assets/1560754/22828538/191374a2-ef9e-11e6-81b1-26d74671c171.png>

**Comment by Portekoi** [comment]
Je ne vois pas la PJ mais je pense qu'il faut effectivement attendre demain pour que le reporting soit rechargé.

**Comment by YvesMadec** [comment]
Merci …
Tant que j’y suis, merci également de ne pas toucher au reporting mardi matin prochain. J’ai une démo à faire à un client potentiel.
Cordialement,
Y.M.

De : Portekoi [mailto:notifications@github.com]
Envoyé : vendredi 10 février 2017 14:55
À : groupe-gac/FleetOne
Cc : Yves Madec; Mention
Objet : Re: [groupe-gac/FleetOne] Transfert Clients UGAP (#117)


Je ne vois pas la PJ mais je pense qu'il faut effectivement attendre demain pour que le reporting soit rechargé.

**Comment by Portekoi** [comment]
@MamboJoel Comment désactiver le reporting? Quel est le risque s'il se charge comme chaque jour?

**Comment by MamboJoel** [comment]
Pourquoi désactiver le reporting ?
Yves effectue une présentation importante auprès d'un prospect mardi. Ne touchons à rien en attendant.
