### ISSUE TITLE
Problème ADV : Liste des factures à recevoir (Gestion de parc)

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#118]
Nous avons un problème dans l'outil comptabilité dans l'onglet "Liste des factures à recevoir" : 
http://comptabilite.sdpv.com/Ugap/InvoiceList.aspx?Action=ARecevoir

Pour ID 323210 nous avons une facture à recevoir de 1486.02 HT alors que nous devrions avoir 1804.45 € HT

Pour ID 323211 nous avons une facture à recevoir de 1602.66 € HT alors que nous devrions avoir 1946.08 € HT

C'est comme si la facturation de la gestion était paramétré à 0.7 au lieu de 0.8 de la facturation client. 

![image](https://cloud.githubusercontent.com/assets/22617815/22823137/a07d1d88-ef82-11e6-863f-18d024fc3f01.png)

**Comment by Portekoi** [comment]
Je ne sais pas si cela peut aider mais si je recherche les `customer` ayant un coefficient de gestion à `0.7` et gérés par l'utilisateur "PIEGAY", j'en trouve 10 :

DEPARTEMENT DU LOIRET
Agence territoriale d'Orléans
Agence territoriale Montargis
Agence territoriale Pithiviers
Agence territoriale Sully
Secteur Fonctionnel Fleury
METROPOLE EUROPEENNE DE LILLE
SIRTOM DE LA REGION FLERS CONDE
INERIS
VILLE DE LEVALLOIS

Mais je n'arrive pas encore à lier le les `Invoice` avec le client.

**Comment by Portekoi** [comment]
J'ajoute : 5 `enfants` pour `DEPARTEMENT DU LOIRET`  :

Agence territoriale d'Orléans
Agence territoriale Montargis
Agence territoriale Pithiviers
Agence territoriale Sully
Secteur Fonctionnel Fleury

**Comment by MamboJoel** [comment]
Cela règle-t-il le problème Cyril ?

**Comment by PIEGAY** [comment]
Le problème reste entier

**Comment by MamboJoel** [comment]
@PIEGAY les données sont écrite comme cela dans la table des factures. Je peux investiguer sur le scénario qui a abouti à cette anomalie ou simplement directement corriger, de manière ponctuelle, les données pour ces deux factures.

**Comment by Portekoi** [comment]
Est ce que ce coefficient peut être modifié après création du client? Et si oui, se peut il qu'il ait été modifié après la génération de ces factures?

**Comment by PIEGAY** [comment]
Le coefficient peut être modifié à n'importe quel moment. 
C'est une variable accessible depuis l’administration ADV.

Je ne pense pas qu'il ait été modifié... mais je ne peux pas l'affirmer

**Comment by MamboJoel** [comment]
Seulement ces factures sont déjà générées.
Souhaites-tu que l'on modifie manuellement les montants ? Ou ces deux cas risquent-ils de se reproduire et il nous faudrait investiguer davantage ?

**Comment by PIEGAY** [comment]
Tu peux modifier les montants manuellement afin que nous puissions facturer correctement et on fait le point le mois prochain si l'erreur se reproduit.

**Comment by MamboJoel** [comment]
J'ai effectué les modifs. Tu peux vérifier.

**Comment by PIEGAY** [comment]
C'est bon.
On reste vigilant pour le mois prochain.

**Comment by PIEGAY** [comment]
Les données n'ont pas été mises à jour dans la page suivante : 
http://comptabilite.sdpv.com/Ugap/InvoiceList.aspx?Action=ToExport 

Id : 323211
Id : 323210

**Comment by MamboJoel** [comment]
C'est problématique.
Tous les totaux que j'avais modifiés (TotalHT,TVA ,CHT ,CTVA, CTTC, T20, HT20) ont était écrasés et remplacés par les totaux erronés.
Manifestement une routine de calcul est passé à la suite d'une procédure que vous avez enclenchez sur les pages. Tu peux m'aiguillez à ce titre ?
@meillere , tu peux m'éclairer sur ce phénomène ?

**Comment by MamboJoel** [comment]
J'ai réécrit les totaux attendus.

**Comment by PIEGAY** [comment]
Je pense que la routine a été lancée lors de la génération de la facture avec l'export dans sage. 
Merci pour la modification

**Comment by MamboJoel** [comment]
J'ai effectué d'autres correctifs. C'était un problème au niveau de la ligne de commande où le "Discount" était à 0.7 au lieu de 0.8. D'où vient cette donnée erronée ?


**Note technique **
J'ai trouvé la procédure `Waybis.Sdpv.ManagementSDPV.Invoice.ComputeTotals()` qui effectue les calculs. Elle se fonde sur `InvoiceItem.SellPrice` et `InvoiceItem.Discount`
Pour corriger j'ai écrit un test unitaire et lancé :
```SQL
update invoicedetail set discount = 20, sellprice = 1804.45 / 0.8  where invoiceid = 323210
update invoicedetail set discount = 20, sellprice = 1946.08 / 0.8   where invoiceid = 323211
```

**Comment by PIEGAY** [comment]
C'est 0.85 et non 0.80

La donnée est paramétrable ici : http://comptabilite.sdpv.com/Ugap/ClientTree.aspx au client 

![image](https://cloud.githubusercontent.com/assets/22617815/22982523/ba93354c-f39f-11e6-9a7c-41db08b54be6.png)

**Comment by meillere** [comment]
La procédure compute total est déclenchées chaque fois que l'on enregistre une facture ou qu'on change son statut.Elle calcule les sommes en pied de facture par rapport aux lignes

**Comment by meillere** [comment]
Il faut faire attention au Niveau de facturation qui peut être différent pour les travaux et la gestion. Pour le coefficient de gestion c'est le coefficient du client de facturation gestion qui va s'appliquer

**Comment by MamboJoel** [comment]
@PIEGAY précise que le `InvoiceItem.Discount `doit être de 0.85 plutôt que 0.8 comme je l'ai paramétré. @meillere je m'étonne que mon correctif pourtant erroné donne, via `Invoice.ComputeTotal()` quand même un total de facture juste.
Au-delà, comment des totaux faux sont-ils arrivés ? On aurait changé le Discount du client après l'appel de `Invoice.ComputeTotal()` suite à l'un des événement que tu décris ?

**Comment by MamboJoel** [comment]
Le problème est résolu. Voici comment l'anomalie est apparue :

- Le client était paramétré avec Discount = 0.7
- Ces deux factures ont été créées avec ce Discount.
- Le client a été reparamétré avec Discount = 0.85
- Les factures sont restée avec Discount = 0.7, celui ayant cours lors de leur édition.

C'est après tout le fonctionnement normal et attendu.
