### ISSUE TITLE
Urgent : Problème facturation gestion de parc UGAP

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#119]
Sur la facturation du mois de Janvier 2017 pour le client SG ABAQUESNE : 
http://comptabilite.sdpv.com/Public/factureservice.aspx?year=2013&Month=5&ClientID=9748 

Nous obtenons 0 € de frais de gestion 

Or le client a possédé un véhicule HP-009-NO archivé seulement le 01/02/2017. 

![image](https://cloud.githubusercontent.com/assets/22617815/22827995/0e0d6e12-ef9b-11e6-84b1-f07b23d1b42c.png)

par conséquent il devrait apparaître en facturation sur le mois de janvier.

**Comment by MamboJoel** [comment]
[La page du véhicule](http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=c.9171&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=42156&AlertID=&VisitID=&ClientTab=Users&FromDate=01/12/2016&ToDate=31/12/2016&VisitReference=824166&Display=&tab=Edit&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=HP-009-NO&MessageID=&VehicleTab=VehicleInfo&EquipmentID=&VehicleTS=1486394345485&MemberTab=Supplier&ProfileCategoryID=412&ProfileID=9024&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017)

**Comment by MamboJoel** [comment]
C'est réglé @PIEGAY.
@meillere j'ai effectué des modifs assez profondes en surchargeant toute la pile de méthodes (dont des récursives) qui déterminent si un client est actifs ou non.

**Comment by PIEGAY** [comment]
Je viens de faire 2/3 tests cela fonctionne 
Merci

**Comment by PIEGAY** [comment]
J'ai un problème dans l'autre sens : 
Véhicule entrée en gestion au 01/01/2017 et il n’apparaît pas en facturation sur Janvier
Ex : AD-863-QL

http://comptabilite.sdpv.com/Public/factureservice.aspx?year=2013&Month=5&ClientID=15725

**Comment by MamboJoel** [comment]
@meillere
