### ISSUE TITLE
UGAP : Intégration visites - AZUR TRUCKS 

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#120]
Bonjour Nicolas,

Comme il y a 3 mois, il faudrait intégrer les visites réglementaires pour les clients suivants  : 
- NCA / COLLECTE (Id : 14129)
[NCA - Intégration visite BOM - 12022017.xlsx](https://github.com/groupe-gac/FleetOne/files/771116/NCA.-.Integration.visite.BOM.-.12022017.xlsx)

- CC VALLEE DU GAPEAU /SERVICE OM (Id : 15439)
[CCGAPEAU - Intégration visite BOM - 12022017.xlsx](https://github.com/groupe-gac/FleetOne/files/771117/CCGAPEAU.-.Integration.visite.BOM.-.12022017.xlsx)

Est-ce que tu as tous les éléments nécessaires ?

Pour rappel, nous l'avons fait pour NCA sur #75 

Merci d’avance.

**Comment by MamboJoel** [comment]
@Paulhac peux-tu intégrer ces deux fichiers dans la base Fleet, une table tmp_bom ?

**Comment by MamboJoel** [comment]
C'est bon @PIEGAY
