### ISSUE TITLE
Mise à disposition du Log  pour le webservice Ican 566

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#122]
dans fleet j'ai bien les Log transmis par l'Ican 566 véhicule ID = 53737 Immat EG-109-PA
Ces log ne sont pas récupérés par Clovis via le Webservice
dernier Log 10h02

**Comment by MamboJoel** [comment]
Je constate en effet trois logs dans la base, avec pour ID 

82270
82284
82292

![image](https://cloud.githubusercontent.com/assets/3832009/22969536/25c78eb6-f36f-11e6-906d-db212a63e5ec.png)

**Comment by MamboJoel** [comment]
Seulement je ne reproduis pas l'anomalie. En passant ces paramètres au webservice (date au format mm/jj/aaaa pour des raisons techniques) :

![image](https://cloud.githubusercontent.com/assets/3832009/22969841/3225e74c-f370-11e6-89d5-893c498bae1f.png)

J'obtiens bien les trois logs attendus :

![image](https://cloud.githubusercontent.com/assets/3832009/22969824/23038d6e-f370-11e6-8ce4-2e13a1e4e019.png)

**Comment by MamboJoel** [comment]
J'ai peut-être une piste : 
Le webservice limite à 15 jours la plage des logs qu'il retournera. Je n'ai pas retrouvé dans github les raisons de cette limitation, je suppose que c'est une question de volume. Mais la règle est la suivante : si la date `From` est antérieur de plus de 15 jours à la date `To`, elle est fixée 15 jours avant la date `To`.

Ainsi, si `To` est fixée au 31 mars 2017, et `From` au 1er janvier 2017, `From` sera fixée par le webservice au 16 mars 2017 et les trois logs attendus ici ne ressortiront pas.

Ces deux dates qui auront servi à retourner les logs sont d'ailleurs retourné par le webservice pour des raisons de clarté. Dans mon test précédent elles se présentaient comme ça : 

![image](https://cloud.githubusercontent.com/assets/3832009/22970199/910b4896-f371-11e6-9b08-73053af41857.png)

**Comment by AlainPierreSDPV** [comment]
Ok mais les log en question ont été générés aujourd'hui

**Comment by MamboJoel** [comment]
Oui. Sur mon second message je montre bien que le webservice expose trois logs pour aujourd'hui.

Depuis il y en a deux autres : 

![image](https://cloud.githubusercontent.com/assets/3832009/22971227/5299bd1e-f375-11e6-87f1-e62f7d5e69a7.png)
