### ISSUE TITLE
Réponse faussement négative recherche 3A

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#125]
Pour le véhicule  EH-319-TE
http://membre.force-reseau-gp.com/mj/#url=/Vehicle/Display/&CompanyID=c.16030&HasAlert=false&HasMandatoryAlert=false&MonthsForAlert=3&VehicleID=53873&AlertID=&VisitID=&IsStoped=false&HasIncomingVisit=false&IsHot=false&HasLicence=true&Licence=EH&ClientTab=Vehicles&tab=Edit&VehicleTab=Equipment-65871&EquipmentID=65871&VehicleTS=1487929364792&Display=&MessageID=&MemberTab=Info
                                                         réponse de 3A  "véhicule introuvable"

dans Fleet Reception
![image](https://cloud.githubusercontent.com/assets/22592053/23298590/9557ea3a-fa7e-11e6-8d21-67ce2bcae6c0.png)

**Comment by MamboJoel** [comment]
Le véhicule est bien retourné coté FR.
Mais pas coté Fleet.

**Comment by Portekoi** [comment]
Le bogue semble avoir été corrigé : 
![image](https://user-images.githubusercontent.com/1560754/32133692-d58e1e46-bbdd-11e7-9112-fa949a168119.png)
