### ISSUE TITLE
UGAP : Mise à jour de la table des prix de gestion UGAP 2 (accord cadre n° 771063) avant le 01/03/2017

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#126]
@MamboJoel,

Ci-joint la table de mise à jour de la table des prix de gestion UGAP 2 (accord cadre n° 771063) à faire avant le 01/03/2017 ? 

Merci 

[Tarif gestion UGAP2 02 2017.xlsx](https://github.com/groupe-gac/FleetOne/files/803374/Tarif.gestion.UGAP2.02.2017.xlsx)

**Comment by PIEGAY** [comment]
Est-ce que tu as pu faire la mise à jour ? 
Merci

**Comment by MamboJoel** [comment]
C'est ok pour moi. Tu peux checker.

**Comment by PIEGAY** [comment]
C'est bon - parfait
