### ISSUE TITLE
Modification de rattachement Membre et clients

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#127]
le membre 449 "GAP" récupère les clients    id =  4002 "Clovis APVI" et 2532 "Clovis Alpes PVI Gap".
le membre 350 "ORANGE" récupère le client id =2529 "Clovis Orange".

Le membre Id = 5143 "ATL" récupère comme membre enfant de "ATL" le membre Id = 5312  "HBL" avec ses 3 clients 
15291 " Client contrat CE"
2528 "HBL Clovis LLD"
958 "Location courte durée"

le gestionnaire User ID= 601 "Alain BOUTIERE" reste le gestionnaire du membre "HBL"

**Comment by Portekoi** [comment]
@AlainPierreSDPV : Je n'ai migré que "Clovis APVI" vers "GAP". Merci de confirmer que c'est bon. Si oui, je m'occuperai des autres. Merci

**Comment by AlainPierreSDPV** [comment]
C'est Ok pour moi

**Comment by Portekoi** [comment]
J'ai fait le nécessaire. Pouvez-vous vérifier? Merci

**Comment by AlainPierreSDPV** [comment]
Pour moi c'est conforme mais j'ai demandé aux gestionnaires de vérifier et de me le confirmer.
Je te tiens au courant.
