### ISSUE TITLE
UGAP : Mouvement de clients UGAP (Double arborescence)

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#128]
Nicolas, 

Quelques clients UGAP gérés actuellement sur la plateforme bascule en gestion chez des franchisés. 
Par conséquent, il faut me réaliser les doubles arborescences suivantes : 

**DIR CENTRE EST**

les id des clients concernés : 
- 8325 (District Chambéry)
- 8326 ( District Grenoble)
- 8327 (District Lyon) 

Id parent côté SDPV : 8207 (DIR CENTRE EST)
Id parent côté FRANCHISE : 14288 (UGAP – GROUPE BERTHIER )

**DIR NORD OUEST**

les id des clients concernés : 
- 9748 (Abaquesne)
- 9051 (Evreux)
- 9056 (Dreux)
- 9747 (Cellule radio) 

Id parent côté SDPV : 9050 (DIR NORD OUEST)
Id parent côté FRANCHISE : 280 (CODICA)

**DIR CENTRE OUEST**

les id des clients concernés : 
- 9201 (Périgueux)
- 9202 (A20 Uzerche)

Id parent côté SDPV : 9200 (DIR CENTRE OUEST)
Id parent côté FRANCHISE : 370 (REGITRUCKS)

**Comment by PIEGAY** [comment]
Nous avions déjà effectué une opération similaire #71

**Comment by PIEGAY** [comment]
Est-ce que tu pourras me le faire demain ? 

Merci d'avance

**Comment by AlainPierreSDPV** [comment]
Appel de Michel Alexandre ce matin il voit les véhicules des districts Chambery Grenoble et Lyon mais les ils ne sont pas rattachés à la propriété "UGAP" qui est donnée par la double arborescence
 Ces districts doivent avoir également comme parent Id côté SDPV Grand Compte : 8207 (DIR CENTRE EST)

**Comment by PIEGAY** [comment]
En effet ils n'apparaissent plus chez moi

**Comment by AlainPierreSDPV** [comment]
Le même Pb existe pour CODICA et REGITRUCKS

**Comment by MamboJoel** [comment]
Ok. C'est plus délicat cette fois-ci car j'essaie d'effectuer cette intervention par programmation plutôt qu'à la main, afin d'automatiser ça pour la prochaine fois.

**Comment by MamboJoel** [comment]
Je fais des tests sur Périgueux. Est-ce que vous pouvez vérifier qu'il est paramétré comme souhaité ?

**Comment by PIEGAY** [comment]
ok pour Périgueux

**Comment by MamboJoel** [comment]
C'est bon pour tout.

Note technique : développement de la procédure stockée : `MoveClientToCompany`

**Comment by AlainPierreSDPV** [comment]
Michel alexandre me dit qu'il a maintenant accès aux véhicules mais qu'il n'a pas la main sur les profils

**Comment by MamboJoel** [comment]
Ah... Ce sont des profils systèmes non ? Il est pas censé les modifier.

**Comment by AlainPierreSDPV** [comment]
@PIEGAY   cyril je pense probablement qu'il faut verrouiller mais c'est à toi de répondre

**Comment by PIEGAY** [comment]
On va demander à Michel de dupliquer le profil, le modifier et le réaffecter. 
On évitera le risque que le profil soit utilisé par un autre utilisateur. 

Qu'en penses tu @AlainPierreSDPV  ?

**Comment by MamboJoel** [comment]
Au besoin il peut m'envoyer une liste de couple VehicleID/ProfileID sous xls.

**Comment by AlainPierreSDPV** [comment]
La solution de Nicolas me convient bien mais c'est à toi de décider

**Comment by PIEGAY** [comment]
Pour moi c'est bon.
