### ISSUE TITLE
IPPOLITO TRUCKS - Modification de l'arborescence

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#13]
Nicolas, 

A la demande du groupe IPPOLITO, tu trouveras ci-dessous un changement d'arborescence (avec les id des nouveaux parents) : 

ID 8739 "CE ATL" - Nouveau parent : ID 920 "VEHICULES EN CE"
ID 10591 "CE TTS" - Nouveau parent : ID 920 "VEHICULES EN CE"
ID 14585 "VGP ET EXTINCTEURS" - Nouveau parent : ID 15312 "VGP ET EXTINCTEURS"

Un client est vierge et nous n'arrivons pas à le supprimer : ID 11163. Est-ce que tu peux le supprimer ? 

Merci

**Comment by MamboJoel** [comment]
C'est ok pour tout ça.
Tu peux vérifier ? Et si c'est correct clore cette 'issue" ?
Merci.
