### ISSUE TITLE
Sauvegarde de la visite

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#132]
Cyril m'annonce que la sauvegarde de la visite Fleet est très lente ce matin.
Et ce, comme jeudi dernier.
@meillere peux-tu constater l'anomalie et regarder s'il y a un travail périodique sur le serveur ?
Je suis en consultation médicale ce matin.

**Comment by MamboJoel** [comment]
NB : Cyril avait remonté l'anomalie jeudi 2 mars.

**Comment by MamboJoel** [comment]
Sur [cette visite](http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.499&HasAlert=true&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=2011&AlertID=&VisitID=857713&Display=&tab=Visits) je constate un délai de 5 secondes.

**Comment by MamboJoel** [comment]
Vous aussi ?

**Comment by PIEGAY** [comment]
Cela refonctionne depuis quelques instants. 
Nous avions des délais de plusieurs minutes en début de matinée (sur l'ensemble de la France).

**Comment by Portekoi** [comment]
Il faudrait programmer une trace jeudi matin prochain qui démarrerait à 6h00 pour se terminer à 10h00. On y verrait plus clair je pense

**Comment by AlainPierreSDPV** [comment]
Information de Eric Tetet.
Pb également ce matin sur le portail SDPV.com  probablement concomitant à Fleet  pas de réponse sur la fonction recherche pièce pendant une vingtaine de minutes.

Est ce qu'une requête à pu mettre à genoux le CPU ?

**Comment by MamboJoel** [comment]
@Portekoi est-ce que tu paramétrer ça ?
- De 8h30 à 10h30
- Chaque jour ouvré (car c'est arrivé aussi un mercredi)

**Comment by Portekoi** [comment]
Je n'ai jamais planifié. Je peux regarder sauf si @jlenormant a déjà fait cela.

**Comment by Portekoi** [comment]
Ok j'ai trouvé une solution. Je vais voir mettre cela en place rapidement sous réserve que SQL Profiler soit bien installé.
Je limite la taille des fichiers traces à 50 Mo et je ne prends que les évènements `RPC Complete` (Requête SQL) et `Batch Complete` (PS)

**Comment by jlenormant** [comment]
Non désolé, je n'ai jamais fait de planification de trace

**Comment by Portekoi** [comment]
@jlenormant  Il faut passer par une procédure stockée. Tu sais si SQL Profiler est présente dessus?

**Comment by jlenormant** [comment]
Ah non, mais le profiler c'est pas seulement pour analyser la trace ? Il me semble que tu n'as pas besoin de lui pour planifier la proc stoc. Je n'ai peut-être pas compris ce que tu voulais faire.

**Comment by Portekoi** [comment]
J'utilise ``sp_trace_create` par exemple et je pensais que c'était installé avec Profiler et non par défaut avec SQL Serveur. Je vais tester. Je te dirai.

**Comment by Portekoi** [comment]
J'ai créé la procédure stockée "fleet.dbo.TrcTemplate" qui contient un profil de trace. 
J'ai mis un filtre sur la durée : 2 secondes minimum.

Cette procédure écrit un fichier *.trc dans le dossier passé lors de l'appel. Exemple :

```
-- pour avoir la commande xm_cmdshell d'activée
EXEC sp_configure 'show advanced options', 1
RECONFIGURE
EXEC sp_configure 'xp_cmdshell', 1
RECONFIGURE
-- Démarrage de la trace pour 2 minutes
EXEC fleet.dbo.TrcTemplate @Folder = 'd:\SqlProfiler\traces', @DureeMinute = 2
 -- on désactive la commande xp_cmdshell
EXEC sp_configure 'xp_cmdshell', 0
RECONFIGURE
EXEC sp_configure 'show advanced options', 0
RECONFIGURE
```
Je viens de l'exécuter durant 2 minutes et la procédure "exec ClearVehicleLogFromAttack " a mis par exemple plus de 11 secondes.

Pour vérifier et consulter, il suffit d'ouvrir le fichier créé par la procédure stockée : 
Exemple : 
D:\SqlProfiler\traces\20170309_1305\trace.trc

Pour regrouper sur la durée, cliquer sur l'icône en haut à gauche "Propriété" > "Sélection des événements" > "Organiser les colonnes" > puis faire monter "Duration" dans "Groupe" comme ceci :

![image](https://cloud.githubusercontent.com/assets/1560754/23749904/c1d50560-04ca-11e7-8377-e1b2017ecbbd.png)

Cliquez ensuite sur "OK" et vous aurez cette vue : 

![image](https://cloud.githubusercontent.com/assets/1560754/23749952/fc9fef02-04ca-11e7-8b09-6d866e1a7cf8.png)

Je vais voir maintenant pour porgrammer cela tous les matins en jours ouvrés de 8h30 à 10h30.

**Comment by Portekoi** [comment]
Je viens de la planifier pour tester à aujourd'hui à 13:26 et le fichier *trc est en cours d'alimentation.
Si c'est bon, je programme comme demandé

**Comment by Portekoi** [comment]
Résultats : toujours la même procédure qui remonte :

![image](https://cloud.githubusercontent.com/assets/1560754/23750393/0cc02684-04cd-11e7-97fb-339482bf331f.png)

j'ai créé le job : AuditSlowQuery_Trace

Paramétré comme ceci :

![image](https://cloud.githubusercontent.com/assets/1560754/23750453/5a0abecc-04cd-11e7-9f54-702179530830.png)

Durée : 120 minutes.

**Comment by Portekoi** [comment]
La job a bien démarré. Réponse à 10h30.

**Comment by Portekoi** [comment]
Le script tourne toujours. Pas mal de requêtes ressortent comme étant gourmandes en ressources.

Les deux remontant le plus souvent au dela des 30 secondes : 

```

> 30 secondes (présente de très nombreuses fois)
exec ClearVehicleLogFromAttack

> 30 secondes  (présente de très nombreuses fois)
exec sp_executesql N'select * from (SELECT  ii.InvoiceNumber, ii.LineTypeID,right(ii.Reference,10) as Reference10,ii.reference, ii.Libelle, ii.PU, ii.Qty, ii.Discount, ii.CodeTVA, ii.TotalHT, convert(decimal(18,2),convert(decimal(18,2),t.prix)*1.08/100) AS TarifUGAP,   t.idfamille,g.remise as RemiseUGAP,ii.sort,  case when ii.pu=convert(decimal(18,2),convert(decimal(18,2),t.prix)*1.08/100) then 1  when ii.pu<convert(decimal(18,2),convert(decimal(18,2),t.prix)*1.08/100) then 2  when ii.pu>convert(decimal(18,2),convert(decimal(18,2),t.prix)*1.08/100) then 3  else 0  end as CodeTarif,  Case when  ii.Discount=CONVERT(decimal(10,2),g.remise) then 1  when ii.Discount>CONVERT(decimal(10,2),g.remise) then 2  when ii.Discount<CONVERT(decimal(10,2),g.remise) then 3  else 0  end as CodeRemise,''VF6'' as Vin3  FROM (select  * from InvoiceItem where InvoiceItem.InvoiceNumber = @p1 and InvoiceItem.LineTypeID=1)  AS ii  LEFT OUTER JOIN   Okelia.dbo.Tarif AS t ON t.artnr = right(ii.Reference,10)  left outer join Okelia.dbo.famille as f on f.idfamille =  t.idfamille  left outer join (select * from fleetR.dbo.GcGrille as gr where gr.GCID=21 and gr.VIN3=''VF6'') as g on t.idfamille=g.famille ) as req order by req.sort',N'@p1 nvarchar(15),@p2 nvarchar(3)',@p1=N'3-0-2017-713575',@p2=N'VF6'


```

Je joins un fichier pour celles dépassant les 10 secondes. A voir pour les autres ensuite.
[Slow-Queries.txt](https://github.com/groupe-gac/FleetOne/files/847004/Slow-Queries.txt)

**Comment by MamboJoel** [comment]
@PIEGAY annonce que le problème survient de nouveau ce matin. @Portekoi tu as mis en place une trace, est-il possible d'en tirer des conclusions ?

**Comment by Portekoi** [comment]
La trace est en cours. Elle termine à 10h30. Dès que c'est bon, je refais un point pour voir.

**Comment by Portekoi** [comment]
Mais tu as déjà un début de conclusion sur ce commentaire : https://github.com/groupe-gac/FleetOne/issues/132#issuecomment-286981750

**Comment by Portekoi** [comment]
Voilà la requête responsable je pense : Durée : 12 minutes
```

 Select  o.ID As VisitID , v.CustomerID  As VehicleCustomerID , cc.Name As VehicleCustomerName , cm.TelePhone As VehicleCustomerAddressTelephone , o.SupplierID As VisitSupplierID , sc.Name As VisitSupplierName , sc.Telephone As VisitSupplierAddressTelephone , v.Name As VehicleName , v.ParkNumber As VehicleParkNumber , v.RegistrationNumber As VehicleRegistrationNumber , v.ID As VehicleID , me.LastKmIndex As VehicleLastKmIndex , e.Name As VisitEquipmentName , o.RvDateIn As VisitDate , o.RvDateOut As VisitEndDate , o.ComputedVisitProcess As VisitComputedProcess , o.ReparationOrder As VisitORNumber , o.ApprouvalNumber As VisitApprouvalNumber , o.InvoiceNumber As VisitInvoiceNumber , o.Price As VisitTotal	 , o.GACInvoiceNumber As VisitGACInvoiceNumber  , o.GACInvoiceID As GACInvoiceID	 , o.GacInvoiceMatchDate As GacInvoiceMatchDate  , o.GacInvoiceMatchUserID As GacInvoiceMatchUserID  , o.InterventionDesignations As VisitInterventionDesignations   From Vehicle v 	Inner Join Equipment e On e.VehicleID = v.ID 	Left Join Equipment me On me.ID = v.MainEquipmentID 	Inner Join [Order] o On o.EquipmentID = e.ID 	Inner Join Customer cc On v.CustomerID = cc.ID 	Left Join Supplier s On o.SupplierID = s.ID 	Left Join Company sc On s.ID = sc.ID 	Left Join [User] cm On cm.ID = v.ClientManagerID Where  	v.IsActive = 1 And o.IsInit = 0 And v.CustomerID In (0, 13549, 869, 2967, 1781, 1271, 6847, 2968, 916, 1498, 2485, 2969, 830, 842, 2758, 2970, 2971, 1859, 2972, 2973, 2974, 2975, 1787, 9378, 13876, 9389, 11722, 9390, 9391, 9450, 9458, 9392, 9393, 9456, 9394, 8203, 8202, 14035, 3669, 3283, 8853, 14394, 14395, 14396, 14397, 14398, 12908, 5834, 8577, 3706, 3782, 502, 3864, 3705, 7473, 14966, 14967, 15725, 14842, 7474, 7105, 6943, 6944, 13951, 15687, 14514, 14543, 14544, 14525, 14553, 14554, 14517, 14549, 14550, 15688, 15690, 15691, 14724, 15025, 14725, 14728, 14726, 15024, 14727, 15021, 15023, 15022, 14520, 14555, 14556, 14515, 14545, 14546, 14513, 14541, 14542, 14527, 14567, 14568, 14526, 14565, 14566, 14524, 14563, 14564, 14512, 13954, 14536, 14537, 13953, 14535, 14533, 14534, 13955, 14540, 14538, 14539, 13952, 14531, 14532, 13956, 14530, 14528, 14529, 14522, 14559, 14560, 14516, 14547, 14548, 14511, 14571, 14572, 14518, 14551, 14552, 14521, 14557, 14558, 13990, 13991, 13993, 14745, 7604, 14752, 15438, 15440, 15439, 7613, 7643, 7645, 7644, 7603, 13754, 13755, 13756, 13757, 13758, 13759, 7605, 8208, 8661, 16062, 8190, 14815, 14814, 14812, 6875, 6872, 6873, 13337, 13361, 13444, 13446, 13447, 13445, 15980, 15981, 15983, 15993, 15994, 15995, 15996, 15997, 15985, 16009, 16010, 16011, 16012, 16013, 16014, 16015, 15984, 15998, 15999, 16000, 16001, 16002, 16003, 16004, 16005, 16006, 16007, 16008, 15982, 15987, 15988, 15989, 15990, 15991, 15992, 15986, 16016, 16017, 16018, 16019, 16020, 16021, 16022, 14250, 14251, 14252, 14253, 14254, 8209, 15948, 14246, 14249, 14248, 14604, 14128, 14129, 7371, 14811, 14878, 14880, 14881, 14879, 14877, 6797, 12452, 12453, 12454, 7584, 7991, 7990, 11582, 14777, 15033, 15816, 15820, 15818, 15817, 15819, 15845, 15919, 14813, 14831, 14832, 14833, 14834, 13255, 13259, 13257, 13258, 13256, 16114, 16115, 7329, 10346, 10347, 6844, 6845, 7330, 7303, 7304, 7308, 7309, 7305, 7306, 11657, 12729, 11686, 11687, 11681, 11683, 11682, 11679, 11680, 11685, 11684, 12728, 11675, 11676, 11677, 11674, 11673, 11678, 12727, 11671, 11666, 11665, 11672, 11668, 11670, 11669, 11667, 11337, 11315, 11321, 11329, 11336, 11326, 11327, 11328, 11333, 11314, 11334, 11318, 11313, 11319, 11311, 11324, 11332, 11312, 11320, 11310, 11317, 11331, 11325, 11335, 8207, 8325, 8328, 8329, 8330, 8331, 8326, 8332, 8224, 8227, 8229, 8235, 8232, 8234, 8230, 8327, 12721, 8333, 8334, 8571, 8572, 8225, 8226, 8228, 8231, 8233, 8236, 12658, 8237, 8238, 8212, 8214, 8216, 8217, 8218, 8220, 12659, 8213, 8215, 8219, 8221, 8222, 8223, 9200, 9207, 9320, 9323, 9321, 16088, 9237, 9322, 14036, 9205, 9319, 9318, 9226, 9202, 9214, 9213, 9215, 9203, 9310, 9311, 9312, 9313, 9314, 9220, 9204, 9316, 9317, 9315, 9223, 9201, 9211, 9210, 9208, 9212, 9209, 9206, 9327, 9328, 9325, 9326, 9324, 9232, 8550, 8534, 10857, 8535, 8539, 8540, 8537, 8538, 8536, 8530, 10858, 8532, 8533, 8531, 8519, 10862, 8520, 8521, 8522, 8523, 8512, 10859, 8513, 8514, 8515, 8516, 8517, 8518, 8507, 10860, 8509, 8510, 8511, 8508, 8541, 10861, 8547, 8542, 8545, 8546, 8543, 8544, 8524, 10863, 8525, 8527, 8526, 8528, 8529, 10883, 10884, 10905, 11395, 10906, 10907, 10908, 10909, 10886, 11396, 10911, 10912, 10913, 10914, 10910, 10915, 10885, 10896, 11397, 10897, 10898, 10899, 10900, 10901, 10902, 10903, 10904, 10887, 11398, 10892, 10893, 10894, 10895, 9657, 9658, 10850, 9665, 9666, 9667, 9668, 9659, 10851, 9669, 9670, 9671, 9672, 9673, 9660, 10852, 9674, 9675, 9661, 10853, 9676, 9677, 9678, 9679, 9662, 10854, 9680, 9681, 9682, 9663, 9683, 9684, 9664, 9685, 9050, 9747, 9051, 10819, 9057, 9058, 9059, 9060, 12692, 9056, 10821, 9089, 9090, 9091, 9092, 9093, 10820, 9054, 10822, 9065, 9066, 9067, 9068, 9069, 9070, 9071, 9072, 12694, 9052, 10823, 9076, 9077, 9078, 9079, 9053, 10824, 9082, 9083, 9084, 9085, 9081, 9086, 9087, 9748, 10653, 10638, 10643, 10640, 10641, 10642, 10639, 10644, 10645, 10646, 10652, 10648, 10649, 10647, 10651, 10650, 8883, 7331, 13549, 8885, 8886, 8887, 8830, 8831, 8832, 8833, 8834, 8835, 8888, 8889, 8891, 8890, 8893, 8892, 8836, 8838, 8837, 8875, 8874, 8873, 8842, 8840, 8841, 8839, 7636, 8240, 8152, 14049, 16072, 15572, 14633, 8196, 14402, 14418, 8198, 14417, 8199, 14280, 14292, 14419, 15660, 8200, 14180, 14809, 14613, 8201, 8193, 8194, 8195, 12827, 15658, 7637, 10568, 14510, 8019, 8205, 8210, 8206, 12581, 12829, 10772, 11583, 8150, 8964, 9333, 9334, 9346, 10509, 9340, 9341, 9343, 9350, 10595, 9351, 9352, 9353, 9358, 10597, 10510, 9360, 9362, 9364, 9366, 10596, 9380, 10598, 10876, 9381, 9382, 9383, 10480, 15568, 9385, 8962, 15972, 15973, 9243, 14798, 9244, 9245, 9246, 9247, 9248, 9249, 9250, 9251, 12899, 9252, 9253, 14841, 9254, 15268, 9255, 9256, 15752, 15763, 9257, 9259, 9260, 9261, 9262, 9263, 9264, 9265, 9266, 9267, 15264, 9268, 9269, 15755, 15252, 9270, 9271, 12765, 9272, 9273, 15240, 9274, 9275, 15757, 9276, 15756, 15758, 9277, 15754, 9278, 9279, 9280, 9281, 9282, 9283, 15261, 15762, 9285, 9286, 15760, 15267, 9287, 9289, 15265, 9290, 9291, 9292, 9293, 9294, 9296, 9297, 9298, 9299, 9302, 15975, 9303, 9330, 9331, 9332, 15753, 9335, 9336, 9338, 9339, 9342, 15759, 9344, 15749, 9345, 10875, 15767, 9347, 9348, 9354, 9355, 9357, 9359, 9361, 9363, 9365, 9367, 9166, 9368, 9167, 9369, 9168, 14190, 15750, 15748, 9370, 15747, 14192, 9371, 9372, 14191, 9373, 9377, 9374, 15761, 9375, 14623, 9398, 9376, 15751, 14062, 15340, 15339, 15341, 15338, 14188, 16066, 16065, 9169, 9170, 9171, 9172, 9173, 9174, 9395, 9396, 15269, 9397, 9399, 14063, 8976, 14589, 14590, 8963, 16079, 15042, 16078, 16076, 15045, 16074, 15046, 16075, 15048, 16077, 15043, 15044, 15047, 15041, 13875, 16080, 10856, 14624, 14488, 14487, 9111, 9112, 10622, 9113, 9579, 9114, 9115, 12821, 9116, 9117, 9118, 9119, 9121, 9123, 13223, 9124, 9125, 9126, 9128, 9129, 9130, 9132, 9133, 10623, 9134, 10624, 9135, 9136, 9137, 9138, 9139, 9140, 9141, 9142, 9143, 9144, 9145, 9146, 9147, 9148, 9149, 9150, 9151, 9152, 9153, 9154, 9155, 9156, 9157, 9158, 13873, 9108, 9159, 9160, 9161, 9162, 9163, 13874, 9164, 9165, 8966, 15243, 10877, 9461, 15244, 14005, 9460, 8970, 10878, 9462, 8967, 9482, 10864, 9489, 9463, 9483, 9471, 9466, 9469, 9486, 9488, 9474, 9477, 9465, 9470, 9487, 9467, 9478, 9476, 9464, 9480, 9475, 9468, 9472, 9473, 9481, 9484, 9485, 9490, 9479, 8968, 8977, 14490, 14193, 14489, 15712, 14491, 14492, 15714, 15716, 15713, 8151, 8192, 8191, 13362, 13363, 13364, 13367, 13365, 13368, 13373, 13369, 13370, 13371, 13366, 13372, 12589) Order By o.RvDateIn Desc


```

Au niveau des horaires, cela a ramé de 9:08 à 9:20 et je vois pas mal de requêtes qui ont dépassé les 10 secondes durant cette période, du fait, je pense, de cette requête.

**Comment by jlenormant** [comment]
Juste une question : je ne vois que des requêtes fleet, est-ce que la trace est faite sur toutes les bases de données ou seulement fleet ?

**Comment by Portekoi** [comment]
Normalement cela devrait être sur toutes les bases.

**Comment by MamboJoel** [comment]
Merci beaucoup pour ces infos.

Dans cette requête la clause `Where` et en particulier le `v.CustomerID In` ... sautent aux yeux comme une aberration.

- `Waybis.Sdpv.Fleet.VisitFactory.GetVisitsDataReader()` construit cette requête. Cette méthode est appelée à l'affichage d'une page tout à fait usuelle de Fleet où l'utilisateur affiche les visites qui le concernent.
- Je m'interroge donc sur la périodicité des plantages. Souvent le matin. Le mercredi ou bien le jeudi. Et puisque cette page est très ordinaire, pourquoi cela ne plante-t-il pas tout le temps ?

Deux choses projets :

- Trouver le user qui lance une telle requête (en analysant les `CustomerID` peut-être) et l'interroger sur sa routine d'usage de Fleet et de la page visite en particulier, pour déterminer si cela correspond aux jeudis et mercredis matins seuls.
- Refactoriser cette `Waybis.Sdpv.Fleet.VisitFactory.GetVisitsDataReader()` de toute façon.

**Comment by MamboJoel** [comment]
@Portekoi tu peux peut-être debugger avec un pas à pas sur `Waybis.Sdpv.Fleet.VisitFactory.GetVisitsDataReader()` afin de trouver une manière d'obtenir une liste de `CustomerID` aussi volumineuse. Je me demande s'il ne s'agit pas tout simplement d'un admin sys, Alain ou Cyril.

Le résultat de cette recherche aboutira de fait sur la refactorisation appropriée. Sachant bien sûr qu'on n'a pas établi encore que c'était cette seule requête qui était à l'origine des lenteurs périodiques.

**Comment by MamboJoel** [comment]
@PIEGAY on pense que le ralentissement vient de la quantité de données retournées par la requête des visites. Un utilisateur intérroge le jeudi matin ou le mercredi matin l'ensemble des visites du client UGAP Global. Cela ressort près de 80000 visites et le volume met toutes les autres requêtes au tapis.
Il s'agit d'un de ces utilisateurs :

![image](https://cloud.githubusercontent.com/assets/3832009/25010680/22f8aa66-206b-11e7-828c-87fe9c758eef.png)

Pour tester cette hypothèse je te propose de limiter à 1000 résultats. A priori l'utilisateur s'en plaindra, et l'on pourra trouver une manière plus appropriée de répondre à son besoin. Est-ce que t'es ok ?

**Comment by Portekoi** [comment]
@PIEGAY : peut on passer le résultat de cette lourde requête à 1000 lignes maximum? Comme le souligne @MamboJoel, cela nous permettra de voir comment aider l'utilisateur concerné car cela ne sert à rien d'afficher 8000 lignes sur un écran de PC.

**Comment by Portekoi** [comment]
Je viens de regarder à nouveau.  Voici un découpage par durée :
*Plus de 15 secondes : *
`Select Top 5 t.*, f.Marque as societe from ( 	Select einspnr, idpart as artnr, designation1, designation2, dimensions from tecdoc_2_4.dbo.tarif 	Union All 	Select idfour as einspnr, idpart as artnr, designation as designation1, designation2, commentaire as dimensions from catdivers..treference 	Union All 	Select 10000 as einspnr, artnr, designation as designation1, '' as designation2, '' as dimensions from GacInvoice..TarifRT ) t inner join  gestionsdpv1.dbo.fournisseur as f on f.idfour=t.einspnr  left join FournisseurExclu fex on fex.FournisseurID=f.id and fex.GroupeID In (Select idgroupe from membre where idmembre = 17) Where f.contrat=1 and t.designation1 like '2826359%' Collate French_CI_AI And fex.ID is null And f.BtoBOK=1`

*Entre 6 et 12 secondes : *
`exec sp_executesql N'select * from (SELECT  ii.InvoiceNumber, ii.LineTypeID,right(ii.Reference,10) as Reference10,ii.reference, ii.Libelle, ii.PU, ii.Qty, ii.Discount, ii.CodeTVA, ii.TotalHT, convert(decimal(18,2),convert(decimal(18,2),t.prix)*1.08/100) AS TarifUGAP,   t.idfamille,g.remise as RemiseUGAP,ii.sort,  case when ii.pu=convert(decimal(18,2),convert(decimal(18,2),t.prix)*1.08/100) then 1  when ii.pu<convert(decimal(18,2),convert(decimal(18,2),t.prix)*1.08/100) then 2  when ii.pu>convert(decimal(18,2),convert(decimal(18,2),t.prix)*1.08/100) then 3  else 0  end as CodeTarif,  Case when  ii.Discount=CONVERT(decimal(10,2),g.remise) then 1  when ii.Discount>CONVERT(decimal(10,2),g.remise) then 2  when ii.Discount<CONVERT(decimal(10,2),g.remise) then 3  else 0  end as CodeRemise,''VF6'' as Vin3  FROM (select  * from InvoiceItem where InvoiceItem.InvoiceNumber = @p1 and InvoiceItem.LineTypeID=1)  AS ii  LEFT OUTER JOIN   Okelia.dbo.Tarif AS t ON t.artnr = right(ii.Reference,10)  left outer join Okelia.dbo.famille as f on f.idfamille =  t.idfamille  left outer join (select * from fleetR.dbo.GcGrille as gr where gr.GCID=21 and gr.VIN3=''VF6'') as g on t.idfamille=g.famille ) as req order by req.sort',N'@p1 nvarchar(22),@p2 nvarchar(3)',@p1=N'0-0-2017-00/AP00011593',@p2=N'VF1'`

*entre 3 et 6 secondes  :*  
`exec sp_executesql N'Select u.*, Company.ID As [Company.ID], Company.Name As [Company.Name] From [User] u Inner Join UserAuthorization ua On u.ID = ua.UserID Inner Join dbo.GetUserCompanies(@UserID) c On c.CompanyID = ua.NodeID Or (ua.AuthorizationID = 2 Or ua.AuthorizationID = 3) Left Join Company On u.CompanyID = Company.ID Where 1 = 1 And ((FirstName + '' '' + LastName) Like ''%'' + @Name + ''%'' Or LastName Like ''%'' + @Name + ''%'' Or FirstName Like ''%'' + @Name + ''%'' Or u.Email Like ''%'' + @Name + ''%'')',N'@UserID int,@Name nvarchar(6)',@UserID=4734,@Name=N'froger'`

`exec UpdateEquipmentLastIndexesNew @VehicleID=42352,@ClientID=NULL`

*Entre 1 à 3 secondes : * 
`Part_listNew	Tecdoc_2_4` (Tecdoc_2_4)

Concernant celle durant **entre 6 et 12 secondes**, j'en ai déjà parlé à @meillere.

**Comment by PIEGAY** [comment]
Ok pas de soucis pour passer à 1000 lignes. 
Est-ce que nous pouvons imaginer une pagination avec 1000 lignes sur chaque page ? 
Voir 500...
