### ISSUE TITLE
Pas de navigation possible dans Fleet

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#134]
Avec mes login et mot de passe

coté SSO alain.pierre@sdpv.com  et   mot de passe 97Serine@
coté Fleet alain.pierre@force-reseau.com  et mot de passe @Serine97 

L'appairage se fait mais avec alain.pierre@sdpv.com et alain.pierre@force-reseau.com

j'arrive sur la page d'acceuil de Fleet mais je ne peux rien faire

![image](https://cloud.githubusercontent.com/assets/22592053/23958669/2077efa6-09a3-11e7-9910-66d21df8dfc8.png)
merci de regarder cela rapidement je ne peux plus rien faire dans Fleet

**Comment by AlainPierreSDPV** [comment]
L'appairage se fait mais avec alain.pierre@sdpv.com et pas avec alain.pierre@force-reseau.com

**Comment by Portekoi** [comment]
Je pense avoir corrigé le problème. Tu peux réessayer? il faut choisir une concession pour que cela refonctionne.

**Comment by AlainPierreSDPV** [comment]
Merci ! ca refonctionne
