### ISSUE TITLE
Information parasite dans le bon de commande

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#135]
quand l'opération est facturée au contrat d'entretien il y  comme information dans le bon de commande  "Facturer à : `Contrat d'entretien&nbsp;`" il faut supprimer `&nbsp;`

exemple
http://membre.force-reseau-gp.com/Visit/Document2/861267

![image](https://cloud.githubusercontent.com/assets/22592053/24057269/1b72b36a-0b47-11e7-8bc6-73f73cd4fb15.png)

**Comment by Portekoi** [comment]
J'ai corrigé en enlevant le `&nbsp;` mais je n'ai pas trouver le lien pour pouvoir tester.

Et le lien fourni dans l'issue me renvoie une erreur.

**Comment by AlainPierreSDPV** [comment]
choisir la visite 880560  cliquer sur le lien "contact"
http://membre.force-reseau-gp.com/Visit/Document2/880560
constater que  &nbsp;  est toujours présent     Facturer à : Contrat d'Entretien&nbsp;

**Comment by Portekoi** [comment]
C'est livré. Pouvez-vous tester? Merci

**Comment by AlainPierreSDPV** [comment]
c'est Ok merci
