### ISSUE TITLE
Bug dans le contrôle de la ventilation des factures 

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#137]
Utiliser le reporting avec comme login : http://rep.gestionparc.com/Controleventilation.aspx
mot de passe : sebastien
onglet reporting choix "contrôle de ventilation" http://rep.gestionparc.com/Controleventilation.aspx
choix:
exercice 2017 , dubreu location client BDM
Constater qu'il n'y a pas de visite non ventilée

aller dans FleetV2 rechercher la visite 844817
constater que la visite en statut facturée n'est pas ventilée

**Comment by MamboJoel** [comment]
En définitive la visite 844817 n'apparaît pas dans le reporting ?
@meillere ça te parle peut-être ?

**Comment by AlainPierreSDPV** [comment]
c'est mort  ...... Sébastien a depuis ventilé la visite
