### ISSUE TITLE
Des logs Ican à destination de clovis ne sont pas exposés par le webservice

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#140]
Le véhicule AA-222-AA existe dans Fleet, mais un log généré le 10/04/2017 n'est exposé à Clovis.

**Comment by MamboJoel** [comment]
Le véhicule AA-222-AA a pour VIN AA-222-AA. Il faut un véritable VIN car c'est sur ce champ que s'effectue le croisement avec les logs ICAN.

**Comment by AlainPierreSDPV** [comment]
VehicleID=54304
CompanyID=c.7432

**Comment by AlainPierreSDPV** [comment]
le VIN est correct
![image](https://cloud.githubusercontent.com/assets/22592053/24904970/94d5df42-1eb2-11e7-9140-dd02aedd2f15.png)

**Comment by MamboJoel** [comment]
Il me faudrait le lien de la page source de ce print screen.

**Comment by AlainPierreSDPV** [comment]
http://membre.force-reseau-gp.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=c.7432&VisitProcess=15&VehicleID=54304&AlertID=&VisitID=&FromDate=01/01/2017&ToDate=31/12/2017&Display=&tab=Edit&MemberTab=Users&ClientTab=Vehicles&MessageID=&VisitReference=&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&VehicleTab=Equipment-66402&EquipmentID=66402&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=AA-111-AA&VehicleTS=1491810991005

**Comment by MamboJoel** [comment]
Je teste le webservice avec les paramètres suivants : 

![image](https://cloud.githubusercontent.com/assets/3832009/24907197/7e3db3dc-1ebb-11e7-82ad-0b1d0fa67b22.png)

Et j'obtiens bien les logs de ce véhicule.

![image](https://cloud.githubusercontent.com/assets/3832009/24907207/8ceaaca0-1ebb-11e7-8501-267e79da5409.png)

@ThierryBrehon  avec quels paramètres appelles-tu le service ?

**Comment by ThierryBrehon** [comment]
Bonjour ,

Une idée…
Ne fais tu pas un rapprochement par le fichier AAA ? Ce qui expliquerait qu’avec une immat bidon cela ne fonctionne pas.

Cordialement
Thierry BRÉHON

[cid:image003.jpg@01D2B399.9F9B9EF0]

Responsable Informatique



Tél : +33 4 37 91 25 98
Tél : +33 6 80 61 17 28



Email : t.brehon@clovislocation.com<mailto:t.brehon@clovislocation.com>

Adresse : Le Britannia – Bâtiment C – 20 Bd Eugène Deruelle – 69432 LYON CEDEX 03

[cid:image004.jpg@01D2B399.9F9B9EF0]<http://www.clovislocation.com/>

De : Nicolas Taret [mailto:notifications@github.com]
Envoyé : mardi 11 avril 2017 13:35
À : groupe-gac/FleetOne <FleetOne@noreply.github.com>
Cc : Thierry Brehon <thierry.brehon@coservices.fr>; Mention <mention@noreply.github.com>
Objet : Re: [groupe-gac/FleetOne] Des logs Ican à destination de clovis ne sont pas exposés par le webservice (#140)


Je teste le webservice avec les paramètres suivants :

[image]<https://cloud.githubusercontent.com/assets/3832009/24907197/7e3db3dc-1ebb-11e7-82ad-0b1d0fa67b22.png>

Et j'obtiens bien les logs de ce véhicule.

[image]<https://cloud.githubusercontent.com/assets/3832009/24907207/8ceaaca0-1ebb-11e7-8501-267e79da5409.png>

@ThierryBrehon<https://github.com/ThierryBrehon> avec quels paramètres appelles-tu le service ?

**Comment by MamboJoel** [comment]
Bien vu @ThierryBrehon 
En effet le webservice croise le VIN avec le fichier AAA. Si l'immatriculation n'existe pas dans le fichier le log ressort, avec son VIN, mais sans l'immatriculation.
Ce véhicule a pour VIN VF6VF000X57176985 et ses logs du 10 avril ont pour ID 93809 et 93810.
