### ISSUE TITLE
Impossible de charger Goocle map à partir des données GPS dans Fleet

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#141]
Cette anomalie est sur tous les logs
exemple 
http://membre.force-reseau-gp.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=c.14979&VisitProcess=15&VehicleID=51498&AlertID=&VisitID=&FromDate=01/01/2017&ToDate=31/12/2017&Display=&tab=Logs&MemberTab=Users&ClientTab=Vehicles&MessageID=&VisitReference=&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&VehicleTab=Equipment-66402&EquipmentID=66402&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=AA-111-AA&VehicleTS=1491810991005

![image](https://cloud.githubusercontent.com/assets/22592053/24969086/cdbb8e44-1faf-11e7-8919-01160e4e47c7.png)

**Comment by Portekoi** [comment]
Je vois l'erreur suivante dans la console : "Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"

Je vais voir ce que je trouve dans les archives, voir si la clef n'aurait pas été supprimée.

**Comment by Portekoi** [comment]
C'est corrigé.
