### ISSUE TITLE
Pas d'acces à 3A via Fleet Reception

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#142]
http://fr.sdpv.com
Login: alain.pierre@sdpv.com
PW : xxxx
cliquer sur l'onglet Reception faire une recherche sur une des 3 immat de test 
constater:    erreur du serveur dans l'application '/'.

**Comment by Portekoi** [comment]
@AlainPierreSDPV Je ne reproduis pas l'erreur. Pouvez confirmer que le problème perdure? Merci

**Comment by MamboJoel** [comment]
Moi non plus. J'ai testé par Immat et par Vin. Et pour des véhicules inconnus de notre base.

**Comment by AlainPierreSDPV** [comment]
Non le Pb ne se reproduit plus...
