### ISSUE TITLE
Customisation du menu déroulant "Facturation" pour les opérations Intermarché

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#144]
SDPV devient SDPV C.E
Client devient SDPV à refacturer
![image](https://cloud.githubusercontent.com/assets/22592053/25282733/a4d1749a-26b1-11e7-8868-475fc96df119.png)

**Comment by MamboJoel** [comment]
Règle :
- Retirer la liste déroulante "Facturation"
- Si coché Inclus au CE : Facturation = "SDPV Contrat d'entretien"
- Sinon Facturation = "SDPV à refacturation"

**Comment by PIEGAY** [comment]
@MamboJoel : Est-ce que tu peux regarder ce point car nous commençons à avoir quelques visites à créer. 
Merci

**Comment by Portekoi** [comment]
Comment je peux déterminer que c'est une opération Intermarché?

**Comment by PIEGAY** [comment]
C'est l'ensemble des opérations créer sur les véhicules situés sont les sous clients à "ITM LAI" - Id :16310

**Comment by Portekoi** [comment]
Je regarde si je peux m'en occuper.

**Comment by Portekoi** [comment]
J'ai commencé à modifier l'écran des visites. Je continue demain.

**Comment by PIEGAY** [comment]
@Portekoi est-ce que tu as pu avancer sur cette issue ? 

Merci

**Comment by Portekoi** [comment]
Je n'ai pas terminé. J'avais des soucis avec les menus déroulants. Je suis en congés cette semaine. Je peux avancer la semaine du 31/07 dès mon retour. Cela vous convient?

**Comment by PIEGAY** [comment]
ok parfait

**Comment by Portekoi** [comment]
Voici la liste actuelle des codes et libellés : 

```
Member (Membre)
ClientViaMember (Membre (refacturer))
InternalClient (Client interne)
Client (Client)
Supplier (Fournisseur)
Warranty (Garantie)
Insurance (Assurance)
CE (Contrat d'Entretien)
SDPV (SDPV) (Pour UGAP uniquement)
```

@PIEGAY : Concernant la demande, merci de me confirmer que je garde bien les codes suivants mais que je change les libellés à savoir : 

```
CE (SDPV Contrat d'entretien)
Client (SDPV à refacturation)
```

C'est bien cela?

**Comment by Portekoi** [comment]
OK merci. Je me mets dessus.

**Comment by Portekoi** [comment]
J'ai bien avancé et quasi terminé. Cela sera bon d'ici demain.

**Comment by Portekoi** [comment]
Je viens de livrer.

Merci de tester sur *un* véhicule dès que possible (ITM ou non) et penser à vider votre cache car j'ai dû modifier un fichier javascript.

Exemple de véhicule ITM :
http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=c.8524&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=55922&tab=Visits&VVS_VehicleID=19228&VVS_OrganIDs=9&VVS_NatureIDs=2&VVS_Accounts=&VVS_VehicleType=AllEquipments&VVS_FromDate=15/06/2009&VVS_ToDate=25/01/2017&VVS_Tags=POULIE_Fuite_&ddd=dddd&AlertID=&VisitID=&Display=&MessageID=&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=CV-187-KC

**Comment by MamboJoel** [comment]
On constate des anomalies :

- Aller sur [ce véhicule](http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=c.16385&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=55846&AlertID=&VisitID=904011&HasIncomingVisit=false&IsStoped=false&HasLicence=true&VisitReference=903977&FromDate=01/01/2017&ToDate=31/12/2017&Display=&tab=Visits&Licence=44401&ClientTab=Vehicles&VehicleTab=VehicleInfo&EquipmentID=&VehicleTS=1501741777922)

1. On ne peut pas décocher ça :
![image](https://user-images.githubusercontent.com/3832009/28914031-7502aac4-783a-11e7-9eec-0025cda96698.png)

2. On ne peut pas changer la facturation

3. On clique sur Contact et on constate une facturation pour BASE ITM LAI au lieu de Contrat d'entretien.

(j'ai essayé de faire des screenshots pour 2. et 3. mais ça plantait.)

**Comment by MamboJoel** [comment]
@Portekoi est-ce que tu peux contacter Nicolas Tillet qui me remonte ces anomalies par téléphone :
04 28 00 05 56

**Comment by Portekoi** [comment]
Vous avez vidé le cache pour le fichier JS?

**Comment by Portekoi** [comment]
Je l'appelle.

**Comment by Portekoi** [comment]
OK c'était bien le fichier JS. Par contre, autre modification dans la demande de devis : 

![image](https://user-images.githubusercontent.com/1560754/28914935-b236ada2-783d-11e7-87d8-e120bd49b936.png)

Cela devrait afficher "BASE ITM LAI PAGNY" si on est hors contrat.

**Comment by PIEGAY** [comment]
Non non il faut bien garder : facturer à SDPV dans les deux cas.
Toute la facturation est centralisée par SDPV.

Cyril

Envoyé de mon iPhone

Le 3 août 2017 à 11:21, Portekoi <notifications@github.com<mailto:notifications@github.com>> a écrit :


OK c'était bien le fichier JS. Par contre, autre modification dans la demande de devis :

[image]<https://user-images.githubusercontent.com/1560754/28914935-b236ada2-783d-11e7-87d8-e120bd49b936.png>

Cela devrait afficher "BASE ITM LAI PAGNY" si on est hors contrat.

**Comment by Portekoi** [comment]
Je me demande s'il ne fallait pas mettre `Client` au lieu de `ClientViaMember`

**Comment by PIEGAY** [comment]
Pour ITM LAI

Envoyé de mon iPhone

Le 3 août 2017 à 11:21, Portekoi <notifications@github.com<mailto:notifications@github.com>> a écrit :


OK c'était bien le fichier JS. Par contre, autre modification dans la demande de devis :

[image]<https://user-images.githubusercontent.com/1560754/28914935-b236ada2-783d-11e7-87d8-e120bd49b936.png>

Cela devrait afficher "BASE ITM LAI PAGNY" si on est hors contrat.

**Comment by Portekoi** [comment]
OK @PIEGAY donc je touche à rien.

**Comment by PIEGAY** [comment]
Non c'est bien clientviamember car le garage facture à membre qui refacture le client

Envoyé de mon iPhone

Le 3 août 2017 à 11:23, Portekoi <notifications@github.com<mailto:notifications@github.com>> a écrit :


Je me demande s'il ne fallait pas mettre Client au lieu de ClientViaMember

**Comment by Portekoi** [comment]
Merci pour ces infos. Donc, voici le résultat comme attendu : 

Je ne coche pas "Inclus au CE" : 
![image](https://user-images.githubusercontent.com/1560754/28915261-da87afbc-783e-11e7-97f7-293ba6ec47a1.png)

Document édité : 
![image](https://user-images.githubusercontent.com/1560754/28915300-f81c3264-783e-11e7-90ac-c330976c4dce.png)

Je coche "Inclus au CE" et je sauvegarde la visite :
![image](https://user-images.githubusercontent.com/1560754/28915354-2562eb50-783f-11e7-84b2-4eb3a4632b35.png)

Document édité :
![image](https://user-images.githubusercontent.com/1560754/28915383-424b5aea-783f-11e7-9c19-42f6066de1b1.png)

**Comment by Nicolas69003** [comment]
Ok donc on laisse comme ça. Oui je pense que c'est ce que veut Cyril

**Comment by PIEGAY** [comment]
Cela me semble ok
Je ne peux pas tester complètement car j'ai un accès limité à internet.
Je valide et clôture la semaine prochaine

Envoyé de mon iPhone

Le 3 août 2017 à 11:32, Nicolas69003 <notifications@github.com<mailto:notifications@github.com>> a écrit :


Ok donc on laisse comme ça. Oui je pense que c'est ce que veut Cyril
