### ISSUE TITLE
Création d'un reporting pour le client Intermarché

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#147]
Yves doit nous donner la façon de présenter ce reporting pour les opérations effectuées au titre du contrat d'entretien

**Comment by MamboJoel** [comment]
@PIEGAY nous constatons que vous avez créé un accès reporting pour ITM. Est-ce que nous pouvons pour autant publier les premiers éléments ?

**Comment by PIEGAY** [comment]
Oui pas de soucis.
Les accès créés sont pour nous.

Envoyé de mon iPhone

Le 26 juil. 2017 à 12:45, Nicolas Taret <notifications@github.com<mailto:notifications@github.com>> a écrit :


@PIEGAY<https://github.com/piegay> nous constatons que vous avez créé un accès reporting pour ITM. Est-ce que nous pouvons pour autant publier les premiers éléments ?

**Comment by AlainPierreSDPV** [comment]
sur    http://rep.gestionparc.com/full/Alertes.aspx (accessible par le lien "réglementaire"
il y a des opérations non réglementaires qui sont avec les opérations réglementaires
![reg 3 mois](https://user-images.githubusercontent.com/22592053/29017995-a1a64820-7b59-11e7-8b59-fa799392e2b4.JPG)

**Comment by AlainPierreSDPV** [comment]
maintenance à 3 mois le fichier est vide

**Comment by AlainPierreSDPV** [comment]
le reporting financier est vide alors qu' il y a des visites facturées
exemple :
http://membre.force-reseau-gp.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=c.16375&VisitProcess=10&VehicleID=55913&AlertID=&VisitID=902430&FromDate=01/01/2017&ToDate=31/12/2017&Display=&AlertFromDate=01/01/2017&AlertToDate=27/05/2017&MemberTab=InvoiceList&ClientTab=Organs&tab=Visits&MessageID=&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&IsStoped=false&HasIncomingVisit=false&IsHot=false&HasLicence=true&Licence=BQ-216-DB&ArchiveMonth=01/04/2017+00%3A00%3A00&VehicleTab=Equipment-70299&EquipmentID=70299&VehicleTS=1502094408018&VVS_VehicleID=25146&VVS_OrganIDs=0&VVS_NatureIDs=0&VVS_Accounts=&VVS_VehicleType=AllEquipments&VVS_FromDate=25/03/2010&VVS_ToDate=30/03/2017&VVS_Tags=vidange_

**Comment by AlainPierreSDPV** [comment]
il existe des incohérences dans l'entité facturée et la visite cochée "à facturer à ITM"
exemple 
http://membre.force-reseau-gp.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=c.16375&VisitProcess=10&VehicleID=55898&AlertID=&VisitID=899345&FromDate=01/01/2017&ToDate=31/12/2017&Display=&AlertFromDate=01/01/2017&AlertToDate=27/05/2017&MemberTab=InvoiceList&ClientTab=Organs&tab=Visits&MessageID=&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&IsStoped=false&HasIncomingVisit=false&IsHot=false&HasLicence=true&Licence=AX-189-BF&ArchiveMonth=01/04/2017+00%3A00%3A00&VehicleTab=Equipment-70299&EquipmentID=70299&VehicleTS=1502094408018&VVS_VehicleID=25146&VVS_OrganIDs=0&VVS_NatureIDs=0&VVS_Accounts=&VVS_VehicleType=AllEquipments&VVS_FromDate=25/03/2010&VVS_ToDate=30/03/2017&VVS_Tags=vidange_

**Comment by MamboJoel** [comment]
Damien tu peux regarder ?

**Comment by Portekoi** [comment]
Je regarde

**Comment by Portekoi** [comment]
Pour chaque opération du premier exemple, j'ai bien 'ClientViaMember' : 
![image](https://user-images.githubusercontent.com/1560754/29025411-d24bb8bc-7b76-11e7-99fe-5be81732b9ac.png)

**Comment by Portekoi** [comment]
J'ajoute @meillere pour voir s'il peut intervenir.

**Comment by meillere** [comment]
Etant donné que le reporting ITM est spécifique et que le client ne voit que les factures qui sont a sa charge
le champ imputation n'a pas lieu d'être dans son reporting car c'est une qualification à la ligne de visite(OrderDetail) et que pour ITM la qualification de l'imputation se fait au niveau de la visite (order)
en conséquence le plus simple est de supprimer le cham imputation du reporting ITM

**Comment by meillere** [comment]
C'est fait et j'ai updaté git hub

**Comment by meillere** [comment]
j'ai mis la modif en ligne

**Comment by AlainPierreSDPV** [comment]
Le reporting financier fonctionne il n'est plus à zéro
il y a des visites  réglementaires qui ont été facturées à ITM cela me semble curieux....

**Comment by meillere** [comment]
Effectivement pour la visite 898936
![image](https://user-images.githubusercontent.com/22621226/29068393-87c7a6bc-7c2e-11e7-8b7b-5fc336f95975.png)
Je n'ai pas d'idée sur la façon d'éviter les mauvaises qualifications

**Comment by meillere** [comment]
Peut être dans la page visite de fleet si toutefois tout le reglementaire est inclus dans le contrat d'entretien.

**Comment by AlainPierreSDPV** [comment]
Oui il faut que Cyril nous confirme que c'est toujours le cas à @PIEGAY

**Comment by AlainPierreSDPV** [comment]
le reporting financier est à nouveau à Zéro ce matin
http://rep.gestionparc.com/Full/ReportFindem.aspx

**Comment by AlainPierreSDPV** [comment]
après échange avec Cyril, c'est à la demande du client que les visites préventives trimestrielles sont considérées comme Réglementaires donc ce n'est pas une anomalie

**Comment by AlainPierreSDPV** [comment]
Le tableau de bord du reporting ITM montre une valeur de 23066.16 €  pour Juillet mais quand on demande le détail
"Bilan financier" 2 exercices  il n'y a toujours aucun détail d'exposé

**Comment by meillere** [comment]
C'est corrigé et c'est maintenant cohérent

**Comment by AlainPierreSDPV** [comment]
il reste une anomalie
" financier"   prendre Analyse des coûts par qualification  2017 cliquer sur le cumul reglementaire et constater qu'il y a 2 opérations qualifiés Maintenance usure dans  cette rubrique

**Comment by PIEGAY** [comment]
J'ai trouvé le filtre est à la visite et non à l'opération. 
C'est pour ça
J'ai pas mal de remarques je les envoies à Jacques

**Comment by meillere** [comment]
la seule solution c'est de virer le champ nature des filtres comme je l'ai fait pour le financier.
dites moi si c'est OK mais je crois qu'on n'a pas le choix

**Comment by AlainPierreSDPV** [comment]
C’est moi qui fait une confusion ce tableau présente bien les raisons des arrêts  et il est normal de trouver des op de maintenance même si l’arrêt est pour une cause réglementaire

De : meillere [mailto:notifications@github.com]
Envoyé : dimanche 27 août 2017 21:34
À : groupe-gac/FleetOne <FleetOne@noreply.github.com>
Cc : Alain Pierre <alain.pierre@force-reseau.com>; Author <author@noreply.github.com>
Objet : Re: [groupe-gac/FleetOne] Création d'un reporting pour le client Intermarché (#147)


la seule solution c'est de virer le champ nature des filtres comme je l'ai fait pour le financier.
dites moi si c'est OK mais je crois qu'on n'a pas le choix
