### ISSUE TITLE
Création d'un Catalogue d'opérations spécifiques pour Intermarché 

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#148]
Yves et Cyril  finalise ce catalogue qui  sera dans la rubrique "Opérations sous protocole"
![image](https://cloud.githubusercontent.com/assets/22592053/25283737/0897ff64-26b5-11e7-93c6-3d1c3446357b.png)

**Comment by YvesMadec** [comment]
Bonjour,
Ci-joint la liste des organes à ventiler pour les SR.
Cordialement,

Yves MADEC

[cid:image001.png@01D2BCDE.F621D660]



Directeur Grands Comptes

Tél: 06 30 56 53 90

Fax : 04 72 13 90 27

Email : yves.madec@force-reseau.com NOUVEAU !


Adresse : 20 Bd Eugène Deruelle - Le Britannia – Bât C –  69432 LYON Cedex 03

[cid:image002.png@01D2BCDE.F621D660]

www.force-reseau.com<http://www.force-reseau.com/> – Découvrez vite notre nouveau site !



De : AlainPierreSDPV [mailto:notifications@github.com]
Envoyé : vendredi 21 avril 2017 17:09
À : groupe-gac/FleetOne
Cc : Yves Madec; Mention
Objet : Re: [groupe-gac/FleetOne] Création d'un Catalogue d'opérations spécifiques pour Intermarché (#148)


Assigned #148<https://github.com/groupe-gac/FleetOne/issues/148> to @YvesMadec<https://github.com/YvesMadec>.

**Comment by AlainPierreSDPV** [comment]
[Ventilation opérations par organe SR ITM 21.02.2017.xlsx](https://github.com/groupe-gac/FleetOne/files/952052/Ventilation.operations.par.organe.SR.ITM.21.02.2017.xlsx)

**Comment by AlainPierreSDPV** [comment]
@Portekoi  Damien peux tu me sortir sous excel la table organe actuelle ?

**Comment by Portekoi** [comment]
Voir ci-joint.
[Fleet-Organ-20170424D-1.xlsx](https://github.com/groupe-gac/FleetOne/files/952294/Fleet-Organ-
20170424D-1.xlsx)

**Comment by AlainPierreSDPV** [comment]
Merci Damien,

Peux  t on envisager d'avoir une table Organe spécifique pour ce client Intermarché ?
je crains que si j’implémente la table existante par la table de Yves le menu déroulant par défaut soit trop compliqué

**Comment by Portekoi** [comment]
De ce que j'ai pu constater, cette notion d'attribution d'une arborescence d'organes à un client avait été créée puis mise en commentaire ensuite.  Mais je peux me tromper, ne maîtrisant pas encore Fleet.
@MamboJoel pourra nous en dire plus à son retour.

**Comment by PIEGAY** [comment]
@MamboJoel : Est-il possible d'avoir une récursivité de cette table > à 2 niveaux
Cf : Ventilation opérations par organe SR ITM 21.02.2017.xlsx 

Merci

**Comment by AlainPierreSDPV** [comment]
@MamboJoel : Je viens de mettre à jour la table Fleet-Organ en incluant les Organes mentionnés par Yves dans le fichier "Ventilation.operations.par.organe.SR.ITM.21.02.2017" 
C
[New_Fleet-Organ-20170424D-1.xlsx](https://github.com/groupe-gac/FleetOne/files/1013506/New_Fleet-Organ-20170424D-1.xlsx)
ette table à maintenant 3 niveau avec la rubrique Hayon 
cette table est paramétrable au client . actuellement si l'on décoche un groupe  exemple "équipements" Id=7
les enfants du groupe apparaissent quand même. Il faut les décocher un à un pour qu'il n'apparaissent plus
serait il possible lorsque l'on décoche un groupe cela décoche automatiquement les enfants?

Pour ne pas gêner les gestionnaires de parc il serait souhaitable que les nouvelles rubriques à partir de l'Id 86  soient décochées par défaut

**Comment by MamboJoel** [comment]
- Le fichier joint est une réplique de la table `Organ` avec, à partir de l'ID 86, les nouveaux organes à insérer.
- Vérifier la récursivité coté UI et serveur car cette table a plus de 2 niveaux.

**Comment by MamboJoel** [comment]
C'est ok Alain ! Tu peux vérifier et clore.

**Comment by PIEGAY** [comment]
L'arborescence est bien apparu. 
En revanche elle est présente chez tous les clients. 

Est-ce que nous pouvons mettre le paramétrage d'origine suivant : 
- Client ITM LAI et ses enfants = uniquement arborescence SR (arborescence d'origine décochée)
- Autres clients = uniquement l'arborescence d'origine (arborescence SR décoché)

Merci

**Comment by AlainPierreSDPV** [comment]
[id clients ITM.xlsx](https://github.com/groupe-gac/FleetOne/files/1106237/id.clients.ITM.xlsx)
[arborescence SR.docx](https://github.com/groupe-gac/FleetOne/files/1106239/arborescence.SR.docx)

Ci-joint les id des clients ITM qui doivent avoir une arborescence de la table organe comme paramétré dans le document word 

Tous les autres clients de Fleet doivent avoir par défaut ces nouvelles rubriques de décocher comme le demande cytil

**Comment by AlainPierreSDPV** [comment]
La table est présentée ordonnancée de A à Z sur tous les niveaux. Pour que les nouvelles rubriques liées aux organes Semi Remorque soient regroupées en bas de liste peut on mettre un tiret ou tout autre caractère sur les rubriques du premier niveau qui  ferait qu'elles seront regroupées ?
les rubriques concernées sont

- Carrosserie SR
- Châssis SR
- Electricité SR
- Equipements SR
- Freins SR

**Comment by MamboJoel** [comment]
J'ai implémenté la demande de @PIEGAY. Est-ce que cela annule la tienne @AlainPierreSDPV  ?

**Comment by AlainPierreSDPV** [comment]
Non si possible
C'est pour traiter le cas d'un client qui a des Véhicules moteur et des semi-remorques et qui souhaite avoir un reporting avec ce niveau de détail pour les semi remorques.
regrouper les organes spécifique Semi Remorque me semble plus ergonomique si ce n'est pas une galère à mettre en place

**Comment by MamboJoel** [comment]
Mais actuellement seuls les clients ITM voient les organes suffixé par "SR". Et comme ces clients ne voient aucun autre organes que ces derniers, ceux-ci sont donc regroupés de facto à leurs yeux.

**Comment by AlainPierreSDPV** [comment]
Oui, mais si par exemple le client PHM Groupe  qui a des semi remorques et des véhicules moteurs souhaite avoir un reporting pour les semi à l'identique de ITM.  Le gestionnaire aura besoin de la totalité de l'arborescence pour qualifier les opérations. C'est ce cas qui est l'objet de ma demande
