### ISSUE TITLE
Impossible de réactiver un véhiciule archivé

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#149]
utiliser le lien ci-dessous pour constater 
http://membre.force-reseau-gp.com/mj/#url=/Vehicle/Display/&CompanyID=c.2786&HasAlert=false&HasMandatoryAlert=false&MonthsForAlert=3&VehicleID=36279&AlertID=&VisitID=&IsStoped=false&HasIncomingVisit=false&IsHot=false&HasLicence=true&Licence=CZ-975-TY&ClientTab=Users&tab=Edit&VehicleTab=Equipment-66402&EquipmentID=66402&VehicleTS=1487929364792&Display=&MessageID=&MemberTab=Users&FromDate=01/01/2017&ToDate=31/12/2017&VisitReference=871689

Pour réactiver il suffit théoriquement de supprimer la date de fin de gestion et ce n'est pas possible

**Comment by Portekoi** [comment]
@AlainPierreSDPV Etait-ce possible avant ou est-ce une fonctionnalité manquante? Et quel est le comportement attendu? Une simple case à cocher "Réactiver ce véhicule" suffirait?

**Comment by AlainPierreSDPV** [comment]
Il me semble que c'était possible avant 
je préférerais garder la fonctionnalité

**Comment by Portekoi** [comment]
J'ai réactivé le véhicule concerné :
`update [Vehicle]  set IsArchive = 0, Dateout = null Where ID =36279`

mais une correction va devoir être apportée.

@MamboJoel Dans la table `Vehicle` est rattaché un Trigger qui force le champ `DateOut` si le véhicule a le champ `IsActive = 0`  et que `DateOut = null`
Du coup, quand on veut supprimer cette date, le trigger la remet car IsActive reste à 0. 
Je me suis dit que si je mets une `DateOut` au `31/12/2031`, `IsActive` allait passer à 1 mais cela ne fonctionne pas car `IsArchive` reste à `1` et je ne trouve nul part où ce champ est mis à jour.

Quand j'aurais cette info, je pourrais corriger cette anomalie.

**Comment by MamboJoel** [comment]
Il s'agissait de véhicule clôturé du temps de V1.
Je clos.
