### ISSUE TITLE
Refonte de la fiche fournisseur

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#15]
Message original d'Alain Pierre envoyé dans #11 

> Refonte de la fiche fournisseur
> Raison Sociale (nom)
> ID FleetOne 
> APE 
> SIRET
> 
> Activité
> 
> Référencement UGAP
> 
> Adresse 
> Code postal 
> Ville
> 
> Coordonées GPS 
> Contact ATELIER 
> Téléphone
> Prénom
> Nom
> Email
> Contact MAGASIN 
> Téléphone
> Prénom
> Nom
> Email
> Contact FACTURATION 
> Téléphone
> Prénom
> Nom
> Email
> 
> Référencement UGAP c’est un menu déroulant qui a pour valeur
> Référencé UGAP
> Non référencé UGAP
> En cours de référencement UGAP

**Comment by AlainPierreSDPV** [comment]
les fournisseurs masqués ne le sont pas exemple SOCREC id 2428

**Comment by MamboJoel** [comment]
Doublon https://github.com/groupe-gac/FleetOne/issues/163
