### ISSUE TITLE
Aide à la mise a jour du reporting pour le groupe DOURS

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#150]
Les profils ont été mis à jour jusqu’à aujourd'hui via fleet V1 et l'on constate que dans Fleet V2 les informations n'ont pas été mises à jour
Pour corriger il faut re-sauvegarder la visite dans Fleet V2 pour la mise à jour.

il faudrait faire une routine pour passer dans toutes les visites du groupe DOURS qui sont en statut réalisée pour les re-sauvegarder .

Pour constater l'anomalie se loguer comme le client STEF ORLEANS
prendre le login: 4455
mot de passe ABC
Le reporting montre que c'est OK sauf pour 2.56 % du parc et quand tu clic sur "reglementaire" c'est l'inverse quasiment toutes les opérations réglementaires sont perimées
tu ne dois prbablement pas taper dans les mêmes tables

**Comment by Portekoi** [comment]
@AlainPierreSDPV De mémoire, et suite à la création de la gestion des profils sur V2 en novembre dernier, l'accès à V1 aurait dû être coupé. Je ne comprends pas pourquoi ce dernier a perduré.

Pour preuve : la routine qui synchronisait V1 vers V2 a bien été désactivée... Je vais voir ce que je peux faire.

**Comment by AlainPierreSDPV** [comment]
@Portekoi merci pour ta réponse , ils attendent cette mise à jour avant de poursuivre la gestion de parc avec Fleet V2

**Comment by Portekoi** [comment]
@AlainPierreSDPV Je ne sais pas comment faire car pour moi, il y a un problème sous-jacent : D'après cette issue https://github.com/groupe-gac/FleetOne/issues/73, @MamboJoel avait coupé la saisie des profils V1
Hors de ce que je comprends, le groupe DOURS a continué de les saisir sur V1. Est ce la cas?

Donc, comment ces profils ont ils pu être mis à jour sur V1? Je pense que quelque chose m'échappe. 

De plus, je ne sais pas comment retrouver les visites qu'il faut re-sauvegarder. Je vais voir avec @MamboJoel à son retour car je risque de faire une bêtise pour le moment.

**Comment by AlainPierreSDPV** [comment]
il n'ont pas touché au paramétrage des profils, mais ils ont mis à jour les profils affectés aux véhicules en passant les visites au statut "réalisées"  avec Fleet V1.

**Comment by Portekoi** [comment]
Je suis parti du reporting :
![image](https://cloud.githubusercontent.com/assets/1560754/25521936/b759d0c6-2c01-11e7-9605-7a9b1f05c7be.png)


SI je prends le premier véhicule `DA-101-FV` : la dernière visite est au 24/01/2017 dans Fleet 2

Si je vais dans Fleet 1:
http://www.gestionparc.com/ParkManagement/VehicleAlert.aspx?VehicleID=36425

J'obtiens la même date. Pourtant,  ce véhicule est en erreur dans le reporting mais je ne vois pas la différence entre v1 et v2

**Comment by AlainPierreSDPV** [comment]
La date de la prochaine alerte pour le contrôle chronotachygraphe est bien au 25/11/2017 dans V1
![image](https://cloud.githubusercontent.com/assets/22592053/25523981/fbdcfc76-2c08-11e7-87fb-dc533dc2c9b6.png)

**Comment by AlainPierreSDPV** [comment]
Si dans V2 je sauvegarde la visite 729322 la date de la prochaine alerte sera alors identique à V1

**Comment by Portekoi** [comment]
OK j'ai compris. Je vais voir les tables concernées.

**Comment by Portekoi** [comment]
J'ai fait un 
```
var v = Vehicle.GetVehicle(36425);
v.ForceAlertComputing();
```

Mais rien à faire, cela reste à 2015. J'ai aussi regardé dans le `NightRoutine` mais sans succès. Je vais voir avec @MamboJoel ce que j'ai manqué ou mal compris.

**Comment by MamboJoel** [comment]
Le problème est donc dans le calcul des alertes ?

Si oui il faut ces infos :
- le véhicule
- l'opération
- la date d'alerte attendue
- la date d'alerte constatée

Et je regarde dimanche.

**Comment by AlainPierreSDPV** [comment]
Toutes les informations sont dans cette issue
id vehicule  36425
opération id = 221
date d'alerte attendue 25/11/2017
date d'alerte constatée dans V2    26/11/2015 mais pas dans V1 cf description du début de l'issue

**Comment by MamboJoel** [comment]
Merci @AlainPierreSDPV 

@Portekoi j'ai exécuté moi aussi :

``` C#
var v = Vehicle.GetVehicle(36425);
v.ForceAlertComputing();
```

Et j'obtiens bien une alerte en novembre 2017. Je ne reproduis donc pas l'anomalie telle que tu l'as exposée. Et ça correspondrait à ce qu'Alain remonte : en sauvegardant la visite (ce qui relance le calcul des alertes) tout revient dans l'ordre. Il y a sûrement quelque chose qui m'a échappé alors, des données qui ont changé entre ton message du 28 et aujourd'hui.

J'ai donc écrit une requête appropriée pour traiter les véhicules de Dours et lancé `Waybis.SDPV.Fleet.Helper.RecomputeVehicles()`. Tu peux récupérer [ce dernier commit](https://github.com/ntlm-technologies/sdpv-fleet2/commit/3936cd2d36e0c463d32b2d9428b43cd5c95f99d3).

@AlainPierreSDPV  : 
- Est-ce que t'es satisfait du résultat ? (Le lot sera exécuté entièrement d'ici une heure.) 
- Le problème relève donc d'un usage de F1 ?

**Comment by AlainPierreSDPV** [comment]
Merci d'avoir regarder cela dés ton retour.
Il y a encore des anomalies
exemple sur cette visite

http://membre.force-reseau-gp.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=c.2558&VisitProcess=10&VehicleID=48412&AlertID=&VisitID=789178&FromDate=01/01/2017&ToDate=31/12/2017&Display=&AlertFromDate=01/01/2017&AlertToDate=27/05/2017&MemberTab=InvoiceList&ClientTab=Budget&tab=Visits&MessageID=&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&IsStoped=false&HasIncomingVisit=false&IsHot=false&HasLicence=false&Licence=eb588&ArchiveMonth=01/04/2017+00%3A00%3A00&VehicleTab=Equipment-66527&EquipmentID=66527&VehicleTS=1493364706352&VVS_VehicleID=25146&VVS_OrganIDs=0&VVS_NatureIDs=0&VVS_Accounts=&VVS_VehicleType=AllEquipments&VVS_FromDate=25/03/2010&VVS_ToDate=30/03/2017&VVS_Tags=vidange_

la date attendue pour la prochaine alerte du contrôle du limiteur de vitesse est 05/07/2017 alors qu'elle est au 05/07/2016
Si je sauvegarde à nouveau cette visite je pense que l'alerte sera recalculée normalement

Autre anomalie 
dans le reporting du client STEF ORLEANS
Login : 4455
mot de passe: ABC
Constater que le réglementaire alerte dépassée pas de RDV est à 2.56%
cliquer sur l'onglet réglementaire et constater qu'il n'y a que 4 opérations qui sont OK

Oui Nicolas le Pb vient qu'ils ont travaillés jusqu'à ce jour avec Fleet V1 pour mettre à jour les plannings véhicules

**Comment by Portekoi** [comment]
Effectivement, si je prends l'opération `Contrôle annuel du limiteur de vitesse`, le code retourne la date au 05/07/2016 : 
![image](https://cloud.githubusercontent.com/assets/1560754/25578673/56a90248-2e71-11e7-8d78-d117d2f7fe2f.png)

Cela viendrait du fait qu'il y a une `MandatoryDate`. J'essaie de voir d'où elle vient et si c'est "normal"

**Comment by Portekoi** [comment]
Cela ressemble à cette issue j'ai l'impression : des données erronées : 
https://github.com/groupe-gac/FleetOne/issues/116
Je regarde.

**Comment by Portekoi** [comment]
Je pense que l'on est dans le même cas pour les deux opérations (`IsInit = 0` dans `Order`) qui ont une date erronée mais je n'arrive pas à corriger. Et le problème doit se poser pour tous ceux qui utilisent V1

**Comment by MamboJoel** [comment]
@Portekoi, le problème se situe plus bas :
![image](https://cloud.githubusercontent.com/assets/3832009/25580322/67098932-2e80-11e7-9978-fbc3ee030405.png)
`LastIntervention.IsMandatoryOK = false` et donc on n'ajoute pas la fréquence de 12 mois à la date de la dernière visite.

SI l'on va sur [la visite du 5 juillet 2016](http://membre.force-reseau-gp.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=c.2558&VisitProcess=10&VehicleID=48412&AlertID=&VisitID=789178&FromDate=01/01/2017&ToDate=31/12/2017&Display=&AlertFromDate=01/01/2017&AlertToDate=27/05/2017&MemberTab=InvoiceList&ClientTab=Budget&tab=Visits&MessageID=&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&IsStoped=false&HasIncomingVisit=false&IsHot=false&HasLicence=false&Licence=eb588&ArchiveMonth=01/04/2017+00%3A00%3A00&VehicleTab=Equipment-66527&EquipmentID=66527&VehicleTS=1493364706352&VVS_VehicleID=25146&VVS_OrganIDs=0&VVS_NatureIDs=0&VVS_Accounts=&VVS_VehicleType=AllEquipments&VVS_FromDate=25/03/2010&VVS_ToDate=30/03/2017&VVS_Tags=vidange) on voit pourtant "A" pour résultat de visite réglementaire :

![image](https://cloud.githubusercontent.com/assets/3832009/25580481/9aa5dd6c-2e81-11e7-859d-7471acf2d2b0.png)

Mais cette valeur est affichée par méprise, uniquement car c'est la première valeur de la liste. Car dans la base de données la valeur est bien nulle :

![image](https://cloud.githubusercontent.com/assets/3832009/25580500/c81457ec-2e81-11e7-8ebe-5ca0916c086a.png)

@AlainPierreSDPV, quand tu parlais de sauvegarder la visite, je pensais que tu désignais la visite actuelle et non la visite précédente. C'est la raison pour laquelle j'ai écrit la routine qui recalculait tous les véhicules. Mais pour résoudre le problème en réalité c'est bien la visite précédente qu'il faut sauvegarder, cela passe VTResult = "A" et alors, lors du recalcul des alertes, le test réussit et le programme ajoute 12 mois comme attendu.

Ce problème a été rencontré dans l'issue #39 sur la même opération d'ailleurs (Contrôle annuel du limiteur de vitesse), car dernièrement, avec @PIEGAY, on a changé le traitement du réglementaire non CT, le fondant sur le résultat de la visite. Ce n'était pas le cas avant.

**Résolution**

- J'ai sauvegardé un dump de `OrderDetail` dans `tmp_OrderDetail_20170501`.
- J'ai passé toutes les interventions réalisées, réglementaires et sans résultat, à "A". 41495 ligne(s) affectée(s) depuis 2006.
- @Portekoi pour ce faire j'ai écrit et exécuté la procédure stockée : `UpdateNullVTResultID`.
- Je relance en ce moment la routine de calcul des alertes sur les 1014 véhicules Dours. 
- @AlainPierreSDPV tu peux constater le résultat d'ici une heure, et clore le cas échéant.

En définitive le problème vient du changement de logique métier pour les réglementaires non CT évoquée dans l'issue #39.

**Comment by AlainPierreSDPV** [comment]
Merci pour ces explications 
Je viens de contrôler quelques véhicules et cela me semble correct. j'ai demandé au gestionnaire de parc de bien vouloir contrôler l'ensemble de ses clients actifs

Il doit me donner la liste des clients qui sont actifs et actuellement rattachées au niveau "groupe Dours" pour les muter sur le membre "Loiret Trucks"
demain je regarde le reporting pour voir si tout est conforme puis je clos cette issue si c'est le cas.

**Comment by Portekoi** [comment]
Des nouvelles?
