### ISSUE TITLE
equipement secondaire non visibles dans la visite

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#151]
C'est probablement lié à la fonctionnalité qui existe  pour le moment dans Fleet V1 et pas encore dans Fleet V2 qui est de pouvoir déplacer un équipement secondaire d'un véhicule à un autre.

Pour reproduite prendre le véhicule EB-588-MG   Id = 51182
constater que ce véhicule est présenté avec un seul équipement principal 
Aller dans l'onglet "véhicule" constater qu'il y a un équipement secondaire nommé "5665 avec 3937' avec un profil "semi AFT Nord"

**Comment by Portekoi** [comment]
Dans la table `Alert`, l'équipement enfant `5665 avec 3937` (ID `66527`) appartient encore au véhicule `54409` 

J'ai donc effectué  :
```
Dim v = Vehicle.GetVehicle(51182)
        v.ForceAlertComputing()
```
Mais cela ne met pas à jour pas le `VehicleID` de la table `Alert`

Je vais creuser.

**Comment by Portekoi** [comment]
C'est corrigé. 

![image](https://cloud.githubusercontent.com/assets/1560754/26722607/f8ded55a-4790-11e7-98af-98115667c5ee.png)

**Comment by Portekoi** [comment]
Suppression des alertes pour l'équipement concerné puis `ForceAlertComputing` sur le Vehicule.
