### ISSUE TITLE
récuperer sous Excel les opérations réglementaires de la table "Opération"

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#152]
je cherche à récupérer sous Excel les opérations réglementaires qui sont dans la table opérations
sous la rubrique "Contrôles réglementaires" ID=57
il y 2 enfants dans cette famille 
 Opérations > Contrôles réglementaires (CRG) > Véhicules (VEH) 
 Opérations > Contrôles réglementaires (CRG) > Equipements et métiers (EQM)
   avec  8  enfants

**Comment by MamboJoel** [comment]
[Operations 57.xlsx](https://github.com/groupe-gac/FleetOne/files/1001457/Operations.57.xlsx)

**Comment by AlainPierreSDPV** [comment]
c 'est Ok merci
