### ISSUE TITLE
Pas de récupération mot de passe pour le SSO

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#153]
Il n'y a pas que pour mathieu Galy que le Pb se pose

![image](https://cloud.githubusercontent.com/assets/22592053/26093644/03db0fb4-3a17-11e7-98cd-59c3f9fca6e6.png)

**Comment by MamboJoel** [comment]
Je t'ai envoyé le nouveau mot de passe par email.

**Comment by AlainPierreSDPV** [comment]
Peux tu me donner par mail un nouveau mot de passe pour l'identifiant f.perry@groupeaustrasie.fr
il ne le récupère pas dans sa boite

**Comment by MamboJoel** [comment]
@meillere

**Comment by Portekoi** [comment]
@meillere quelle est la procédure dans ce cas? Cela concerne quelle table?
