### ISSUE TITLE
MAJ table de croisement Fleet / Rentcar pour Berthier

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#154]
Peux mettre à jour la table de croisement pour le membre  5402 GIC
cette table remplace les informations pour ce membre
[BERTHIER _RENTCAR.xls.xlsx](https://github.com/groupe-gac/FleetOne/files/1010444/BERTHIER._RENTCAR.xls.xlsx)

**Comment by AlainPierreSDPV** [comment]
@MamboJoel  peux tu faire cette mise à jour aujourd'hui ? cela me permettra de contrôler avant notre réunion avec le groupe Berthier du 1 er Juin à Lyon  que la transmission des alertes vers Rentcar est conforme

**Comment by MamboJoel** [comment]
Oui, je suis dessus.

**Comment by MamboJoel** [comment]
C'est bon !

**Comment by AlainPierreSDPV** [comment]
Je viens de contrôler sur un véhicule est j'ai les écarts suivants
utiliser le webservice avec l'immatriculation AT-743-ND
![image](https://cloud.githubusercontent.com/assets/22592053/26311121/6ff66ca2-3f03-11e7-9531-0c06be87e625.p
profil = 4703  "GI-Arret 60000 Km/DXI /Hayon/POMONA TA"  Les id des opérations  sont 
31 / 221 / 458 / 249 / 1222 / 1421 / 1425 / 358 / 355 / 348 / 356 / 680 /346/ 28 
équipement secondaire  profil = 3789  Les id des opérations  sont  42 / 673 / 43048

la table de croisement doit donner comme résultat  
 id 31   = CT/D                 date alerte = 15/03/2018
 id 680  = CT TACHY/D    date alerte = 18/05/2018
id  28    =  CT HAYON/D  date alerte = 23/08/2017
id 346 = E/S CHASSIS/K   date alerte = 11/09/2017
id = 42 E/S GROUPE / D   date d'alerte = 19/04/2017
id= 673  CT DSV / D         date d'alerte = 19/04/2019

le webservice donne:
CT DSV/D           19/04/2019 
E/S GROUPE/D    19/04/2017
CT HAYON/D       23/08/2017   
E/S CHASSIS / K    11/09/2017

peux tu regarder pourquoi 
d 31   = CT/D   d 680  = CT TACHY/D  sont à Null dans le résultat du webservice

**Comment by AlainPierreSDPV** [comment]
je viens de faire un test sur le véhicule AT-743-ND
![image](https://cloud.githubusercontent.com/assets/22592053/26312972/a7097b66-3f09-11e7-8baa-82f3d6698a28.png)

les opérations dans le profil id= 31  "contrôle technique PL"  et id = 680  "Contrôle contrôlographe numérique" sont à Null dans le web service

il devrait y avoir 
CT/D date d'alerte 15/03/2018 et CT YACHY/D date d'alerte 18/05/2018 
peux tu regarder

**Comment by MamboJoel** [comment]
(Mieux vaut ne pas publier ici de mots de passes. Et, le cas échéant de me passer les emails et autres en texte en plus de l'image pour que je puisse copier/coller)

**Comment by MamboJoel** [comment]
C'est corrigé.
