### ISSUE TITLE
Modification de la régle d'intégration des index Kilométriques pour les VI avec Ican 

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#155]
Actuellement
c'est le premier index du mois qui est sauvegardé dans la table et qui permet au profil de se mettre à jour.
pour permettre à Clovis d'obtenir le dernier index du mois via le reporting qui lui sert pour sa facturation il faut modifier cette règle en récupérant le dernier index du mois.
pour cela il faut integrer tous les index dans la table et la requête  prendra le Max du mois

**Comment by MamboJoel** [comment]
Merci !
