### ISSUE TITLE
Modification de l'arborescence groupe Berthier

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#157]
En pièce jointe la situation actuelle pour le groupe Berthier et la situation future demandée
[MODIF2 ARBORESCENCE BERTHIER.xlsx](https://github.com/groupe-gac/FleetOne/files/1022769/MODIF2.ARBORESCENCE.BERTHIER.xlsx)

**Comment by Portekoi** [comment]
Je ne retrouve pas les mêmes parentID actuels. Je pense que Excel a incrémenté le compteur mais je préfère être sur :

![image](https://cloud.githubusercontent.com/assets/1560754/26521454/fe162fd4-42e8-11e7-84a3-80a4bf7ea30f.png)

**Comment by AlainPierreSDPV** [comment]
Oui c'est évident .... 1545 = groupe berthier et rien d'autre
désolé de ne pas avoir controlé

**Comment by Portekoi** [comment]
Désolé mais j'ai deux fois le membre ID `16321` :
`16321 ==> Plateforme Gestion de Flotte`
`16321 ==> Plateforme Gestion de Parc`

Avec 2 ParentID différents. Pouvez-vous revoir le fichier? Je dois renommer le `16321`?

**Comment by AlainPierreSDPV** [comment]
Je corrige mes erreurs .....       16321 = Gestion de Flotte et non de parc
et j'ai modifier aussi le rattachement de GIC qui a comme parent  GROUPE BERTHIER = Id 1545
[MODIF ARBORESCENCE BERTHIER corrigée.xlsx](https://github.com/groupe-gac/FleetOne/files/1035375/MODIF.ARBORESCENCE.BERTHIER.corrigee.xlsx)

**Comment by Portekoi** [comment]
@AlainPierreSDPV  : Cela devrait être bon.

**Comment by AlainPierreSDPV** [comment]
C'est conforme

**Comment by AlainPierreSDPV** [comment]
Suite à une réunion avec Berthier il y a un nouveau membre de créer enfant de GIC
LOCATION PLUS  IDMember = 16354
il faut rattacher le Client qui porte le même nom "Location Plus" CompagnyID=14358 à ce nouveau membre
Ce client a 2 enfants  Location plus (courte durée) ID =14361 et Location plus (longue durée)  ID = 15400

**Comment by Portekoi** [comment]
Le client et ses 2 enfants ont été rattachés au membre 16354. Pouvez-vous vérifier?

**Comment by AlainPierreSDPV** [comment]
C'est correct.
Mais quand je vais sur l'onglet  administration du membre "Location plus" le client "location plus" n'apparait pas . cela n'a pas d'incidence sur le fonctionnement des alertes
