### ISSUE TITLE
Modification de l'arorescence groupe DOURS

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#158]
En pièce jointe les modifications à apporter
[modif arborescence groupe DOURS.xlsx](https://github.com/groupe-gac/FleetOne/files/1025966/modif.arborescence.groupe.DOURS.xlsx)

**Comment by Portekoi** [comment]
C'est fait. Pouvez-vous vérifier lundi? Merci.

**Comment by AlainPierreSDPV** [comment]
Je viens de vérifier c'est Ok merci
