### ISSUE TITLE
Marquage des week end dans le planning des alertes des visites décalés 

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#162]
Prendre n'importe quel véhicule. Affichez la visite et constater que le premier week end de Juin est le Dimanche 04 et le Lundi 06 Juin

**Comment by Portekoi** [comment]
Dans le planning à droite, c'est bien ça? 
![image](https://user-images.githubusercontent.com/1560754/26836999-98b069a6-4adc-11e7-95e6-4e95ae107c68.png)

**Comment by AlainPierreSDPV** [comment]
Oui

Envoyé de mon iPhone

Le 6 juin 2017 à 17:21, "Portekoi" <notifications@github.com<mailto:notifications@github.com>> a écrit :


Dans le planning à droite, c'est bien ça?
[image]<https://user-images.githubusercontent.com/1560754/26836999-98b069a6-4adc-11e7-95e6-4e95ae107c68.png>

**Comment by Portekoi** [comment]
C'est corrigé.
