### ISSUE TITLE
URGENT - Intégration parc INTERMARCHE avec équipement hayon

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#164]
Nous souhaitons pouvoir initialiser les équipements secondaires en automatique pour les semi-remorques ITM qui ont un hayon.

Le process suivant peut-il convenir : 
- Etape 1 importation des équipements principaux 
- Etape 2 récupération de fleet des id des véhicules et des id des équipements principaux 
- Etape 3 constitution d’un fichier Excel qui reprend ces id et qui donne toutes les informations nécessaire à la création des équipements secondaires.

Est-ce jouable pour toi ?

**Comment by MamboJoel** [comment]
Carrément.
Il me faut un fichier xls les colonnes suivantes :
- ID du véhicule créés sur Fleet.
- Colonnes relatives au hayon.

On écrira une routine qu'on pourra réutiliser à l'avenir.

**Comment by MamboJoel** [comment]
@Portekoi demain matin Cyril va nous fournir un fichier xls selon les spécifications que j'ai établies dans le message précédent. C'est un besoin urgent, mais je suis en congé jusqu'à mardi. Je peux travailler dessus avant midi demain. Est-ce que tu peux effectuer l'intégration ? 
Il y a deux possibilités :
- Par programmation, en bouclant sur les lignes du xls, initialisant un nouveau véhicule (s'il n'existe pas déjà), puis lui ajoutant un équipement (s'il n'existe pas déjà).
- Par sql.
Dans les deux cas, pour chacun des véhicules, il faut ensuite appeler `Vehicle.ForceAlertComputing()` , qui assurera le calcul du planning.
A ta dispo pour traiter ça demain par téléphone. Ou samedi selon ton planning.

**Comment by Portekoi** [comment]
Plutôt j'aurais le fichier et mieux cela sera pour que je puisse commencer à repérer les éléments dont je vais avoir besoin

**Comment by MamboJoel** [comment]
Il devrait arriver avant 10h demain.

**Comment by PIEGAY** [comment]
Les véhicules ont été intégrés par la procédure habituel. 
Est-ce que vous pouvez lancer la "moulinette 3A" sur l'ensemble des véhicules sous les bases ITM LAI : 
[ID BASE ITMLAI.xlsx](https://github.com/groupe-gac/FleetOne/files/1097098/ID.BASE.ITMLAI.xlsx)

![image](https://user-images.githubusercontent.com/22617815/27471613-a004f8f6-57f8-11e7-9c2b-c0c4041d4b68.png)

Ci-joint le fichier pour la création des équipements : 
[Intégration équipememnt ITM LAI.xlsx](https://github.com/groupe-gac/FleetOne/files/1097091/Integration.equipememnt.ITM.LAI.xlsx)

![image](https://user-images.githubusercontent.com/22617815/27471659-c9a27ce2-57f8-11e7-9a5b-a8fabe4a2b05.png)

**Comment by Portekoi** [comment]
OK je retrouve 959 véhicules. Je regarde pour créer les hayons.

**Comment by Portekoi** [comment]
Je confirme que aucun n'a de hayon. Je vais créer la routine

**Comment by Portekoi** [comment]
Je voulais saisir le premier manuellement mais je ne trouve pas la catégorie de profil 'ITM LAI' : 
![image](https://user-images.githubusercontent.com/1560754/27474463-9f23d790-5802-11e7-85fe-cb004057854b.png)

Pas grave, je vais faire autrement.

**Comment by PIEGAY** [comment]
Ils ont été créés ce matin. 
Il faut peut être faire une mise à jour de la liste déroulante : 

![image](https://user-images.githubusercontent.com/22617815/27474705-06a553e4-5803-11e7-80c8-ba1b11adf907.png)

**Comment by MamboJoel** [comment]
Pour info Damien, la procédure AAA est `Vehicle.MatchTo3AVehicle()`.

**Comment by Portekoi** [comment]
Ah ok je la cherchais. Merci :)

J'ai sauvegardé la table `equipment` ==> `Equipment_20170623D`

**Comment by Portekoi** [comment]
La reprise pour les équipements est ok. Je regarde pour le AAA
J’exécuterai tout demain matin pour pas gêner le serveur.

**Comment by PIEGAY** [comment]
Les hayons ne sont pas en ligne.
Est-ce qu'ils apparaîtront demain matin ?

Merci

**Comment by Portekoi** [comment]
C'est pour les AAA. Des soucis de connexion. Donc je lance tout demain matin quand le serveur sera au calme.

**Comment by Portekoi** [comment]
Je viens de voir le message de @PIEGAY : Oui, je lance tout demain matin.

Mes véhicules de test sont : `AP044FS` et `AP909FR`

Ceux là sont bons normalement.

**Comment by Portekoi** [comment]
Les hayons sont bien présent. Je lance la seconde partie de la routine.

**Comment by Portekoi** [comment]
J'en suis à 200 véhicules traités. Je les traite 100 par 100.

**Comment by Portekoi** [comment]
On a fait la moitié. Si je prends un exemple, la requête AAA a bien fonctionné : 

![image](https://user-images.githubusercontent.com/1560754/27507714-ef5ca110-58d4-11e7-8991-53e6ca526e35.png)

**Comment by Portekoi** [comment]
Traitement terminé. Dernier véhicule traité : AP-355-GY :

![image](https://user-images.githubusercontent.com/1560754/27508148-896c60c4-58df-11e7-8538-ca68a8dc0cf4.png)

**Comment by AlainPierreSDPV** [comment]
Merci Damien
Je laisse cyril clôturer cette issue
Si tout est conforme pour lui

Envoyé de mon iPhone

Le 24 juin 2017 à 13:18, "Portekoi" <notifications@github.com<mailto:notifications@github.com>> a écrit :


Traitement terminé. Dernier véhicule traité : AP-355-GY :

[image]<https://user-images.githubusercontent.com/1560754/27508148-896c60c4-58df-11e7-8538-ca68a8dc0cf4.png>

**Comment by PIEGAY** [comment]
C'est bon les hayons sont bien chargés + le AAA.
Merci Damien

Je ne clôture pas l'issue car je vais avoir quelques compléments d'infos à intégrer comme l'historique dans la semaine

**Comment by PIEGAY** [comment]
@Portekoi / @MamboJoel : tu trouveras ci-dessous quelques intégrations à réaliser lundi dans la mesure du possible.

**INTEGRATION DE L'HISTORIQUE DE LA REMORQUE - EQUIPEMENT PRINCIPAL**

Ci-joint le fichier : import historique remorque - equipement principal
[import historique remorque - equipement principal.xlsx](https://github.com/groupe-gac/FleetOne/files/1118013/import.historique.remorque.-.equipement.principal.xlsx)

Mise à jour des données ci-dessous (en écrasant les données existantes) : 

![image](https://user-images.githubusercontent.com/22617815/27772822-12ec13fe-5f6a-11e7-81ab-0b5bac106e97.png)

**INTEGRATION DE L'HISTORIQUE DU HAYON - EQUIPEMENT SECONDAIRE**

Ci-joint le fichier : import historique hayon
[import historique hayon.xlsx](https://github.com/groupe-gac/FleetOne/files/1118015/import.historique.hayon.xlsx)

Mise à jour des données ci-dessous (en écrasant les données existantes) : 
![image](https://user-images.githubusercontent.com/22617815/27772833-5ddb4ed4-5f6a-11e7-91ac-49cf633f13d1.png)

**MISE A JOUR DE LA FICHE VEHICULE**
Ci-joint le fichier : import fiche véhicule
[import fiche véhicule.xlsx](https://github.com/groupe-gac/FleetOne/files/1118017/import.fiche.vehicule.xlsx)

Mise à jour des données ci-dessous (en écrasant les données existantes) : 
![image](https://user-images.githubusercontent.com/22617815/27772853-bb976224-5f6a-11e7-8938-94e1623ecc7a.png)

**MISE A JOUR DE LA FICHE EQUIPEMENT PRINCIPAL - REMORQUE**
Ci-joint le fichier : import fiche remorque
[import fiche remorque.xlsx](https://github.com/groupe-gac/FleetOne/files/1118020/import.fiche.remorque.xlsx)

Mise à jour des données ci-dessous (en écrasant les données existantes) : 
![image](https://user-images.githubusercontent.com/22617815/27772866-0c2e5422-5f6b-11e7-9ae2-f5ac10a31916.png)

MERCI D'AVANCE !!

**Comment by MamboJoel** [comment]
C'est bon !

**Comment by PIEGAY** [comment]
@MamboJoel : Je n'ai rien dans FleetOne / Les données n'ont pas été intégrées. 
Est-ce que les modifications ont été publiées ?

**Comment by PIEGAY** [comment]
**INTÉGRATION DE L'HISTORIQUE DE LA REMORQUE - EQUIPEMENT PRINCIPAL**

Les dates ont été importées mais dans le profil les anciennes dates n'ont pas été écrasées : 

![image](https://user-images.githubusercontent.com/22617815/27854677-025ead4e-6168-11e7-92d1-744c5099c98b.png)

Peux tu les supprimer car on va faire des bétises ? 

**MISE A JOUR DE LA FICHE VÉHICULE**

![image](https://user-images.githubusercontent.com/22617815/27854748-344bb478-6168-11e7-8f84-9c8fa174471a.png)

La date d'entrée en gestion + le fournisseur par défaut n'ont pas été intégrés depuis le fichier  import fiche véhicule.xlsx 

**MISE A JOUR DE LA FICHE EQUIPEMENT PRINCIPAL - REMORQUE**

Le type n'a pas été mis à jour depuis le fichier : import fiche remorque.xlsx

![image](https://user-images.githubusercontent.com/22617815/27854820-7743e200-6168-11e7-8705-3e80d56f13ff.png)

Merci !!

**Comment by MamboJoel** [comment]
C'est OK Cyril !

**Comment by PIEGAY** [comment]
Parfait.
Tout me parait OK
