### ISSUE TITLE
Aide pour Berthier : fichier 3A Marchizet et Vandelle

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#165]
Berthier souhaite récurer via 3A  la Marque, le type _vin_cg , le modele,le PTR? la date_1ER_CIR des véhicules qui sont dans les onglets "Marchizet" et "vandelle" du fichier Excel ci-joint.

Peux tu faire une routine qui recherche sur l'immat et si la réponse est "Véhicule non trouvé dans la base des immatriculations" , essayer alors par le VIN ? et si la réponse est positive de récupérer la bonne immatriculation
[marchizet_vandelle.xlsx](https://github.com/groupe-gac/FleetOne/files/1091674/marchizet_vandelle.xlsx)

**Comment by MamboJoel** [comment]
Nous avons une **procédure 3A** qui interroge d'abord notre base, et si rien n'y est trouvé interroge le webservice 3A.
Qu'entends-tu par "récupérer" ces données ?
- Interroger notre **procédure 3A** et vous renvoyer un fichier Excel avec les champs attendus ?
- Interroger notre **procédure 3A** et documenter les véhicules Fleet correspondants ?

**Comment by AlainPierreSDPV** [comment]
Interroger notre procédure 3A et renvoyer un fichier Excel avec les champs attendus.

ces véhicules seront peut être dans fleet aprés mais actuellement ce n'est pas la demande

**Comment by Portekoi** [comment]
Si je regarde dans notre fichier de consultation 3A, sans passer par le web service, je trouve 526 véhicules sur les 2443 de "Vandelle". Est ce que je lance la consultation 3A pour les autres? Je crois savoir que ce service est payant. A vous de me dire.

**Comment by AlainPierreSDPV** [comment]
oui c'est payant de l'ordre de 8 ç la consultation mais je suis d'accord pour le faire

**Comment by Portekoi** [comment]
OK je regarde ça

**Comment by Portekoi** [comment]
La procédure 3A appelle le WS `GERAUSIV` mais ce dernier, que cela soit par l'immatriculation ou le VIN, me renvoi souvent : 

`<ERR><NUMERR>34</NUMERR><LIBERR>Immatriculation inconnue</LIBERR></ERR>`

Exemple : plaque : 

* 4463 VA 88 / WJMENPT10C141104
* 1475 SF 39 / ZFA24400007134605 

Est-ce normal?

**Comment by Portekoi** [comment]
A l'inverse, un exemple pour lequel cela a fonctionné : 

`1755SN39 / VSESJS04VNA204282`

**Comment by AlainPierreSDPV** [comment]
je constate comme toi que c'est véhicules sont inconnus du CIV sans que je puisse déterminer pourquoi
pour le 1755SN39 j'ai également l'information "Immatriculation inconnue" quand j'interroge par Fleet Reception

**Comment by Portekoi** [comment]
Oui effectivement pour le 1755SN39 , je n'avais pas vu mais c'était bien ce message...

**Comment by Portekoi** [comment]
Ci-joint un fichier pour `Vandelle`. Dites moi si cela convient malgré les informations manquantes et je m'occuperai du second.

[FL-BERTHIER-3A-20170711D-1.xlsx](https://github.com/groupe-gac/FleetOne/files/1139539/FL-BERTHIER-3A-20170711D-1.xlsx)

**Comment by AlainPierreSDPV** [comment]
cela convient tu peux lancer le second fichier

**Comment by Portekoi** [comment]
Là encore, j'ai beaucoup de VIN inconnus : 
* VF1FH30GG13929008
* VKIST39MHPE708185
* VLURA4X2A09001185

A l'inverse, celui-ci est bien reconnu : 
* VF9SR3CA34Y160089

Il y a plus de 4 000 lignes à traiter. Je vous envoie le fichier dès que c'est terminé.

**Comment by Portekoi** [comment]
Voici le second fichier
[FL-BERTHIER-3A-Marchizet-20170711D-1.xlsx](https://github.com/groupe-gac/FleetOne/files/1144969/FL-BERTHIER-3A-Marchizet-20170711D-1.xlsx)
