### ISSUE TITLE
Modifier la fiche contact pour AUSTRASIE

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#166]
Pour le membre AUSTRASIE id=3735 et ses enfants  masquer sur la fiche contact le logo Force Reseau

![image](https://user-images.githubusercontent.com/22592053/27434105-c879f0b2-5757-11e7-8147-9c9499fe5e2f.png)

**Comment by AlainPierreSDPV** [comment]
-----

**Comment by MamboJoel** [comment]
C'est ok Alain !
