### ISSUE TITLE
Mettre en place le nouveau reporting client  "Planning maintenance"

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#167]
Actuellement  le lien qui est en place coté reporting client pour obtenir le Planning maintenance
est     http://rep.gestionparc.com/Full/Planning.aspx
Il faut lui substituer par le lien ci dessous qui a été validé par Yves et Cyril
http://rep.gestionparc.com/Full/Planning1.aspx

**Comment by MamboJoel** [comment]
Jacques le projet fleet-reporting ne compilait pas sur ta machine. J'ai dû remettre à jour les références qui pointaient vers `waybis/waybis-common`.
Je suspecte une autre arborescence sur ta machine au Portugal.

Désormais je compile, mais ViewState("UserID") est vide et sql serveur lève une erreur à l'exécution de [cette requête](https://github.com/ntlm-technologies/sdpv-fleet-reporting/blob/master/FleetReporting/Full/Planning.aspx.vb#L180).

T'as une idée ?
