### ISSUE TITLE
Liste des Véhicules avec Ican dans fleet

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#168]
J'ai besoin de la liste des véhicules avec Ican qui sont dans Fleet avec la date du premier Log

C'est peut être possible directement à partir des log Ican ? sinon à partir de Fleet les véhicules sont tagués dans information véhicule avec  le champ "suivi" qui a la valeur "ACTIA"

C'est pour contrôler la facturation Actia

**Comment by AlainPierreSDPV** [comment]
peux tu regarder cette demande cette semaine ?

**Comment by Portekoi** [comment]
[EQP-ICAN-issue-168-20170703D-1.xlsx](https://github.com/groupe-gac/FleetOne/files/1119285/EQP-ICAN-issue-168-20170703D-1.xlsx)

Je trouve 103 logs pour ACTIA mais pour certains, je ne retrouve pas le `VehicleID`

**Comment by AlainPierreSDPV** [comment]
Merci Damien 
Tous les véhicules ayant un Ican ne sont pas dans Fleet
