### ISSUE TITLE
ITM LAI - CHARGEMENT CATALOGUE D'OPERATIONS

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#169]
@MamboJoel / @Portekoi 

Est-ce que tu peux charger le catalogue d'opération ci-joint pour le contrat intermarché : 
[Catalogue d'opérations ITM LAI.xlsx](https://github.com/groupe-gac/FleetOne/files/1118097/Catalogue.d.operations.ITM.LAI.xlsx)

![image](https://user-images.githubusercontent.com/22617815/27773431-b24d8824-5f79-11e7-90a2-b9094a178ffc.png)

Merci

**Comment by MamboJoel** [comment]
@PIEGAY : La ligne téléphonique a coupé. On s'occupe de ça en fin de journée.

**Comment by PIEGAY** [comment]
@MamboJoel - Merci il y a également la fin du message #164

**Comment by MamboJoel** [comment]
Oui je l'ai bien en tête.

**Comment by MamboJoel** [comment]
C'est bon !

**Comment by PIEGAY** [comment]
Parfait 
C'est bon pour mois
