### ISSUE TITLE
Integration des logs Ican PL dans Fleet

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#17]
Il y aura des évolutions à prévoir en fonction des demandes clients et des améliorations des diags capables d'être réalisés par les Ican.
ci dessous une amélioration qu'il nous faut capter à partir des Ican PL . Il n'y a qu'un seul véhicule équipé
le VIN est VF611J161ED000091

info donnée par Actia :

> Je vous confirme que nous remontons bien les heures moteur et le régime, et que ces données sont poussées vers FleetOne.
> Pour les régimes: nous utilisons les mêmes champs que pour les VU. Bizarre que ça ne fonctionne pas.
> Pour les heures: elles sont dans l'ID 14. Mais attention: pour l'instant nous remontons directement le temps moteur. Pour des raisons d'homogénéisation avec d'autres boitiers Actia (TGU1A), nous allons devoir convertir la donnée au format hexadecimal. Donc si Nicolas procède à l'intégration maintenant, ça va bien et facilement marcher, mais d'ici 1 mois ça va planter quand nous changerons le format. Exemple: il recevra 14 = A1 au lieu de 14 = 17 heures…

**Comment by MamboJoel** [comment]
Plusieurs questions :

- Ils vont changer le format des données qu'ils nous envoient ?
- Quand ?
- Pour l'instant seul un véhicule (VF611J161ED000091) observe le nouveau format ?
- Quelles sont les changements de format ?
- Y a-t-il une nouvelle documentation ?

**Comment by AlainPierreSDPV** [comment]
voir le mail d'ici 1 mois uniquement pour le temps d utilisation du moteur valable uniquement pour l'Ican Pl 
oui il n'y a pour le moment que le VF611J161ED000091 qui est équipé d'un Ican PL
Pour le changement de format de la donnée heure moteur lire le mail
en pièce jointe la doc sur le s Ican PL
[Data sample ICAN Truck.zip](https://github.com/groupe-gac/FleetOne/files/544785/Data.sample.ICAN.Truck.zip)
