### ISSUE TITLE
ITM LAI - Ajout d'une catégorie dans la table des organes SR

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#171]
@MamboJoel : Merci d'ajouter la catégorie "Béquilles" sous la catégorie "Châssis SR" dans la table des organes. 

![image](https://user-images.githubusercontent.com/22617815/27872184-35b25b88-61a8-11e7-9e41-79a7d7c8ee15.png)

Merci

**Comment by MamboJoel** [comment]
C'est bon. C'était un peu fastidieux d'ajouter un organ a posteriori. Alors je laisse cette issue ouverte avec [cette note technique](https://github.com/ntlm-technologies/sdpv-fleet-mvc/issues/13). Quand tu veux ajouter un organ tu peux repasser par cette issue et ça ira beaucoup plus vite.

**Comment by PIEGAY** [comment]
Parfait 
C'est OK
