### ISSUE TITLE
pas de log pour l'Ican 1239 immat EN-713-GL

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#174]
Actia me précise que les logs sont bien transmis à Fleet pour cet Ican 
véhicule immatriculé EN-713-GL 
Ces logs ne sont pas visibles dans Fleet.

"_concernant l’iCAN numéro 1239, de notre côté les logs montrent que les messages sont bien envoyés vers FleetOne avec le code VIN VF6SXTF24H7203902. Rien de particulier à signaler de notre côté qui pourrait expliquer vos observations_."

**Comment by Portekoi** [comment]
Peuvent ils nous donner un message ID en particuliers que je vois de notre côté ce qu'il en est?

A première vue, je ne vois pas de code '1239' dans les logs. Pour aucun véhicule d'ailleurs.

**Comment by Portekoi** [comment]
D'ailleurs si je prends le fichier ci-joint, je ne vois pas de code 1239. Peut être ai-je mal compris.
[Data.sample.ICAN.Truck.zip](https://github.com/groupe-gac/FleetOne/files/1145134/Data.sample.ICAN.Truck.zip)

**Comment by AlainPierreSDPV** [comment]
le Pb semble résolu . Il y a dans certain cas un temps de latence avant que l'Ican transmette
