### ISSUE TITLE
UGAP - Changement arborescence DIR CENTRE OUEST - Pour le 18/07

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#175]
@MamboJoel , peux-tu faire le changement d'arborescence franchisé suivant (UGAP) : 

- DISTRICT A20 (Id 9205) : Parent Id actuel : 261 / Nouveau Parent Id : 370
- DISTRICT GUERET (Id 9203) : Parent Id actuel : 261 / Nouveau Parent Id : 370
- DISTRICT LIMOGES (Id 9204) : Parent Id actuel : 261 / Nouveau Parent Id : 370
- DISTRICT POITIER (Id 9206) : Parent Id actuel : 261 / Nouveau Parent Id : 370

Attention : Double arborescence UGAP 

Délai : mardi 18/07

Merci

**Comment by MamboJoel** [comment]
Ok. Tu peux vérifier ?

**Comment by MamboJoel** [comment]
Nous rencontrons le même problème que pour la #71.

**Comment by MamboJoel** [comment]
- Et aussi la #128 où j'avais [commenté](https://github.com/groupe-gac/FleetOne/issues/128#issuecomment-283381875) qu'on avait désormais une procédure `MoveClientToCompany`.

- J'ai effectué les traitements. La demande de Cyril se traduit par ces appels :
```sql
exec [MoveClientToCompany] 9205, 261, null
exec [MoveClientToCompany] 9203, 261, null
exec [MoveClientToCompany] 9204, 261, null
exec [MoveClientToCompany] 9206, 261, null
```

- En revanche à l'occasion de la #128 vous aviez rencontré un problème de profils système auquel le GP n'a pas accès (à l'époque Michel Alexandre) et vous aviez donc [dupliqué les profils](https://github.com/groupe-gac/FleetOne/issues/128#issuecomment-283975291).

- Je n'ai pas l'accès coservice de Clerfond donc je n'ai pas pu vérifier mon patch.

**Comment by PIEGAY** [comment]
Ce n'est pas bon. 
Les clients ont disparu de l'arborescence SDPV et ils sont maintenant uniquement chez BERNIS (Id 261) au lieu d'être chez BRUNAUD (Id 370) et chez SDPV

**Comment by PIEGAY** [comment]
Voila ce que nous avons dans FleetOne : 

![image](https://user-images.githubusercontent.com/22617815/28288458-88b543ea-6b3f-11e7-8926-dbaeb517da37.png)

**Comment by PIEGAY** [comment]
alors que nous devrions avoir comme le district A20 / Uzerche : 

![image](https://user-images.githubusercontent.com/22617815/28288504-abe65ebc-6b3f-11e7-99d3-2f207df7c3b7.png)

**Comment by MamboJoel** [comment]
Ok Cyril, je crois avoir résolu le problème :
![image](https://user-images.githubusercontent.com/3832009/28369386-b31afd42-6c97-11e7-9b6d-ecc5c87801ef.png)

**Comment by PIEGAY** [comment]
Il est bien réapparu sous SDPV mais il est toujours sous BERNIS (Id : 261) alors qu'il devrait être sous Bruneau / Régitrucks (Id : 370)

**Comment by MamboJoel** [comment]
Ok. Tu peux tester ?

**Comment by PIEGAY** [comment]
C'est bon !! Merci

**Comment by AlainPierreSDPV** [comment]
Nicolas peux tu extraire dans un fichier Excel ou TXT l'ensemble des visites avec leurs détails pour les véhicules des clients ci dessous depuis la date d'entrée en gestion de parc jusqu'au 17/07/2017 inclus

    DISTRICT A20 (Id 9205) :  
    DISTRICT GUERET (Id 9203) : 
    DISTRICT LIMOGES (Id 9204) :
    DISTRICT POITIER (Id 9206) :

**Comment by Portekoi** [comment]
Vous avez un exemple de fichier déjà transmis pour ce genre de demande pour que je vois les colonnes à mettre? Merci

**Comment by AlainPierreSDPV** [comment]
Bonjour Damien
Oui il existe déjà une requête pour cela dans le reporting mais je ne peux pas remonter plus loin que 2015
exemple pour le client ID 9205 url rep.gestionparc.com
Login: gestion-flotte-argenton.dirco@developpement-durable.gouv.fr
pw: dirco
choisir reporting financier puis bilan financier (3 exercices ) et nous pouvons exporter le fichier ci dessous qui convient mais que depuis 2015
[extraction bernis.zip](https://github.com/groupe-gac/FleetOne/files/1214850/extraction.bernis.zip)

**Comment by Portekoi** [comment]
Les identifiants ne semblent pas fonctionner.

**Comment by Portekoi** [comment]
Je pense avoir repéré la requête. Je creuse et je reviens vers vous.

**Comment by Portekoi** [comment]
J'ai essayé de récupérer les mêmes colonnes, dans le même ordre que l'écran de reporting. Dites moi si c'est bon et je ferai les autres.

[VHL-CLT-9205-Datein-20170717-20170818D-1.xlsx](https://github.com/groupe-gac/FleetOne/files/1234223/VHL-CLT-9205-Datein-20170717-20170818D-1.xlsx)

**Comment by AlainPierreSDPV** [comment]
c'est Ok pour moi avec les remarques ci-dessous
la colonne  Niv2 est à supprimer
il y a un décalage dans les entêtes de colonnes à partir de la colonne k
Limiter la requête date de visite < au 17/07/2017

**Comment by AlainPierreSDPV** [comment]
Bonjour Damien peux tu finaliser les extractions ?

**Comment by Portekoi** [comment]
Pour demain sans faute. Retour de vacances un peu chaotique.

**Comment by Portekoi** [comment]
[VHL-CLT-9205-DTVisit-20170717-20170829D-1.xlsx](https://github.com/groupe-gac/FleetOne/files/1259077/VHL-CLT-9205-DTVisit-20170717-20170829D-1.xlsx)
[VHL-CLT-9206-DTVisit-20170717-20170829D-1.xlsx](https://github.com/groupe-gac/FleetOne/files/1259078/VHL-CLT-9206-DTVisit-20170717-20170829D-1.xlsx)
[VHL-CLT-9204-DTVisit-20170717-20170829D-1.xlsx](https://github.com/groupe-gac/FleetOne/files/1259080/VHL-CLT-9204-DTVisit-20170717-20170829D-1.xlsx)
[VHL-CLT-9203-DTVisit-20170717-20170829D-1.xlsx](https://github.com/groupe-gac/FleetOne/files/1259079/VHL-CLT-9203-DTVisit-20170717-20170829D-1.xlsx)
