### ISSUE TITLE
ITM LAI - Intégration nouveau historique + basculement des visites hayon sur remorque

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#176]
@MamboJoel : Comme indiqué par téléphone tu trouveras ci-joint le fichier d'historique à réintégrer pour le client ITM LAI. 

[Intégration historique ITM 19072017.xlsx](https://github.com/groupe-gac/FleetOne/files/1159301/Integration.historique.ITM.19072017.xlsx)

De plus pour l'ensemble des véhicules sous le client ITM LAI (Id : 16310), il faudrait basculer les visites crées sous le hayon (équipement secondaire) sur la semi-remorque (équipement principal). 
Le client ne souhaite plus ressortir le hayon...

Merci d'avance

**Comment by MamboJoel** [comment]
C'est ok !

**Comment by PIEGAY** [comment]
C'est bon !

Merci
