### ISSUE TITLE
ITM LAI - Quelques modifications pour gagner du temps

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#177]
@MamboJoel nous avons besoin de quelques petites modifications pour gagner beaucoup de temps dans la gestion ITM.  

**Gestion du hayon**
Nous avons conservé l'onglet hayon pour la facturation et les informations liées au hayon mais avec un profil vide afin qu'il ne génère pas d'alertes. 
En revanche nous pouvons pas le sauvegarder : 
![image](https://user-images.githubusercontent.com/22617815/28464389-40f89af0-6e25-11e7-82eb-7edf42a7aa23.png)

**Paramétrage du profil de l'équipement principal**
Dans le profil de l'équipement principal pour l'ensemble du parc ITM LAI, il faudrait paramétrer l'organe, la nature et la facturation comme ci-dessous : 
![image](https://user-images.githubusercontent.com/22617815/28464487-d999a466-6e25-11e7-8e79-a5e553f78592.png)

**Utilisation des opérations protocole INTERMARCHE**
Lorsqu'on met dans une visite une opération du protocole intermarché, il apparaît toute l'arborescence : 
![image](https://user-images.githubusercontent.com/22617815/28464665-8066bc0c-6e26-11e7-9cc8-1de2365867fd.png)
Pouvons nous afficher uniquement le libellé de l'opération : "REMPL PLAQUETTES - ESSIEU 2"
exemple :  http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=c.16376&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=55275&AlertID=&VisitID=896927&Display=&tab=Visits&VehicleTab=Equipment-67576&EquipmentID=67576&MessageID=&MemberTab=Supplier&ClientTab=Vehicles&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=DW711SR&FromDate=01/01/2017&ToDate=31/12/2017&VehicleTS=1500473225145&VisitProcess=20&VisitReference=896984&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=

Merci

**Comment by MamboJoel** [comment]
Ok. On travaille dessus aujourd'hui.

**Comment by MamboJoel** [comment]
Concernant le paramétrage du profil de l'équipement principal : on retire tous les paramétrages existant et on remplace par celui présenté ici.

**Comment by MamboJoel** [comment]
Tout est ok.

**Comment by PIEGAY** [comment]
Parfait !!
Merci
