### ISSUE TITLE
FleetOne - Ajout d'une marque et modification des heures de rendez-vous

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#178]
@MamboJoel : 

Est-ce que tu peux ajouter la marque "ZEPRO" à la liste des marques dans la fiche véhicule : 

![image](https://user-images.githubusercontent.com/22617815/28502591-17892248-6ff6-11e7-888b-85fd75baf582.png)

Est-ce que tu mettre l'ensemble des heures de 00h00 à 23h30 (avec un pas de 30 min) dans la liste déroulante des heures d'une visite afin de pouvoir gérer les dépannages de nuit : 

![image](https://user-images.githubusercontent.com/22617815/28502606-4c647f58-6ff6-11e7-995a-7e147bf9afbd.png)

Merci

**Comment by MamboJoel** [comment]
C'est bon !
