### ISSUE TITLE
Création de fournisseur par les GP

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#18]
Message d'origine de Cyril :

> Les gestionnaires de parc ne peuvent plus créer de fournisseurs.
>  
> Comme indiqué par Alain, il faut que le gestionnaire de parc puisse :
> -          Créer un nouveau fournisseur avec un n° de siret
> -          Modifier la fiche contact
>  
> Avec le login administrateur :
> -          Modifier l’ensemble de la fiche

**Comment by MamboJoel** [comment]
C'est corrigé.
En revanche je vois que la réforme évoquée ici #11 pose des questions quant aux droits des GP. Comme on leur accorde un accès aux fournisseurs du pool commun ils ont la possibilité de détériorer les données des fournisseurs de ce pool. 
J'ai restreint l'accès en écriture par les GP aux seuls fournisseurs qui ont été créés à l'origine sous leur membre.

Par exemple Lionel Gozart ne peut pas modifier les données d'un fournisseur créé sous Alvarez puisqu'il n'a accès qu'à SDPV Grand Compte. Seul les admin système ont accès à tout.

**Comment by MamboJoel** [comment]
Anomalie :

- Nouveau fournisseur : 15364
- Prétend que ce SIRET existe déjà : 49315551900033 pour le fournisseur Le Poids Lourd 92 (IVCO) qui appartient au membre SDPV Grands Comptes.
- En revanche ce fournisseur est introuvable via la recherche.

**Comment by MamboJoel** [comment]
Le Poids Lourd 92 (IVECO) (SupplierID=15238) existe bien avec ce SIRET, mais n'est pas System. D'ailleurs il n'existe pas dans le fichier fourni par Alain  dans #11.
Il a pourtant été créé sous SDPV Grand Compte.

**Comment by MamboJoel** [comment]
J'ai fais la modification suivante :
On peut créer un fournisseur avec un SIRET déjà affecté à un fournisseur non system. C'est à dire un fournisseur créé avant la réforme, mais n'apparaissant plus, puisque désormais tous les fournisseurs sont system.

**Comment by PIEGAY** [comment]
Parfait cela fonctionne bien. 
Il faudrait masquer le fournisseur id  779 - GGE TIRARD car sa fiche est vide.

![image](https://cloud.githubusercontent.com/assets/22617815/19596863/1ca9bab4-9791-11e6-9570-5ede5ae5fd6b.png)

**Comment by PIEGAY** [comment]
De plus dans la fiche véhicule, il faut afficher l'ensemble des fournisseurs dans le menu déroulant "Fournisseur par défaut" : http://f2.sdpv.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=m.15204&VisitProcess=20&VehicleID=52049&AlertID=&VisitID=&FromDate=01/01/2016&ToDate=31/12/2016&Display=&tab=Edit&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=60010201&VisitReference=772643&VehicleTab=Equipment-64058&EquipmentID=64058&ClientTab=Vehicles&MemberTab=Supplier&VehicleTS=1477039499208&MessageID=&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=

![image](https://cloud.githubusercontent.com/assets/22617815/19597084/b3192d1c-9792-11e6-8b5b-0de137e2bbd1.png)

**Comment by PIEGAY** [comment]
Il faut que l'ensemble des gestionnaires de parc puissent modifier la fiche contact d'un fournisseur : 

![image](https://cloud.githubusercontent.com/assets/22617815/19600197/3479d2ba-97a4-11e6-9056-0b35f88f7a7f.png)

**Comment by MamboJoel** [comment]
- Ok pour le fournisseur par défaut du véhicule.
- Ok pour l'accès en écriture aux fournisseurs par les GP.

**Comment by MamboJoel** [comment]
Cyril, je suis en réunion téléphonique. Je n'ai pas pu bien noter l'anomalie, c'est confus dans mon esprit. Tu peux l'écrire ici et je la traiterai ensuite ?
Merci.

**Comment by PIEGAY** [comment]
Impossible de créer le fournisseur CONTROLEPLUS avec le SIRET 81976887000019 alors qu il n apparaît pas dans la liste.

**Comment by PIEGAY** [comment]
Vendredi tu avais modifié la procédure de contrôle du SIRET uniquement sur le fournisseur "système" et plus sur les fournisseurs "cachés". 
Apparemment c'est cette modification qui ne fonctionne plus.

Ce problème est urgent car les gestionnaires prennent du retard sur les fournisseurs non créés.

**Comment by MamboJoel** [comment]
Ok. Je viens d'avoir Alain ( #22 ).
Vous pouvez à nouveau créer des fournisseurs avec des SIRET de fournisseurs existants hors pool commun.

**Comment by MamboJoel** [comment]
Cas de la création d'un fournisseur avec un SIRET appartenant à un fournisseur hors du pool commun.
Alain, tu suggérais, au moment où l'écran d'erreur apparaît de basculer le fournisseur en "pool commun". Ça n'a pas de sens puisque désormais cet écran n'apparaît plus, l'erreur n'étant plus levée.
En revanche on peut travailler sur les derniers fournisseurs créés (entre la production du fichier XLS et son déploiement dans la base)

Voici la liste des derniers fournisseurs créés avec SIRET et qui ne sont pas "system".
[Fournisseurs dans l'intervalle.xlsx](https://github.com/groupe-gac/FleetOne/files/550624/Fournisseurs.dans.l.intervalle.xlsx)

Voulez-vous que je les passe tous en "system" ?

**Comment by MamboJoel** [comment]
[Fournisseurs dans l'intervalle.xlsx](https://github.com/groupe-gac/FleetOne/files/550638/Fournisseurs.dans.l.intervalle.xlsx)

**Comment by AlainPierreSDPV** [comment]
Il y a des doublons dans cette liste 
Peux tu me donner toutes les informations disponibles sur ces fournisseurs . je clean et SIRET ce fichier pour intégration comme fournisseurs system

**Comment by AlainPierreSDPV** [comment]
Ne pas oublier de modifier la fiche fournisseur 
en ajoutant 2 autres contacts MAGASIN ET FACTURATION avec les mêmes champS que le contact existant que l on nomme ATELIER

**Comment by MamboJoel** [comment]
C'est l'entrée #15

[Fournisseurs dans l'intervalle.xlsx](https://github.com/groupe-gac/FleetOne/files/550765/Fournisseurs.dans.l.intervalle.xlsx)

**Comment by PIEGAY** [comment]
Il n'y plus aucun test qui est fait sur le n° de SIRET. 
On peut créer n'importe quoi.

![image](https://cloud.githubusercontent.com/assets/22617815/19716248/09ea9290-9b5b-11e6-85fb-0dde08ec6c85.png)

Il faut corriger rapidement car on va à nouveau détériorer la base. 

Merci

**Comment by MamboJoel** [comment]
Ce sera corrigé ce soir avec une nouvelle mise à jour.
Je dois finir de tester #19 avant de publier.

**Comment by AlainPierreSDPV** [comment]
Ci joint fichier dédoublonné et sirété
[Copie de Fournisseurs.dans.l.intervalle.xlsx](https://github.com/groupe-gac/FleetOne/files/553540/Copie.de.Fournisseurs.dans.l.intervalle.xlsx)

**Comment by AlainPierreSDPV** [comment]
les sirets du fichier remplace les siret existants

**Comment by MamboJoel** [comment]
Comme prévu @PIEGAY , les tests SIRET sont réinstallés. Je traite le fichier @AlainPierreSDPV .
