### ISSUE TITLE
Anomalie d'édition côté V1 liaison Corine Artigueville

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#182]
### Description
Corine Artigueville remonte une anomalie côté V1.

### Scénario pour reproduire l'anomalie
http://www.gestionparc.com/parkadministration/vehicles/detail.asp?NodeID=5518&CustomerID=5518&VehicleID=56896&EquipmentID=70441

### Anomalie constatée
Une erreur serveur dans le champ "Immatriculation".

**Comment by Paulhac** [comment]
http://www.gestionparc.com/parkadministration/vehicles/detail.asp?NodeID=5518&CustomerID=5518&VehicleID=56896&EquipmentID=70441

**Comment by MamboJoel** [comment]
Je ne reproduis pas l'anomalie.

![image](https://user-images.githubusercontent.com/3832009/29456664-0845b410-8417-11e7-9a85-67002befdc50.png)
