### ISSUE TITLE
BUG sur reporting arrêts 

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#184]
page : rep.gestionparc.com/Full/ReportVisites.aspx  (reporting arrêts)

Login : alain.brunaud@renault-trucks.net
pw : ******
choisir translocacentre  / CHENCKER / visites par fournisseur   / 1 exercice
cliquer sur le nb de visites grand total et constater que le tableau est vide avec l'information ci-dessous

A field or property with name 'Kmindex' was not found in the selected data source. Possible causes of this error may be the following: an incorrect or case-insensitive spelling of the grid column name; assigning a wrong or not properly initialized data source to the grid.

**Comment by MamboJoel** [comment]
@Portekoi tu peux jeter un oeil ?

**Comment by Portekoi** [comment]
Je regarde

**Comment by Portekoi** [comment]
Ok j'ai reproduis. Je creuse.

**Comment by Portekoi** [comment]
J'ai livré une modification mais sans effet. Je dois peut être redémarrer le site pour que cela prenne effet.

**Comment by Portekoi** [comment]
J'ai redémarré mais sans succès. J'ai pourtant modifié la requête dans `ReportVisites.aspx`

Mais je ne peux pas tester en local car je n'ai pas DevExpress.

**Comment by Portekoi** [comment]
Je suis en train de récupérer les DLL de DevExpress du serveur. Je vais voir pour faire autrement.

**Comment by Portekoi** [comment]
J'ai des disparités entre ce qui est archivé et ce qui est en ligne. Comme si le fichier avait été modifié directement sur le FTP. Je reporte la modification et je commite à nouveau.

Ceci n'existe pas dans les sources :

    </dx:PivotGridField>
        <dx:PivotGridField ID="fgestionnaire" area="FilterArea" AreaIndex="2" FieldName="Gest" Caption="Gestionnaire" >
    </dx:PivotGridField>

**Comment by AlainPierreSDPV** [comment]
Pour moi c'est bon 
puis je clore @Portekoi  ?

**Comment by Portekoi** [comment]
C'est tout bon pour moi
