### ISSUE TITLE
Pas de pop up quand données GPS Ican = données GPS fournisseur par defaut

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#185]
Actuellement il y a un pup up quand données GPS Ican = données GPS fournisseur
quand les véhicules Clovis sont en parking ils sont souvent sur le parking du fournisseur par défaut donc génère des  pop up  en grand nombre; ils ne sont donc plus regarder comme des alertes cela discédite le système

**Comment by MamboJoel** [comment]
Je comprends la problématique. On fait ça aujourd'hui.

**Comment by MamboJoel** [comment]
C'est ok.
