### ISSUE TITLE
Extraction fichier contact SIMMT

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#186]
Est-ce que tu peux m'extraire la table des contacts SIMMT ayant un droit de reporting ?

Tu m'avais déjà fait cette extraction #76

MamboJoel was assigned by PIEGAY 9 months ago
@MamboJoel
MamboJoel commented 9 months ago • edited 9 months ago
Contacts SIMMT.xlsx

Info technique :

Select * from SIMMT_CONTACTS

**Comment by Portekoi** [comment]
Voici le fichier
[Fleet-SIMMT-20170914D-1.xlsx](https://github.com/groupe-gac/FleetOne/files/1303072/Fleet-SIMMT-20170914D-1.xlsx)

**Comment by PIEGAY** [comment]
Merci !!

Envoyé de mon iPhone

Le 14 sept. 2017 à 15:15, Portekoi <notifications@github.com<mailto:notifications@github.com>> a écrit :


Voici le fichier
Fleet-SIMMT-20170914D-1.xlsx<https://github.com/groupe-gac/FleetOne/files/1303072/Fleet-SIMMT-20170914D-1.xlsx>
