### ISSUE TITLE
ecart de réponse interrogation 3A entre FleetOne et Fleetreception

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#187]
![3a fleet reception](https://user-images.githubusercontent.com/22592053/30587742-877a4ef4-9d34-11e7-828f-9a09d25a905a.JPG)
![3a fleetone](https://user-images.githubusercontent.com/22592053/30587750-900803ea-9d34-11e7-9872-8e58fded5987.JPG)

**Comment by Portekoi** [comment]
Je vais regarder.

**Comment by Portekoi** [comment]
Est il possible de me donner des accès à Fleet Réception ( http://fr.sdpv.com/Default.aspx ?)
Et me dire ensuite dans quel menu aller pour effectuer une recherche 3A?
Merci

**Comment by AlainPierreSDPV** [comment]
alain.pierre@sdpv.com
97S*******@
****** = ce que tu sais

**Comment by Portekoi** [comment]
Apparemment, cela vient du fait que le client n'a pas concessionID rattaché : 

![image](https://user-images.githubusercontent.com/1560754/30593378-9fc00b3c-9d4a-11e7-8b95-1ec5c2a16096.png)

**Comment by AlainPierreSDPV** [comment]
le memberID est le 57    "SUD ALSACE TRUCKS"

**Comment by Portekoi** [comment]
Je trouve pas ce `memberID `57 : 

![image](https://user-images.githubusercontent.com/1560754/30597027-0f9e2d7a-9d56-11e7-82a0-1c411fb8efda.png)

Mais je trouve bien un  `SUD ALSACE TRUCKS` sans concession.

**Comment by AlainPierreSDPV** [comment]
essaye memberID  186  "CATRA SAS"

**Comment by Portekoi** [comment]
Non plus. Je dois pas chercher au bon endroit. A quel concession est rattaché `SUD ALSACE TRUCKS` ? le 57?

**Comment by AlainPierreSDPV** [comment]
c'est dans admin SDPV que je cherche les Id ci-joint la table
[id.concession.xlsx](https://github.com/groupe-gac/FleetOne/files/1314599/id.concession.xlsx)

**Comment by AlainPierreSDPV** [comment]
http://www.sdpv.com/sdpv/Listegroupes.asp

login alain.pierre@sdpv.com
PW  celui de Id.coservices

**Comment by Portekoi** [comment]
Oui je viens bien la liste mais dans quel groupe devrait être `SUD ALSACE TRUCKS`

Et comment lui attribuer une concession? Une interface pour gérer ça?

**Comment by AlainPierreSDPV** [comment]
Sud Alsace est un groupe qui a plusieurs concessions
C est Dans Sdpv que cela s administre je pense que Jacques ou Nicolas peuvent te dire ou sont les tables

Envoyé de mon iPhone

Le 19 sept. 2017 à 16:35, "Portekoi" <notifications@github.com<mailto:notifications@github.com>> a écrit :


Oui je viens bien la liste mais dans quel groupe devrait être SUD ALSACE TRUCKS

Et comment lui attribuer une concession? Une interface pour gérer ça?

**Comment by MamboJoel** [comment]
@Portekoi `Member.SDPVConcessionID` doit contenir l'`idconcession` de la table `concession` de `gestionsdpv1`. Si ça peut aider...

**Comment by Portekoi** [comment]
@MamboJoel Merci pour l'info concernant les concessions.

Mais je ne sais pas quel `concessionID` attribuer à `SUD ALSACE TRUCKS`

La plaque `EH-319-TE` appartient au `Vehicle` n° `53873`, appartenant au `customerID`  `CATRA - Colmar` dont le `memberID` est `16027` - `SUD ALSACE TRUCKS`

Pour ce `memberID` - `16027`, la colonne `IDConcession` est à `NULL`

Donc : quel `IDConcession` dois-je mettre parmi la liste des concessions ci-dessous?
[id.concession.xlsx](https://github.com/groupe-gac/FleetOne/files/1314599/id.concession.xlsx)

**Comment by Portekoi** [comment]
Ok je viens de retrouver dans le dit fichier : 
` 186 | CATRA SAS | Sud alsace trucks | COLMAR`

Donc je mets `IDConcession` 186 pour le memberID `16027`.

**Comment by Portekoi** [comment]
Update effectué : 

`update member set IDConcession = 340 where id = 16027`

@AlainPierreSDPV Cela devrait fonctionner maintenant.

**Comment by AlainPierreSDPV** [comment]
c 'est ok merci
