### ISSUE TITLE
Problème avec la validation VGP - Visite id 811298

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#19]
http://f2.sdpv.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=m.15204&VisitProcess=20&VehicleID=37839&AlertID=&VisitID=811298&FromDate=01/01/2016&ToDate=31/12/2016&Display=&tab=Visits&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=71230072&VisitReference=811298&VehicleTab=Equipment-64058&EquipmentID=64058&ClientTab=Vehicles&MemberTab=Supplier&VehicleTS=1477039499208&MessageID=&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=

Dans la visite 811298, l'opération VGP est validée en statut "X - Report de la visite".
Par conséquent, la prochaine "VGP levage 6 mois" doit rester au 04/10/2016 et non au 04/04/2017 

![image](https://cloud.githubusercontent.com/assets/22617815/19600541/ca762042-97a5-11e6-97ea-63d53676ce58.png)

**Comment by MamboJoel** [comment]
En fait cette opération est réglementaire mais pas CT. Elle ne devrait pas faire l'objet d'une gestion de type CT (contre visite, etc). Il y avait une anomalie donc à proposer ces options. J'ai corrigé.
Si tu souhaites une gestion de type CT pour cette opération préviens-moi.

**Comment by PIEGAY** [comment]
Nous avons besoin de traiter les opérations réglementaires comme un contrôle technique : 
- Une date précise pour le contrôle (qui n'est pas forcément la date de la visite)
- Un résultat (Accepté, Observations, Sursis, Refus, Report)

**Comment by MamboJoel** [comment]
Je m'en remets à @AlainPierreSDPV 
Il semblerait Cyril que tu voudrais que le comportement des réglementaire soit exactement le même que des CT. C'est une nuance fondamentale de l'appli. Alain qu'en penses-tu ?

**Comment by AlainPierreSDPV** [comment]
Les visites réglementaires CT ont une propriété particulière
Ce sont des visites réalisées exclusivement par des organismes agréés qui donnent à la suite du contrôle un statut. Le S et le R donne  lieu à une contrevisite dans un délai qui est paramétrable à l'opération .

Dans le reporting les visites CT sont distinguées des autres 

Nous ne pouvons donc pas qualifier la VGP comme réglementaire CT 

Si nous voulons historiser le report ou  le refus,. Je peux ajouter ces opérations au catalogue des opérations  du genre "VGP non conforme" "VGP reportée". qui pourrons être utilisées dans la visite tout en décochant l'opération VGP pour que cette opération ne soit pas validée 

qu'en pense Cyril ?

**Comment by MamboJoel** [comment]
J'ai remis la version d'avant

`Proc stock : GetVehiclePlanning`

**Comment by MamboJoel** [comment]
Après discussion avec Alain Pierre :

Calcul des alertes **réglementaires** :
- Maintenir date et résultat comme si c'était des CT.
- Si le résultat est "x" ne pas recalculer l'alerte.

**Comment by MamboJoel** [comment]
Ok. J'ai modifié le calcul des alertes réglementaires comme indiqué dans le message précédent. 
J'ai conduit pas mal de tests, j'espère qu'il n'y aura pas trop de turbulence.
La VGP de BB-690-AS est bien calculée au 4 octobre.
