### ISSUE TITLE
FLEETONE - INTEGRATION D'UNE NOUVELLE BASE INTERMARCHE

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#193]
@MamboJoel nous avons intégré une nouvelle base intermarché dans FleetOne : BASE ITM LAI ARGENTRE DU PLESSIS (ID 17024). 

Les véhicules ont été intégrés avec le fichier excel dédié mais quelques ajouts sont nécessaires. 

**Compléter la fiche "information véhicule"**
Tu trouveras ci-dessous le fichier pour compléter la "information véhicule" : 
[Complément fiche information véhicule.xlsx](https://github.com/groupe-gac/FleetOne/files/1337361/Complement.fiche.information.vehicule.xlsx)
- Gestionnaire
- Fournisseur par défaut

![image](https://user-images.githubusercontent.com/22617815/30916662-3b2ce8b0-a39a-11e7-87f5-cc54a836134d.png)

**Compléter la fiche de l'équipement principal**
Tout d'abord il faudrait lancer la documentation avec AAA de la fiche "équipement principal" pour l'ensemble des véhicule de ce client. 

![image](https://user-images.githubusercontent.com/22617815/30916765-7ed01fb0-a39a-11e7-92db-f051db34b9d8.png)

Ensuite il faudrait compléter la fiche de l'équipement principal avec le fichier suivant : 
[Complément fiche équipement principal.xlsx](https://github.com/groupe-gac/FleetOne/files/1337374/Complement.fiche.equipement.principal.xlsx)
- N° de parc
- Type

![image](https://user-images.githubusercontent.com/22617815/30916848-acd678d2-a39a-11e7-8a0e-0e68d6ee40bf.png)

**Créer un équipement secondaire**
Enfin il faudrait créer les équipements secondaires avec le fichier ci-dessous : 
[Création équipement hayon.xlsx](https://github.com/groupe-gac/FleetOne/files/1337405/Creation.equipement.hayon.xlsx)
- NOM
- N° DE PARC
- TYPE
- DATE IMMAT
- MARQUE

![image](https://user-images.githubusercontent.com/22617815/30917142-9137b75c-a39b-11e7-90f5-de3e833e173e.png)

Merci !!

Cyril

**Comment by MamboJoel** [comment]
Cyril, tu peux déjà checker la documentation AAA.

**Comment by PIEGAY** [comment]
Non les AAA n’a pas été réalisé

  Cordialement,

Cyril PIEGAY

[cid:image003.png@01D337B0.41959450]



Responsable plateforme gestion de parc

Tél: 04 72 13 34 72 / 06 72 84 05 56

Fax : 04 72 13 90 27

Email : cyril.piegay@force-reseau.com<mailto:cyril.piegay@force-reseau.com> – NOUVEAU !

Adresse : 20 Bd Eugène Deruelle - Le Britannia – Bât C –  69432 LYON Cedex 03

[cid:image004.png@01D337B0.41959450]

www.force-reseau-gp.com<http://www.force-reseau-gp.com/> - Découvrez vite notre nouveau site !



De : Nicolas Taret [mailto:notifications@github.com]
Envoyé : mercredi 27 septembre 2017 16:39
À : groupe-gac/FleetOne <FleetOne@noreply.github.com>
Cc : Cyril Piegay <cyril.piegay@force-reseau.com>; Author <author@noreply.github.com>
Objet : Re: [groupe-gac/FleetOne] FLEETONE - INTEGRATION D'UNE NOUVELLE BASE INTERMARCHE (#193)


Cyril, tu peux déjà checker la documentation AAA.

**Comment by MamboJoel** [comment]
En effet. Tu peux vérifier de nouveau. AAA a retourné 74 fiches sur les 74 demandées.

**Comment by PIEGAY** [comment]
C’est bon !!

  Cordialement,

Cyril PIEGAY

[cid:image003.png@01D337B2.0E0DD410]



Responsable plateforme gestion de parc

Tél: 04 72 13 34 72 / 06 72 84 05 56

Fax : 04 72 13 90 27

Email : cyril.piegay@force-reseau.com<mailto:cyril.piegay@force-reseau.com> – NOUVEAU !

Adresse : 20 Bd Eugène Deruelle - Le Britannia – Bât C –  69432 LYON Cedex 03

[cid:image004.png@01D337B2.0E0DD410]

www.force-reseau-gp.com<http://www.force-reseau-gp.com/> - Découvrez vite notre nouveau site !



De : Nicolas Taret [mailto:notifications@github.com]
Envoyé : mercredi 27 septembre 2017 16:58
À : groupe-gac/FleetOne <FleetOne@noreply.github.com>
Cc : Cyril Piegay <cyril.piegay@force-reseau.com>; Author <author@noreply.github.com>
Objet : Re: [groupe-gac/FleetOne] FLEETONE - INTEGRATION D'UNE NOUVELLE BASE INTERMARCHE (#193)


En effet. Tu peux vérifier de nouveau. AAA a retourné 74 fiches sur les 74 demandées.

**Comment by MamboJoel** [comment]
Ok tu peux vérifier l'ensemble des données. 

### Sur la redondance d'une telle demande

Pour l'avenir j'ai implémenté un minimum de formalisation pour intégrer ces _**"compléments d'information parc"**_ selon le format de fichiers XLS que tu m'as fourni aujourd'hui. L'idéal serait même que tu me les transmettes en csv directement (tu peux faire "Enregistrer sous", etc.). Au fond on préfère toujours ce format à XLS puisqu'il est garanti sans décoration, calculs, merges et autres. Même si dans ce cas tes XLS sont passés sans aucun problème...
A l'avenir tu peux donc me transmettre les données de cette façon : un fichier pour le véhicule, le principal, le secondaire ; avec ces noms de colonnes ; et en spécifiant le client pour AAA. 
Tu peux ajouter d'autres colonnes ou process et on enrichira la routine.

### Note technique :
Nom du service : `Waybis.Sdpv.Fleet.VehicleDocumentationService`
Appelé depuis : `Waybis.Sdpv.Fleet.Helper`

**Comment by PIEGAY** [comment]
OK pour la fiche « information véhicule »
OK pour la création de l’équipement secondaire

En revanche l’équipement principal n’a pas été renseigné sur le n° de parc et le type :

[cid:image001.png@01D337B9.6C76AA70]


De : Nicolas Taret [mailto:notifications@github.com]
Envoyé : mercredi 27 septembre 2017 17:48
À : groupe-gac/FleetOne <FleetOne@noreply.github.com>
Cc : Cyril Piegay <cyril.piegay@force-reseau.com>; Author <author@noreply.github.com>
Objet : Re: [groupe-gac/FleetOne] FLEETONE - INTEGRATION D'UNE NOUVELLE BASE INTERMARCHE (#193)


Ok tu peux vérifier l'ensemble des données.

Sur la redondance d'une telle demande

Pour l'avenir j'ai implémenté un minimum de formalisation pour intégrer ces "compléments d'information parc" selon le format de fichiers XLS que tu m'as fourni aujourd'hui. L'idéal serait même que tu me les transmettes en csv directement (tu peux faire "Enregistrer sous", etc.). Au fond on préfère toujours ce format à XLS puisqu'il est garanti sans décoration, calculs, merges et autres. Même si dans ce cas tes XLS sont passés sans aucun problème...
A l'avenir tu peux donc me transmettre les données de cette façon : un fichier pour le véhicule, le principal, le secondaire ; avec ces noms de colonnes ; et en spécifiant le client pour AAA.
Tu peux ajouter d'autres colonnes ou process et on enrichira la routine.

Note technique :

Nom du service : Waybis.Sdpv.Fleet.VehicleDocumentationService
Appelé depuis : Waybis.Sdpv.Fleet.Helper

**Comment by PIEGAY** [comment]
OK pour la fiche « information véhicule »
OK pour la création de l’équipement secondaire

En revanche l’équipement principal n’a pas été renseigné sur le n° de parc et le type :

![image](https://user-images.githubusercontent.com/22617815/30954173-8093cca8-a42f-11e7-931e-879da4aeecf3.png)

**Comment by MamboJoel** [comment]
Ok. Tu peux vérifier.

**Comment by PIEGAY** [comment]
C'est bon parfait !!
