### ISSUE TITLE
UGAP : Mouvement client chez franchisé (Double Arborescence) - Lundi 02/10

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#196]
@MamboJoel,

Quelques clients UGAP gérés actuellement sur la plateforme bascule **lundi 02 Octobre** en gestion chez des franchisés.
Par conséquent, il faut me réaliser les doubles arborescences suivantes :

**VILLE DE NOISY**

id client : 15845 (VILLE DE NOISY LE GRAND)
Id parent côté SDPV : 7371 (VILLES)
Id parent côté FRANCHISE : 254 (SOCREC )

**VILLE DE LAGNY SUR MARNE**

Id client : 14777 (VILLE DE LAGNY SUR MARNE)
Id parent côté SDPV : 7371 (VILLES)
Id parent côté FRANCHISE : 254 (SOCREC )

**VILLE DE TOULON**

Id client : 16444 (VILLE DE TOULON)
Id parent côté SDPV : 7371 (VILLES)
Id parent côté FRANCHISE : 13867 (AZUR TRUCKS / MARCHE UGAP)

**COMMUNAUTE DE COMMUNES DU LUNEVILLOIS**

Id client : 7613 (COMMUNAUTE DE COMMUNES DU LUNEVILLOIS)
Id parent côté SDPV : 7604 (COMMUNAUTES DE COMS)
Id parent côté FRANCHISE : 16957 (UGAP - LOCATRANS)

Merci !!

**Comment by PIEGAY** [comment]
Nous l'avons déjà fait #128

**Comment by PIEGAY** [comment]
Est-ce que cela sera bon pour lundi ? 
Merci

**Comment by Portekoi** [comment]
Je viens d'utiliser la procédure de @MamboJoel pour le premier cas. Merci de vérifier que cela soit bon pour vous et je ferai les autres.

**Comment by Portekoi** [comment]
Auparavant, j'ai sauvegardé la table `Customer` sous `Customer20170929D`

**Comment by PIEGAY** [comment]
non le client n’apparaît pas sous 254 (SOCREC )

**Comment by Portekoi** [comment]
Bizarre. l'update est pourtant bien passé : 

Avant : 
![image](https://user-images.githubusercontent.com/1560754/31025196-ec7664f4-a541-11e7-92b5-056fd835108e.png)


Après : 
![image](https://user-images.githubusercontent.com/1560754/31025183-dbcb7d9c-a541-11e7-9eca-0a677266fb95.png)

**Comment by Portekoi** [comment]
Je pense que cela doit être un problème de cache. Je crois qu'il y a un lien qui permet de le recharger. Je vais chercher.

**Comment by Portekoi** [comment]
SI je compare avec Drancy qui elle apparait bien : 
![image](https://user-images.githubusercontent.com/1560754/31025538-43c9c34e-a543-11e7-87a9-cca5dec36f9d.png)

**Comment by Portekoi** [comment]
Cela devrait être ceci le résultat? 

![image](https://user-images.githubusercontent.com/1560754/31025906-b187f1e8-a544-11e7-84dd-388419fdc476.png)

**Comment by Portekoi** [comment]
C'est rechargé. Merci de contrôler et me dire si c'est bon.

**Comment by PIEGAY** [comment]
Ok je regarde dans une petite heure

Cyril

Envoyé de mon iPhone

Le 29 sept. 2017 à 18:36, Portekoi <notifications@github.com<mailto:notifications@github.com>> a écrit :


C'est rechargé. Merci de contrôler et me dire si c'est bon.

**Comment by PIEGAY** [comment]
Parfait !!!
Si tu peux faire les autres pour lundi...
Merci bcp

**Comment by Portekoi** [comment]
Ca devrait être bon

**Comment by PIEGAY** [comment]
Impeccable !!
Tout fonctionne 
Merci beaucoup pour ta disponibilité

**Comment by Portekoi** [comment]
Aucun problème. Bon week end.

**Comment by AlainPierreSDPV** [comment]
Oui merci Damien ta disponibilité est précieuse en ces moments un peu spide
Bon week end


Envoyé de mon iPhone

Le 29 sept. 2017 à 21:56, "PIEGAY" <notifications@github.com<mailto:notifications@github.com>> a écrit :


Impeccable !!
Tout fonctionne
Merci beaucoup pour ta disponibilité
