### ISSUE TITLE
BUG sur la saisie de l'index horaire dans la visite

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#197]
Bug relevé par Michel Alexandre
"J’ai inscrit les heures de fonctionnement moteur dans la casse heure
A la sauvegarde de la visite, les heures se sont dupliqués dans la case km automatiquement.
Malheureusement ce n’est pas à chaque fois !!!"
[Doc1.docx](https://github.com/groupe-gac/FleetOne/files/1358571/Doc1.docx)

j'ai réussi à reproduire avec un véhicule du TPS demo 69

utiliser la visite ci dessous

http://membre.force-reseau-gp.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=m.499&VisitProcess=12&VehicleID=54176&AlertID=&VisitID=920834&FromDate=01/01/2017&ToDate=31/12/2017&Display=&tab=Visits&MessageID=&VehicleTab=VehicleInfo&EquipmentID=&VVS_VehicleID=51498&VVS_OrganIDs=0&VVS_NatureIDs=0&VVS_Accounts=&VVS_VehicleType=AllEquipments&VVS_FromDate=01/02/2017&VVS_ToDate=31/10/2017&VVS_Tags=&AlertFromDate=01/01/1900&AlertToDate=02/11/2017&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=bl109&HasMandatoryAlert=false&MonthsForAlert=1&MemberTab=Profiles&VehicleTS=1507194877265&ClientTab=Vehicles&VisitReference=907454

c'est un véhicule avec un profil qui utilise comme index que des Heures
créer une nouvelle visite
Entrer une valeur comme index horaire pour cette visite par exemple 850 et sauvegarder 
puis modifier la date de la visite avec une date d'entrée et de sortie antérieur à la date du jour qui est proposée par défaut 
cocher les opérations qui sont en alerte dépassée (3 op) puis sauvegarder la visite en indiquant que les travaux ont bien été réalisés.
constater que l'index kilométrique prend alors la même valeur que l'index horaire soit 850 km

**Comment by Portekoi** [comment]
J'ai corrigé mais je ne peux livrer (attente du SSO)

**Comment by Portekoi** [comment]
Pour montrer que c'est corrigé (sur la branche SSO) : 
![image](https://user-images.githubusercontent.com/1560754/32503827-84777e86-c3de-11e7-9ca7-5b28828f4840.png)

**Comment by AlainPierreSDPV** [comment]
Ok je clos cette issue
