### ISSUE TITLE
UGAP - Mouvement client (Double arborescence) -09/10

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#198]
@MamboJoel,

Quelques clients UGAP gérés actuellement sur la plateforme bascule lundi 09 Octobre en gestion chez des franchisés.
Par conséquent, il faut me réaliser les doubles arborescences suivantes :

**SDIS 22**

id client : 16353 (SDIS 22)
Id parent côté SDPV : 15980 (SDIS)
Id parent côté FRANCHISE : 1155 (KERTRUCKS LOCATION SERVICES)

**VILLE DE TREGUEUX**

Id client : 15919 (VILLE DE TREGUEUX)
Id parent côté SDPV : 7371 (VILLES)
Id parent côté FRANCHISE : 1155 (KERTRUCKS LOCATION SERVICES)

**MONTPELLIER MED. METROPOLE**

Id client : 16807 (MONTPELLIER MED. METROPOLE)
Id parent côté SDPV : 6944 (COMMUNAUTES D'AGGLOS)
Id parent côté FRANCHISE : 420 (GROUPE MARTY)

Merci !!

**Comment by PIEGAY** [comment]
Idem issue #196

**Comment by Portekoi** [comment]
@PIEGAY Je viens de faire le premier : est-ce que c'est bon? Si oui, je ferai les autres demain ou après demain grand max.

**Comment by Portekoi** [comment]
Le résultat : 
![image](https://user-images.githubusercontent.com/1560754/31296296-0f9d8926-aae2-11e7-893a-4c08474e7709.png)

**Comment by PIEGAY** [comment]
C’est parfait !!

Merci



Le 6 oct. 2017 à 22:02, Portekoi <notifications@github.com<mailto:notifications@github.com>> a écrit :


Le résultat :
[image]<https://user-images.githubusercontent.com/1560754/31296296-0f9d8926-aae2-11e7-893a-4c08474e7709.png>

**Comment by Portekoi** [comment]
J'ai passé les deux autres. J'avais sauvegardé la table `Customer`

**Comment by Portekoi** [comment]
![image](https://user-images.githubusercontent.com/1560754/31296914-5ce8bd02-aae4-11e7-921c-b9e8b2b261cc.png)



![image](https://user-images.githubusercontent.com/1560754/31296877-32a50258-aae4-11e7-8777-2e930fefaee0.png)

**Comment by PIEGAY** [comment]
Merci bcp
Impeccable
Pour les libellés de RTD s’est possible de publier avant le SSO ?



Le 6 oct. 2017 à 22:19, Portekoi <notifications@github.com<mailto:notifications@github.com>> a écrit :




[image]<https://user-images.githubusercontent.com/1560754/31296877-32a50258-aae4-11e7-8777-2e930fefaee0.png>

**Comment by Portekoi** [comment]
J'ai peur que non. La modification était déjà sur la branche... 

Je peux peut être livrer sur cette fameuse version SSO : http://fleet.fr.ntlm.tech/account/logon ?

**Comment by PIEGAY** [comment]
On en parle lundi avec Nicolas car j’ai une présentation la semaine prochaine et Jacques est en train de dvlt le reporting sur cette base

Merci pour l’ugap

Envoyé de mon iPhone

Le 6 oct. 2017 à 22:40, Portekoi <notifications@github.com<mailto:notifications@github.com>> a écrit :


J'ai peur que non. La modification était déjà sur la branche...

Je peux peut être livrer sur cette fameuse version SSO : http://fleet.fr.ntlm.tech/account/logon ?

**Comment by PIEGAY** [comment]
@Portekoi je suis désolé j'ai oublié un client....

**GRENOBLE ALPES METROPOLE**

id client : 16960 (GRENOBLE ALPES METROPOLE)
Id parent côté SDPV : 15948 (METROPOLE)
Id parent côté FRANCHISE : 16957 (UGAP - LOCATRANS)

Cela peut attendre la semaine prochaine pour celle ci

**Comment by Portekoi** [comment]
Aucun problème. Je fais ça dans le week end.

**Comment by Portekoi** [comment]
C'est fait

**Comment by PIEGAY** [comment]
Merci !!
