### ISSUE TITLE
Problème date alerte sur limiteur de vitesse - véhicule ED-650-SJ

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#20]
**Problème rencontré**

Sur le véhicule ED-650-SJ : http://f2.sdpv.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=c.8152&VisitProcess=20&VehicleID=39782&AlertID=&VisitID=0&FromDate=01/01/2016&ToDate=31/12/2016&Display=&tab=Visits&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=ED-650-SJ&VisitReference=814214&VehicleTab=Equipment-47631&EquipmentID=47631&ClientTab=Users&MemberTab=Supplier&VehicleTS=1477316897722&MessageID=&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=

Pour l'opération "Limiteur de vitesse" : Périodicité 12 mois
Date ancienne opération : 21/07/2016
Date prochaine opération : 22/09/2016 alors que nous devrions avoir 21/07/2017

**Comment by MamboJoel** [comment]
Cette opération était paramétrée au km. Tous les 12km. J'ai corrigé le profil.
