### ISSUE TITLE
UGAP - DEPARTEMENT DU LOIRET - COCHER OPTION DEPANNAGE 

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#200]
@MamboJoel / @Portekoi ,

Merci de cocher l'option "Dépannage / Remorquage" pour les véhicules du fichier ci-joint appartenant au client "DEPARTEMENT DU LOIRET" (Id - 13754). 

![image](https://user-images.githubusercontent.com/22617815/31317485-219a85a0-ac42-11e7-9a2c-bac819c49d4a.png)

[Département du loiret - Opt dépannage.xlsx](https://github.com/groupe-gac/FleetOne/files/1366934/Departement.du.loiret.-.Opt.depannage.xlsx)

Merci !!

**Comment by Portekoi** [comment]
Je vais regarder.

**Comment by Portekoi** [comment]
C'est fait
