### ISSUE TITLE
BUG sur calcul d'alerte 

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#206]
Membre CODICA  id = 280
Véhicule immat DL-783-XL véhiculeID = 47740
profile ID = 8405
opération ID = 1422 

visite

visite http://membre.force-reseau-gp.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=m.280&VisitProcess=12&VehicleID=47740&AlertID=&VisitID=736922&FromDate=01/01/2017&ToDate=31/12/2017&Display=&tab=Visits&MessageID=&VehicleTab=Equipment-58156&EquipmentID=58156&VVS_VehicleID=51498&VVS_OrganIDs=0&VVS_NatureIDs=0&VVS_Accounts=&VVS_VehicleType=AllEquipments&VVS_FromDate=01/02/2017&VVS_ToDate=31/10/2017&VVS_Tags=&AlertFromDate=01/01/1900&AlertToDate=02/11/2017&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=dl783&HasMandatoryAlert=false&MonthsForAlert=1&MemberTab=Profiles&VehicleTS=1507634988544&ClientTab=Info&VisitReference=907454&ProfileCategoryID=375&ProfileID=8405

cette visite valide l'opération    Vérifier Jeu des soupapes (1422)
tel qu'elle a été programmée elle ne devrait être recalculée
![capture](https://user-images.githubusercontent.com/22592053/32044250-5817d5d4-ba3d-11e7-9d29-babb3853b5f2.JPG)

**Comment by Portekoi** [comment]
@AlainPierreSDPV 
Je vois que la visite date du 12/2015. D'après le profil établit, c'est tous les 24 mois ou 200 000 Km.
Pour moi, il est normal qu'elle soit prévue pour le 12/2017.
Mais je pense avoir mal compris.

**Comment by AlainPierreSDPV** [comment]
la règle de l'opération est la suivante
pour les dates
date de mise en service du véhicule 20/11/2014 la date le recalcule de l'alerte ne se fera pas si 21/11/2014 + 36 mois soit 21/11/2017 est inférieur à la date de la dernière intervention + 24 mois soit 21/12/2015 + 24 mois soit 21/12/2017   ce qui est le cas

pour les Kms
Index dernière intervention + 200 000 Km soit 431463  qui est supérieur à l'index de fin de recalcule de l'alerte qui est 300 000 Km

**Comment by Portekoi** [comment]
OK je vais regarder.

**Comment by Portekoi** [comment]
En prenant en Debug le programme, je constate que la date de départ prise en compte pour le calcul des alertes n'est jamais la date de mise en service SAUF s'il n'y a jamais eu de visite auparavant pour cette intervention.
Sinon, la date prise en compte est la date de dernière visite.

Source : `ProfileProgrammation`  ligne `137`
`startDate = LastIntervention.Visit.StartDate`

Si je dois modifier cette date pour la remplacer par : 
`startDate = Equipment.ServiceDate`

*J'aimerais avoir l'accord de @MamboJoel  car cela impactera toutes les autres règles se basant sur une date.*

**Comment by Portekoi** [comment]
Ne pas tenir compte de ma réponse.

**Comment by Portekoi** [comment]
En reprenant le programme plus bas et en lisant ce qu'il fait : 
Si l'âge de l'équipement en mois est supérieur à `Début (de Profil Programmation)` et qu'il est inférieur à `Fin (de Profil Programmation)` soit : 
Âge de l'équipement : 35 mois ce qui est donc bien inférieur à `Fin` qui est de 36 mois
Alors un rappel est généré.

Donc si je reprends le détail du calcul

1. Date de dernière intervention pour cette opération : 21/12/2015
1. Le véhicule a t il plus de 36 mois? non, il en a 35.
1. Est-on dans les `bornes` du `Profile` : Oui car 35 est supérieur à 0 et  inférieur à 36

Donc pour corriger ce cas, il faudrait ajouter : Est on dans les `bornes` du `Profile` et est ce que la date de prochaine intervention dépasse `Date de mise en service` + `Borne supérieur du Profile`

SI oui, on ne recalcule pas le rappel.

**Comment by Portekoi** [comment]
Pas évident de se replonger dans ce calcul. 

Donc, voici le résultat obtenu : 
![image](https://user-images.githubusercontent.com/1560754/32133241-5152cc52-bbd4-11e7-83a7-d96cae5c5523.png)


@MamboJoel J'ai modifié mais pas **commité**. Et je ne voulais pas faire un pull request pour éviter un merge hasardeux encore.

Fichier `ProfileProgrammation` / Ligne 231

Contrôle des bornes par rapport au `Profile Programmation`

Avant : On vérifie que l'âge de l'équipement soit compris dans les bornes définies du profile.
`ElseIf Equipment.AgeInMonths.Value >= FromValue And (Not ToValue.HasValue OrElse Equipment.AgeInMonths.Value <= ToValue.Value) Then`

Après : On vérifie que l'âge de l'équipement soit compris dans les bornes définies du profile et que la date de rappel ne soit pas supérieure à la date de `mise en service du véhicule` + `borne de fin du profile programmation`
`ElseIf Equipment.AgeInMonths.Value >= FromValue And (Not ToValue.HasValue OrElse (Equipment.AgeInMonths.Value <= ToValue.Value And Equipment.ServiceDate.Value.AddMonths(ToValue.Value) > nextDate)) Then`

**Comment by MamboJoel** [comment]
J'ai suivi votre échange et @Portekoi ta réforme me paraît améliorer le calcul pour traiter précisément ce cas de figure. Tu peux commiter/pousser/déployer. Cette entrée et bien documentée, si demain nous avons des retours nous pourrons facilement remonter jusqu'ici.

**Comment by Portekoi** [comment]
Je peux pas livrer à cause du SSO.

**Comment by MamboJoel** [comment]
Tu peux livrer sur fleet.fr.ntlm.tech ?

**Comment by Portekoi** [comment]
De mémoire, c'est le dossier `FleetMVC_switch`. Ok je livre.

**Comment by MamboJoel** [comment]
Oui c'est celui-là.

**Comment by Portekoi** [comment]
C'est en ligne. J'ai renommé le dossier  en `FleetMVC_switch.20171028D`

**Comment by Portekoi** [comment]
Ca me semble bon

**Comment by AlainPierreSDPV** [comment]
pour la visite 736922 du 21/12/2015 c'est effectivement Ok mais toutes les visite suivantes reprennent  le calcul de l'alerte

**Comment by Portekoi** [comment]
Je ne vois pas `Vérifier Jeu des soupapes` dans les visites suivantes. Exemple  : 
![image](https://user-images.githubusercontent.com/1560754/32162945-ea7fa1ac-bd5a-11e7-9f87-92665ebfc008.png)

**Comment by AlainPierreSDPV** [comment]
Tu as raison j'ai pas regardé les opérations du profil j'ai juste constaté qu'il y avait des alertes calculées pour toutes les opérations.
Il me semble que précédemment lorsque une opération n'était plus reprogrammée elle apparaissait quand même dans le profil avec la date de la dernière intervention et sans nouvelle alerte... a voir avec @MamboJoel

**Comment by Portekoi** [comment]
Ca ne me dit rien. Le patch n'est pas encore livré. Il est sur la version `SSO`

**Comment by MamboJoel** [comment]
Elle est en ligne maintenant.

**Comment by AlainPierreSDPV** [comment]
c'est ok je clos cette issue
