### ISSUE TITLE
Basculement de 5  marchés DIR au 6 Novembre

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#207]
-DIR MASSIF CENTRAL (ID=7303)  à basculer complètement sous LOMATIC (FAURIE) (ID=2540)
- DIR NORD OUEST (ID=9050) à basculer complètement sous LOCAVI (COQUIDÉ) (ID=347)
- DIR CENTRE EST ( ID=8207) à basculer complètement sous UGAP - LOCATRANS (BERNARD) (ID=16957)
- DIR SUD OUEST ( ID=8883) à basculer complètement sous GROUPE MARTY (ID=420)
- DIR CENTRE OUEST ( ID=9200) à basculer complètement sous BERNIS FLEET SERVICE ( ID=261)
évidemment avec leur enfants 
Ces basculements prennent effet le lundi 06 Novembre à 8h00. 
Il faudrait donc les réaliser vendredi en fin de journée dans FleetOne
Conserver la double arborescence avec SDPV GRANDS COMPTES. avec comme parent ID  DIT ( ID=7330)

**Comment by Portekoi** [comment]
Est il possible de le formaliser comme dans cette issue ou ce n'est peut être pas le même type de basculement ?
https://github.com/groupe-gac/FleetOne/issues/196

**Comment by AlainPierreSDPV** [comment]
c'est effectivement le même genre de basculement que l'issue 196

**Comment by AlainPierreSDPV** [comment]
@Portekoi  à la demande de Yves MADEC pourrais tu basculer la DIR ci-dessous ce soir vers 17h ?

DIR NORD OUEST (ID=9050) à basculer complètement sous LOCAVI (COQUIDÉ) (ID=347)

**Comment by Portekoi** [comment]
Est-ce que ceci est correct?

id client : 9050 (DIR NORD OUEST)
Id parent côté SDPV : 7330 (DIT)
Id parent côté FRANCHISE : 347( LOCAVI (COQUIDÉ))

**Comment by AlainPierreSDPV** [comment]
Oui cela me semble correct je ne suis pas devant écran je ctrl cet apm

Envoyé de mon iPhone

Le 31 oct. 2017 à 11:05, "Portekoi" <notifications@github.com<mailto:notifications@github.com>> a écrit :


Est-ce que ceci est correct?

id client : 9050 (DIR NORD OUEST)
Id parent côté SDPV : 7330 (DIT)
Id parent côté FRANCHISE : 347( LOCAVI (COQUIDÉ))

**Comment by Portekoi** [comment]
Est-ce que tu peux juste me confirmer que c'est bon?

**Comment by AlainPierreSDPV** [comment]
Non 
c'est Ok pour 
id client : 9050 (DIR NORD OUEST) Id parent côté SDPV : 7330 (DIT)
mais il n'est pas visible coté  LOCAVI

**Comment by Portekoi** [comment]
Non j'ai rien fait encore. Je voulais juste être sur que ceci était bon : 

```
id client : 9050 (DIR NORD OUEST) Id parent côté SDPV : 7330 (DIT) Id parent côté FRANCHISE : 347( LOCAVI (COQUIDÉ))
```

**Comment by AlainPierreSDPV** [comment]
Oui c'est correct

**Comment by Portekoi** [comment]
C'est fait pour celui-ci.

**Comment by AlainPierreSDPV** [comment]
c'est top merci Damien

**Comment by Portekoi** [comment]
Je ferai donc les autres vendredi dans la soirée.

**Comment by YvesMadec** [comment]
Nickel !
Les autres DIR pour vendredi soir en effet
Merci !
Cordialement,

Yves MADEC

[cid:image001.png@01D35270.BA8A0AA0]



Directeur Grands Comptes

Tél: 06 30 56 53 90

Fax : 04 72 13 90 27

Email : yves.madec@force-reseau.com NOUVEAU !


Adresse : 20 Bd Eugène Deruelle - Le Britannia – Bât C –  69432 LYON Cedex 03

[cid:image002.png@01D35270.BA8A0AA0]

www.force-reseau.com<http://www.force-reseau.com/> – Découvrez vite notre nouveau site !

[Bannière signature FR GP vdef (2)]


De : Portekoi [mailto:notifications@github.com]
Envoyé : mardi 31 octobre 2017 17:46
À : groupe-gac/FleetOne
Cc : Yves Madec; Assign
Objet : Re: [groupe-gac/FleetOne] Basculement de 5 marchés DIR au 6 Novembre (#207)


Je ferai donc les autres vendredi dans la soirée.

**Comment by Portekoi** [comment]
Si je résumé les autres : 

```
id client : 8207 (DIR CENTRE EST ) 
Id parent côté SDPV : 7330 (DIT) 
Id parent côté FRANCHISE : 16957 (UGAP - LOCATRANS (BERNARD))

id client : 8883 (DIR SUD OUEST) 
Id parent côté SDPV : 7330 (DIT) 
Id parent côté FRANCHISE : 420( GROUPE MARTY)

id client : 9200 (DIR CENTRE OUEST) 
Id parent côté SDPV : 7330 (DIT) 
Id parent côté FRANCHISE : 261(BERNIS FLEET SERVICE)
```

Est-ce que cela vous semble bon?

**Comment by YvesMadec** [comment]
Bonjour,
Pour moi il manque la DIR MC (Massif Central) à basculer sur le groupe Faurie.
Cordialement,

Yves MADEC

[cid:image001.png@01D354A5.344E7390]



Directeur Grands Comptes

Tél: 06 30 56 53 90

Fax : 04 72 13 90 27

Email : yves.madec@force-reseau.com NOUVEAU !


Adresse : 20 Bd Eugène Deruelle - Le Britannia – Bât C –  69432 LYON Cedex 03

[cid:image002.png@01D354A5.344E7390]

www.force-reseau.com<http://www.force-reseau.com/> – Découvrez vite notre nouveau site !

[Bannière signature FR GP vdef (2)]

De : Portekoi [mailto:notifications@github.com]
Envoyé : vendredi 3 novembre 2017 10:59
À : groupe-gac/FleetOne
Cc : Yves Madec; Assign
Objet : Re: [groupe-gac/FleetOne] Basculement de 5 marchés DIR au 6 Novembre (#207)


Si je résumé les autres :

id client : 8207 (DIR CENTRE EST )

Id parent côté SDPV : 7330 (DIT)

Id parent côté FRANCHISE : 16957 (UGAP - LOCATRANS (BERNARD))



id client : 8883 (DIR SUD OUEST)

Id parent côté SDPV : 7330 (DIT)

Id parent côté FRANCHISE : 420( GROUPE MARTY)



id client : 9200 (DIR CENTRE OUEST)

Id parent côté SDPV : 7330 (DIT)

Id parent côté FRANCHISE : 261(BERNIS FLEET SERVICE)

Est-ce que cela vous semble bon?

**Comment by AlainPierreSDPV** [comment]
Oui c'est bon mais il ma,que la 5ieme DIR à basculer

id client : 7303  (DIR MASSIF CENTRAL)
 Id parent côté SDPV : 7330 (DIT)
 Id parent côté FRANCHISE : 2540 (LOMATIC FAURIE)

**Comment by Portekoi** [comment]
Effectivement, je l'avais pas vu au dessus. Je m'en occupe ce soir.

**Comment by Portekoi** [comment]
```
id client : 8207 (DIR CENTRE EST ) 
Id parent côté SDPV : 7330 (DIT) 
Id parent côté FRANCHISE : 16957 (UGAP - LOCATRANS (BERNARD))

id client : 8883 (DIR SUD OUEST) 
Id parent côté SDPV : 7330 (DIT) 
Id parent côté FRANCHISE : 420( GROUPE MARTY)

id client : 9200 (DIR CENTRE OUEST) 
Id parent côté SDPV : 7330 (DIT) 
Id parent côté FRANCHISE : 261(BERNIS FLEET SERVICE)

id client : 7303 (DIR MASSIF CENTRAL)
Id parent côté SDPV : 7330 (DIT)
Id parent côté FRANCHISE : 2540 (LOMATIC FAURIE)
```

**Comment by Portekoi** [comment]
Table sauvegardée sous `Customer_20171103D`. Je viens de faire le nécessaire.

**Comment by Portekoi** [comment]
Pas de retour donc je pense qu'on est bon. Je clos
