### ISSUE TITLE
UGAP : Mise à jour des tarifs de gestion parc - Accord cadre n° 770516

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#208]
@MamboJoel,

Nous venons d'avoir une mise à jour des tarifs des prestations de gestion de parc pour le mois de novembre 2017 (Uniquement pour l'accord cadre n° 770516).

Tu trouveras en pièce jointe la nouvelle table de tarification.

[Tarif gestion UGAP 770516 - 102017.xlsx](https://github.com/groupe-gac/FleetOne/files/1446002/Tarif.gestion.UGAP.770516.-.102017.xlsx)

Il faut que la mise à jour soit effectuée avant le 07/11/2017

Nous avons déjà effectué cette opération l'année dernière : #51 
Attention nous avions eu un bug sur le véhicules DOM TOM : #79 

Merci

**Comment by MamboJoel** [comment]
C'est OK Cyril. Tu peux vérifier/clore ?

**Comment by Portekoi** [comment]
@MamboJoel Quelle est la procédure? (Tu peux me l'envoyer par mail si tu veux)

**Comment by PIEGAY** [comment]
Pour les paramétrages hors DOM TOM s'est bon. 

En revanche, les clients "DOMTOM" sont devenus en tarification classique.
Client DOMTOM :
- GSBDD LA REUNION MAYOTTE
- GSBDD GUYANE
- GSBDD ANTILLES
Exemple : le véhicule EQ-138-WL doit être facturé 44 € au lieu de 24.89 €

Idem #79

**Comment by PIEGAY** [comment]
Le problème pour les DOM TOM (Voir ci-dessus) est toujours existant et je dois facturer. 
Merci d'avance

**Comment by PIEGAY** [comment]
J'ai toujours le problème pour les clients DOM TOM.
Identique à l'issue #79 

J'ai vraiment besoin de facturer on est le 17 du mois et je bloque une facturation de 30 000 € HT... 
Je vais me faire découper en 2 par Nathalie...

**Comment by MamboJoel** [comment]
Je suis dessus.

**Comment by MamboJoel** [comment]
Ce devrait être bon.

**Comment by PIEGAY** [comment]
Ok c'est bon
Merci
