### ISSUE TITLE
UGAP - Double arborescence (Nouveau client)

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#210]
@Portekoi 

Ci-dessous un nouveau client UGAP en gestion chez notre franchisé AZUR TRUCKS. 
Par conséquent, il faut me réaliser les doubles arborescences suivantes :

CC PRO : 

id client : 17190 (CC PRO)
Id parent côté SDPV : 7604 (COMMUNAUTES DE COMS)
Id parent côté FRANCHISE : 13867 (MARCHE UGAP)

Merci !

**Comment by Portekoi** [comment]
C'est pour quand? ASAP?

**Comment by Portekoi** [comment]
@PIEGAY Je vais devoir m'absenter. Peux tu me confirmer que je peux le faire dès maintenant? Ou ce soir, comme tu veux.

**Comment by PIEGAY** [comment]
tu peux le faire dès maintenant
merci

**Comment by Portekoi** [comment]
C'est fait.
