### ISSUE TITLE
mise à jour table de croisement Fleet Rentcar pour berthier

### ISSUE THREAD

**Issue by A-PIERRE** [groupe-gac/FleetOne#214]
Merci de mettre à jour la table de croisement qui annule et remplace pour berthier seulement
companyid = 5402
[BERTHIER _RENTCAR.xls.xlsx](https://github.com/groupe-gac/FleetOne/files/1514306/BERTHIER._RENTCAR.xls.xlsx)

**Comment by MamboJoel** [comment]
OK !

**Comment by AlainPierreSDPV** [comment]
Il y avait une erreur dans la table pour l'opération 80 la compagny était 5403 au lieu de 5402
nouvelle table 
[BERTHIER _RENTCAR.xls.xlsx](https://github.com/groupe-gac/FleetOne/files/1521411/BERTHIER._RENTCAR.xls.xlsx)

**Comment by Portekoi** [comment]
Je sais pas où cela met à jour. @MamboJoel Si tu me dis, je le fais :)

**Comment by MamboJoel** [comment]
Oui si tu peux ! Merci !

**Comment by MamboJoel** [comment]
C'est la table `codification`. Si l'erreur est clairement exposée dans le xls tu peux rentrer direct dans la table et le faire à la main, c'est plus simple que de refaire toute une importation.

**Comment by MamboJoel** [comment]
Mais je crains que ce ne soit pas le cas : il faut tout recommencer à zéro. Voici [un script pour t'aider](https://github.com/ntlm-technologies/ntlm-sql-tools/blob/master/SDPV%20Codification%20RentCar%20Berthier.sql).

**Comment by Portekoi** [comment]
OK je regarde

**Comment by Portekoi** [comment]
Ok j'ai édité dans la table directement.

**Comment by MamboJoel** [comment]
Cool.
