### ISSUE TITLE
récuperer des id de fournisseur qui ne sont plus visibles

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#218]
Nicolas je dois donner une table au groupe Berthier des fournisseurs utilisés par Ets Clovis avec le siret et l'id fleet. cela servira à la création d'une table de croisement dans Rentcar pour récupérer les factures de Fleet
[recup id fournisseurs.xlsx](https://github.com/groupe-gac/FleetOne/files/1555620/recup.id.fournisseurs.xlsx)
.
Je sais le faire à partir du reporting financier mais certains des fournisseurs utilisés ne sont plus accessibles et je n'ai aucun moyen de récupérer leur Id.
Peux tu me remplir la colonne Id à partir des visites pour ces 11 fournisseurs ?
Je dois donner cette table d'ici ce soir merci pour ton aide

**Comment by MamboJoel** [comment]
Voilà !
[Fournisseurs pour Berthier.zip](https://github.com/groupe-gac/FleetOne/files/1555796/Fournisseurs.pour.Berthier.zip)
