### ISSUE TITLE
Modificaton arborescence SOCREC

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#24]
Dans le fichier excel joint il y a 2 onglets 
le premier "DÉPLACER" donne les information des clients qui sont à rattacher au membre SOCREC
Le deuxième "SUPPRIMER" donne les informations des membres à supprimer
Des clients existent chez ces membres ils sont également à supprimer avec leur parc
[MODIF ARBO.xlsx](https://github.com/groupe-gac/FleetOne/files/558734/MODIF.ARBO.xlsx)
ci dessous la demande de Nicolas Lenormant
-   Basculer le parc gérer sous « CREIL » vers « SOCREC » en gardant comme référence client « véhicule de service SOCREC ».
-   Basculer de la même façon « Creil CD » vers « SOCREC » en laissant comme nom client « Creil CD »   (attention il existe un parc « SMELVI Creil CD » qui doit rester inchangé).
-   Supprimer les parcs « Garges-lès-Gonesse » et « Plessis Belleville » et « AFT Atelier Mobile » dont nous n’avons pas/plus l’utilité

**Comment by MamboJoel** [comment]
C'est un peu plus délicat que l'autre. 
Tu peux regarder. Et fermer cette entrée si c'est ok.

**Comment by AlainPierreSDPV** [comment]
pour moi c'est Ok j'infore Guillaume pour qu'il contrôle aussi
