### ISSUE TITLE
Impossible d'ajouter une opération

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#27]
http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.867&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=52174&AlertID=&VisitID=816508&MemberTab=Supplier&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=61630240&Display=&tab=Visits&ClientTab=Users&VehicleTab=Equipment-56251&EquipmentID=56251&VehicleTS=1477053753325&MessageID=&VisitReference=&FromDate=01/04/2014&ToDate=31/12/2016&VisitProcess=15&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=28/10/2016

Impossible d'ajouter une nouvelle opération : 

![image](https://cloud.githubusercontent.com/assets/22617815/19967396/57dcd802-a1d0-11e6-95ea-415c32ada530.png)

**Comment by MamboJoel** [comment]
Et tu disais qu'il y avait un autre bug ? qu'on pouvait pas accéder à certains véhicules ?

**Comment by MamboJoel** [comment]
Réglé aussi.
