### ISSUE TITLE
Impossible d'accéder au véhicule BH-799-PR

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#28]
Avec un login "Gestionnaire de parc", impossible de rentrer dans le véhicule BH-799-PR

**Comment by MamboJoel** [comment]
Le lien :

http://f2.sdpv.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=m.15204&VisitProcess=20&VehicleID=47709&AlertID=&VisitID=&FromDate=01/01/2016&ToDate=31/12/2016&Display=&tab=Visits&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=BH-799-PR&VisitReference=811298&VehicleTab=Equipment-64058&EquipmentID=64058&ClientTab=Vehicles&MemberTab=Profiles&VehicleTS=1477039499208&MessageID=&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=

**Comment by MamboJoel** [comment]
Ce problème est réglé.
