### ISSUE TITLE
Impossible d'affecter un profil à un équipement

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#29]
http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=c.15400&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=52575&AlertID=&VisitID=&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=dd475&ClientTab=Vehicles&Display=&tab=Edit&VehicleTab=Equipment-64327&EquipmentID=64327&MemberTab=Profiles&ProfileCategories=1,291,284&categoryID=284&articleID=

**Comment by MamboJoel** [comment]
Alain, n'oublie pas d'affecter au Milestone.

**Comment by MamboJoel** [comment]
Damien, il manque la méthode Tree_json au controller Profile.

**Comment by Portekoi** [comment]
Corrigé et commité.

**Comment by MamboJoel** [comment]
Merci.
Alain j'ai testé en local et publié le correctif. Tu peux fermer cette entrée.
Damien, nous placerons les issues github relatif au projet de profile sous la [milestone 1](https://github.com/groupe-gac/FleetOne/milestone/1)
