### ISSUE TITLE
Rendre non modifiable les profils créés par l'adminsytéme

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#30]
http://f2.sdpv.com/mj/#url=/Member/Index/&CompanyID=m.5402&HasAlert=true&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=&AlertID=&VisitID=&ClientTab=Vehicles&Display=&tab=Edit&VehicleTab=Equipment-64327&EquipmentID=64327&MemberTab=Profiles&ProfileCategories=1,291,284,288,292,7,8,376&categoryID=376&articleID=

**Comment by MamboJoel** [comment]
Malheureusement Alain les liens des profils ne pointent pas directement vers les profils, mais vers la page générale des profils. Tu peux me désigner un profil que tu considères "Système", je ne me souviens plus de la manière dont ils sont paramétrés.

"Visite Régl SREM & REM" par exemple ?

**Comment by MamboJoel** [comment]
Que l'on trouve dans : Profils > Remorques et Semi Remorques > Gestion visite réglementaire

**Comment by AlainPierreSDPV** [comment]
le profil "Visite Régl SREM & REM"  profilID = 684 est effectivement un profil "systéme"  accessible pour tous les membres non modifiable mais duplicaple et donc la copie modifiable par le membre.
Dans V1 les profils créés par le membre sont identifiables lors de l'affectation à un équipement .Le libellé du profil en en Bleu /gras/italique 
Dans V2 ils étaient entre crochet { xxxxxxxxx}

**Comment by AlainPierreSDPV** [comment]
le profil "Visite Régl SREM & REM"  profilID = 684 est effectivement un profil "systéme"  accessible pour tous les membres non modifiable mais duplicaple et donc la copie modifiable par le membre.
Dans V1 les profils créés par le membre sont identifiables lors de l'affectation à un équipement .Le libellé du profil en en Bleu /gras/italique 
Dans V2 ils étaient entre crochet { xxxxxxxxx}

**Comment by Portekoi** [comment]
@MamboJoel Tu m'as créé la méthode "CanWrite()" qui m'indique si la personne est admin ou non.

Mais comment voir si la personne peut modifier le profil? Si je regarde v1 : 
`If Rs("MemberID") & "" = MemberID & "" Then IsPersonalized = True Else IsPersonalized = False`

Si le profil a été créé par la même personne, alors il peut le modifier. J'applique la même règle?

**Comment by AlainPierreSDPV** [comment]
Les profils créés par un membre qui sont identifiables d’après ce que je comprends dans l'application  par IsPersonalized = True  doivent pouvoir être modifiables par toutes les personnes qui ont le rôle "admin" chez ce membre mais il ne doivent pas pouvoir modifier les profils créés par les adminsystéme c'est à dire actuellement par moi et cyril.

**Comment by AlainPierreSDPV** [comment]
pour être plus précis
Chez le membre Fleet trucks 69 (qui sert pour les tests) id member = 499 
à titre d'exemple il y a un profil au niveau:  Profils > Véhicules Moteur > Niv2= Niv1 + suivi Ent de Base (NIV2) > Inter-Urbain 
un profil  "Kerax - Arret 30000 Km" id = 2113 qui a été créé chez ce membre par duplication d'un profil dit systéme 
ce profil ne se retrouve pas dans V2.  il doit pouvoir être modifiable par les personnes ayant le rôle "admin" chez ce franchisé.

par contre le profil "GH - Arret 30000 Km"  id=521  qui est un profil systéme créé par moi  "adminsystéme" il  est actuellement modifiable par les personnes qui ont le rôle "admin" chez ce membre . cela ne doit pas être possible.

**Comment by Portekoi** [comment]
Merci pour ces précisions.
@MamboJoel Au début, tu m'avais dit de prendre les memberID à Null. Sauf que pour les cas cités par Alain, le 2113 possède un memberID (499) mais pas le 521. (qui est bien NULL)

Donc les profils systèmes sont en memberID= null et les profils "membre", l'inverse. Je vais devoir réorienter mon dev en ce sens. Dis moi si je me trompe.

**Comment by Portekoi** [comment]
@MamboJoel On s'appelle demain pour que je comprenne mieux les Member et Company...

**Comment by AlainPierreSDPV** [comment]
Nous avons Jeudi une réunion des gestionnaires de parc, ce serait le moment idéal pour leur montrer la gestion des profils dans V2 sous condition qu'ils retrouvent leurs profils en plus des profils "système"
est ce possible ?

**Comment by MamboJoel** [comment]
Malheureusement je ne pourrai pas me rendre à Lyon jeudi car j'ai un impératif le matin. En revanche je serai disponible au téléphone l'après-midi.

Tâchons, avec Damien ( @Portekoi ) de rendre le projet présentable.

Alain, tu dis donc, que les profils appartenant aux membres ne sont pas visibles dans l'arborescence ? Peux-tu me désigner par son nom ou email un user ainsi qu'un breadcrumb menant à un de ses profils personnalisé afin que l'on reproduise l'anomalie ?

**Comment by AlainPierreSDPV** [comment]
les informations  données plus haut ne suffisent pas ?
```
"pour être plus précis
Chez le membre Fleet trucks 69 .............
```

**Comment by MamboJoel** [comment]
Ah pardon, j'avais oublié ce pavé. @Portekoi  ça te suffit ?

**Comment by Portekoi** [comment]
Corrigé et comité. A livrer et voir pour l'issu CanWrite :
 https://github.com/groupe-gac/FleetOne/issues/44

**Comment by MamboJoel** [comment]
J'ai publié.

**Comment by AlainPierreSDPV** [comment]
Les profils publics et créés par le membre sont maintenant visibles
Les profils publics sont modifiables et ils ne doivent pas pouvoir être modifiés par le membre 
pour reproduire 
Login  dominique.charlet@renault-trucks.net    PW :  Domi62840
Profils > Véhicules Moteur > Niv1 = Gest Réglementaire   profil id=403 
constater qu'il est modifiable au niveau de la description du profil

Autre anomalie au niveau de la modification d'une opération du profil
exemple profil id 2791 Descamps Hydro RTMD/ADR c'est un profil créé par le membre nous avons une erreur si l'on souhaite modifier cette opération
Message d'erreur du compilateur: CS0117: 'ASP.Helpers' ne contient pas de définition pour 'ScriptsPopUp'

**Comment by MamboJoel** [comment]
Je créé une entrée spécifique pour l'autre anomalie.

**Comment by MamboJoel** [comment]
C'est corrigé.
