### ISSUE TITLE
Ajout de nouvelles marques dans le catalogue FleetOne

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#31]
Merci d'ajouter les marques suivantes au catalogue dans FleetOne : 
TOPY
HAULOTTE
HABRIAL
MANUTAN
FINATEC
CARIPDRAULIC
GESUTRA
LIFTER
PALFINGER
KALMAR
FAUN
SEMAT
FANTUZZI

![image](https://cloud.githubusercontent.com/assets/22617815/19974897/5d6f10f4-a1ea-11e6-97c6-7eaaa812a671.png)

**Comment by MamboJoel** [comment]
C'est ok Cyril.
