### ISSUE TITLE
le parametre des alertes réglementaires est le mois et non l'heure

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#32]
Exemple ci-dessous

http://f2.sdpv.com/mj/#url=/Member/Index/&CompanyID=m.286&HasAlert=true&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=182&AlertID=&VisitID=&MemberTab=Profiles&ProfileCategories=1,291,284,287&categoryID=288&articleID=&Display=&tab=Edit&VehicleTab=Equipment-262&EquipmentID=262

**Comment by AlainPierreSDPV** [comment]
je n'ouvre pas une nouvelle Issue mais le paramètre déclencheur pour les opérations gérées au kilomètres sont au mois dans cette nouvelle version. Je pense que la correction de cette anomalie est de même nature

**Comment by MamboJoel** [comment]
Oui, j'attire l'attention de Damien là-dessus. @Portekoi

**Comment by MamboJoel** [comment]
Alain,

Les lies que tu nous donnes ne permettent pas d'aller directement sur la page de profil que tu désignes. Ils mènent vers la page générale. Pour nous aider il vaut mieux que tu copies-colles le breadcrumb situé en haut du profil. Par exemple :

`Profils > Remorques et Semi Remorques > Gestion visite réglementaire > Visite Régl SREM & REM (684)`

Cela étant, nous ne comprenons pas ta demande. Lorsque tu paramètres une opération tu peux choisir l'unité. Que l'opération soit réglementaire ou non.

**Comment by AlainPierreSDPV** [comment]
Ok pour les liens, Pour constater l'anomalie il faut aller dans la gestion des profils dans V2
exemple
Profils > Véhicules Moteur > Niv2= Niv1 + suivi Ent de Base > Approche Chantier > Gamme G & R - P BOM - Arret 15000 Km (643)
cliquer sur modifier l'opération "Contrôle Technique PL" et constater que dans ce profil l'opération est dite gérée en Heure alors que c'est au mois qu'elle est gérée dans V1
de même constater que l'opération "Station" est gérée en mois en non en Kilomètres
le transfert de la gestion des profils n'a pas respecter les unités de gestion des alertes connues de V1

**Comment by MamboJoel** [comment]
Merci Alain pour ces précision. J'ai localisé le problème. Je vois avec Damien.

**Comment by MamboJoel** [comment]
J'ai corrigé. Damien j'attire ton attention sur le correctif.
https://github.com/ntlm-technologies/sdpv-fleet-mvc/commit/3bcf81b23d88490d78e4559cf9c29e153c5a57d0

**Comment by AlainPierreSDPV** [comment]
Je n'ai plus accès à l'arborescence des profils

**Comment by MamboJoel** [comment]
Il faut que tu vides le cache. F5, ou mieux, ctrl + maj + supp

**Comment by Portekoi** [comment]
Pour le ctrl + maj + supp , juste cocher "cache". Parfois, passer en navigation privée 'ctrl + maj + N' sous chrome permet de ne pas utiliser le cache.

**Comment by AlainPierreSDPV** [comment]
Je me suis mal exprimé. j'ai accès à l'arborescence jusqu'au au niveau le plus bas mais pas un profil ne s'affiche et nous avons comme information  "Une erreur est survenue"
