### ISSUE TITLE
affichage des profils

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#33]
la colonne "code" n'est pas utilisé dans l'application  par contre la "Sévérité" et  pertinente pour faire le choix du profil

**Comment by MamboJoel** [comment]
Alors on supprimer "code" ?

**Comment by AlainPierreSDPV** [comment]
oui à la place de "code" on met "Sévérité"

**Comment by AlainPierreSDPV** [comment]
Si la question est:  peut on supprimer le champ "code" dans la base ? c'est également oui ; ce champ est quasiment à Null pour tous les profils et n'est pas utilisé.

**Comment by AlainPierreSDPV** [comment]
J’accède à l'arborescence mais les profils ne s'affichent plus  J'ai "veuillez patienter..."

**Comment by AlainPierreSDPV** [comment]
précision:   j'ai utiliser Google chrome en mode "fenêtre privée"

**Comment by Portekoi** [comment]
@MamboJoel Il y a eut régression : 
category_id=285&action=%2FProfileCategory%2FGetListeprofiles

Au lieu de 
categoryID=285&action=%2FProfileCategory%2FGetListeprofiles

Vue : à relivrer : \Views\ProfileCategory\Index.cshtml

**Comment by MamboJoel** [comment]
C'est ok.
Alain, pour la clarté je recommande, à l'aspect d'un nouveau problème, d'ouvrir une issue spécifiquement pour le problème.
