### ISSUE TITLE
la fonction "ajouter une opération"  ne fonctionne pas

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#34]
exemple sur ce profil
http://f2.sdpv.com/mj/#url=/Member/Index/&CompanyID=m.286&HasAlert=true&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=182&AlertID=&VisitID=&MemberTab=Profiles&ProfileCategories=1,291,284&categoryID=287&articleID=&Display=&tab=Edit&VehicleTab=Equipment-262&EquipmentID=262

**Comment by MamboJoel** [comment]
C'est bon Alain.
