### ISSUE TITLE
Urgent : Problème mise à jour alerte "Contrôle limiteur" (Ex : CY-934-RJ) 

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#39]
Nous avons un problème avec la non mise à jour de l'alerte limiteur de vitesse sur plusieurs véhicules alors que celui ci a bien été réalisé. 

Ex : CY-934-RJ
http://f2.sdpv.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=c.9200&VisitProcess=20&VehicleID=36984&AlertID=&VisitID=&FromDate=01/01/2016&ToDate=31/12/2016&Display=&tab=Visits&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=CY934RJ&VisitReference=&VehicleTab=Equipment-49449&EquipmentID=49449&ClientTab=Users&MemberTab=Users&VehicleTS=1478511074019&MessageID=&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&ProfileCategories=1,291,284,315,283,50,54,51,52,288,289,290&categoryID=290&articleID=

![image](https://cloud.githubusercontent.com/assets/22617815/20054062/86dbffa8-a4db-11e6-81e8-1c8c6aee59da.png)

**Comment by MamboJoel** [comment]
Je suis en voiture. Je regarde dès que je suis à l'arrêt.

**Comment by AlainPierreSDPV** [comment]
J'ai juste resauvegarder la visite et l'alerte a été recalculée correctement .....

**Comment by PIEGAY** [comment]
Le problème est plus large que cette visite car j'ai eu deux cas ce matin

**Comment by PIEGAY** [comment]
Je trouve une autre visite pour reproduire

**Comment by MamboJoel** [comment]
Oui ce serait bien une autre visite dans ce cas. 
Je me demande si le problème n'est pas lié à #19

**Comment by PIEGAY** [comment]
J'ai trouvé une autre visite avec le limiteur en alerte alors que la visite est "réalisée" : 

http://f2.sdpv.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=c.9453&VisitProcess=20&VehicleID=40147&AlertID=&VisitID=819050&FromDate=01/01/2016&ToDate=31/12/2016&Display=&tab=Visits&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=60110841&VisitReference=816126&VehicleTab=Equipment-63713&EquipmentID=63713&ClientTab=Users&MemberTab=Users&VehicleTS=1479454201804&MessageID=&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&ProfileCategories=1,291,284,315,283,50,54,51,52,288,289,290&categoryID=290&articleID=

**Ne pas faire "sauvegarder" car la visite se mettre à jour.**

**Comment by MamboJoel** [comment]
Je travaille sur ce cas. Merci de ne pas faire "sauvegarder" en effet.

**Comment by MamboJoel** [comment]
J'ai trouvé Cyril.
Il y a eu deux publications concernant les réglementaires non CT, une "Reg" :

- Le 21 octobre on a retiré date et résultat du contrôle.
- Le 26 octobre on a remis cette date et fondé le calcul des alertes sur le résultat du contrôle.

Donc :

**Avant le 21 octobre**
Sauvegarder une visite ayant une Reg repoussait l'alerte dans le temps, que le contrôle soit positif ou non.

**Entre le 21 et le 26 octobre**
Sauvegarder une visite ayant une Reg n'enregistrait pas de résultat et de date de contrôle. L'alerte était donc figée sur la date de la visite.

**Depuis le 26 octobre**
- Sauvegarder une visite **ayant une Reg** enregistre le résultat et la date de contrôle. L'alerte est donc bien repoussée selon le résultat.
- Sauvegarder une visite **n'ayant pas une Reg** n'enregistre pas de résultat et de date de contrôle (car l'opération n'est pas cochée). L'alerte n'est donc pas repoussée comme voulue.

C'est pourquoi tes GP en cliquant Sauvegarder repoussait la date. En revanche la dernière visite du véhicule 60110841 ne contient pas de Reg, donc cliquer Sauvegarder n'enregistre pas de date ou de résultat et l'alerte n'est pas recalculée.

**Comment by MamboJoel** [comment]
**Patch :**

- Pour toutes les interventions Reg posant problème j'ai passé le résultat à "ok" et fixé la date réglementaire à la date de la vsite.

- J'ai écrit et lancé une routine qui recalcule les alertes pour les véhicules en question. Elle vient de se terminer avec succès.

- J'ai quand même prise l'initiative de passer les résultats à OK. Mais vu que le cas d'un résultat négatif n'est apparu que lors de la #19 , j'ai estimé que c'était acceptable. Vous pouvez effectuer un contrôle sur 
[la liste des véhicules que j'ai traités](https://github.com/groupe-gac/FleetOne/files/600501/Fleet.-.Vehicules.concernes.par.l.entree.39.xlsx).
