### ISSUE TITLE
Impossible de se connecter à FleetOne f2.sdpv.com

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#41]
Lors de la connexion à FleetOne, nous avons l'erreur suivante : Le journal des transactions de la base de données 'Fleet' est plein. Pour savoir pourquoi il est impossible de réutiliser de l'espace dans le journal, consultez la colonne log_reuse_wait_desc dans sys.databases. 

Impossible de se connecter... Je ne peux pas organiser mon dépannage 24/7

![image](https://cloud.githubusercontent.com/assets/22617815/20215813/43ce843a-a817-11e6-8e49-bccb965d003b.png)

**Comment by MamboJoel** [comment]
C'est corrigé.

**Comment by PIEGAY** [comment]
Un grand merci pour ton intervention rapide !!!
