### ISSUE TITLE
CanWrite toujours true

### ISSUE THREAD

**Issue by Portekoi** [groupe-gac/FleetOne#44]
Voir méthode CanWrite() de Profile qui renvoie toujours True.
Pour contrôler : si un administrateur de parc se connecte, il doit voir 13 lignes dans le "Profils > Véhicules Moteur > Niv2= Niv1 + suivi Ent de Base (NIV2) > Inter-Urbain" dont certains SANS les boutons "Modifier" / "Déplacer" / "Supprimer"

**Comment by MamboJoel** [comment]
Pour reproduire l'anomalie il me faudrait :
- Un ProfileID
- Un UserID (de l'utilisateur qui consulte un profil et doit avoir CanWrite = False)
Merci !

**Comment by Portekoi** [comment]
la ProfileCategoryID =288 et le member ID = 499

Dans la liste des profils, tu as par exemple le 622 qui est un profil système et le 2113 qui est un profil modifiable.
Je dois me sauve en réu là. Je serai pas de retour avant ce soir.

**Comment by MamboJoel** [comment]
Il me faut le UserID.

**Comment by MamboJoel** [comment]
Celui avec lequel tu te connectes. Car c'est lui contre qui l'on teste "CanWrite"
