### ISSUE TITLE
Entête et pied des listings de profils.

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#46]
- Se loguer en tant que Gestionnaire de Parc.
- http://f2.sdpv.com/mj/#url=/Member/Index/&CompanyID=m.261&HasAlert=true&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=&AlertID=&VisitID=&MemberTab=Profiles

- Aller dans un listing de profil.

> Constater des entêtes et pied de table décalés (colspan).

**Comment by Portekoi** [comment]
C'est pas forcément un bogue même si c'est pas très joli. Dans la liste, il peut y avoir des profils appartenant au membre (donc il y aura tous les boutons d'action) et des profils systèmes bloqués en modification (donc avec moins de bouton). Les deux peuvent et sont d'ailleurs souvent affichés quand on choisi un grand compte.

**Comment by MamboJoel** [comment]
Ah c'est vrai. Je pense que tu ne devrais pas tester sur la cellule (td) mais sur le bouton (button) ainsi tu garderais une table avec à chaque ligne le même nombre de cellule ainsi que la décoration (bordures et fonds). Par ailleurs la dernière ligne devrait avoir colspan="7". Je te pinaille un peu tranquille sur la tronche.

**Comment by Portekoi** [comment]
Tu cherches un peu la licrone là mais tu as raison. Je corrigerais ça

**Comment by Portekoi** [comment]
Commité. A livrer après la réunion.

**Comment by Portekoi** [comment]
A confirmer mais pour moi, c'est corrigé.

**Comment by MamboJoel** [comment]
C'est clean.
