### ISSUE TITLE
Pas de mise à jour du profil suite à modification

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#48]
Prendre mon login et mon mot de passe pour reproduire
aller sur la visite ci-dessous

http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.261&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=41379&AlertID=&VisitID=&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=98630002&Display=&tab=Visits

constater qu'il n'y a que l'opération station alors que le profil contient 2 autres opérations
Vidange du pont(s) et Vidange BV

**Comment by Portekoi** [comment]
Le lien ne pointe pas vers un profil. Il faut me donner le nom du profil / catégorie pour que je puisse y accéder.

**Comment by AlainPierreSDPV** [comment]
Le profileID=9684  il semble être vide alors qu'il est présenté dans Fleet V2 avec 3 opérations

**Comment by MamboJoel** [comment]
Je reproduis l'anomalie.

Mais c'est le résultat souhaité. Il y a bien trois opération pour ProfileID=9684. Seulement deux semblent inverser km et mois. Notamment une programmée tous les 120000 mois. Dernièrement on a fixé une limite dans le temps (pas plus de 20 ans) car cela provoquait des erreurs.

Je vous invite à corriger le profil.

**Comment by AlainPierreSDPV** [comment]
On n’accède pas au paramétrage de ce profil qui est présenté comme ayant aucune opération dans 
Profils > Véhicules Moteur > Niv2= Niv1 + suivi Ent de Base > SIMMT TRACTEUR RENAULT R551S (9684)

**Comment by Portekoi** [comment]
Accéder au paramétrage? C'est à dire? Si je vais sur ce profile depuis ce lien :
http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.261&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=41379&AlertID=&VisitID=&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=98630002&Display=&tab=Visits

Je clique sur : SIMMT TRACTEUR RENAULT R551S

Et j'affiche le profil. Pour le modifier, cliquer à gauche sur sa catégorie pour lister les profils, le trouver dans la liste puis cliquer sur Modifier. 

Est ce bien cela @AlainPierreSDPV ? Si oui, je vais simplifier l'interface.

**Comment by AlainPierreSDPV** [comment]
l'interface est correct c'est en fait une anomalie de fonctionnement 
je devrais pouvoir acceder aux opérations de ce profil en modification  mais aucunes des 3 opérations n'est proposées.  Le profil semble être vide à l'affichage

**Comment by Portekoi** [comment]
Ce profil n'est contient pas : 
select * from fleet.dbo.profiledetail where profileid = 9684 
*0 ligne*
