### ISSUE TITLE
Pas d’accès en consultation des profils publics

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#49]
Profils > Véhicules Moteur > Niv1 = Gest Réglementaire 
Prendre le profil PL Suivi visites réglementaires cliquer sur consulter 
constater 

> `Vous ne pouvez pas consulter ce profil
`
les profils publics doivent être non modifiable mais duplicable et consultable par les membres

**Comment by AlainPierreSDPV** [comment]
La duplication est également impossible

**Comment by Portekoi** [comment]
Nico, tu peux livrer mes dernières modifs? Merci

**Comment by MamboJoel** [comment]
C'est publié.

**Comment by MamboJoel** [comment]
Ça corrige l'erreur @AlainPierreSDPV  ?

**Comment by Portekoi** [comment]
Corrigé dans le dernier commite
