### ISSUE TITLE
Consulter le profil depuis la visite Fleet

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#50]
depuis une visite:    exemple
http://f2.sdpv.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=c.13094&VisitProcess=20&VehicleID=52622&AlertID=&VisitID=&FromDate=01/01/2016&ToDate=31/12/2016&Display=&tab=Visits&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=CY934RJ&VisitReference=&VehicleTab=Equipment-49449&EquipmentID=49449&ClientTab=Users&MemberTab=Users&VehicleTS=1478511074019&MessageID=&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&ProfileCategories=1,291,284,315,283,50,54,51,52,288,289,290&categoryID=290&articleID=

pouvoir consulter le profil de ce véhicule
Profils > Validés par Clients Nationaux > Dubreu > UTILITAIRE (8112)

**Comment by MamboJoel** [comment]
@Portekoi est-ce que tu serais en mesure d'afficher le profile et la catégorie si je te passais leurs ID via le hash de l'url ?
Par exemple :
#url=/Member/Index/&CompanyID=m.867&HasAlert=true&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=&AlertID=&VisitID=&MemberTab=Profiles&**ProfileID=1**&**ProfileCategoryID=1**

**Comment by MamboJoel** [comment]
@Portekoi j'ai implémenté le lien vers les profils. Je l'ai commité.

Il s'agit que ta page soit en mesure de présenter la catégorie et le profil en réponse, par exemple, à :

mj/#url=/Member/Index/&CompanyID=m.867&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=41379&AlertID=&VisitID=0&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=98630002&Display=&tab=Visits&ProfileCategoryID=284&ProfileID=9684&MemberTab=Profiles

En javascript, pour accéder à ces variables tu peux utiliser :

``` javascript
$.nav.state.ProfileID
$.nav.state.CategoryID
```

**Comment by Portekoi** [comment]
Fait et Commité.

**Comment by MamboJoel** [comment]
C'est publié.
Ça nécessite certainement de secouer un peu le cache (F5 ou carrément le vider), mais c'est ok.
Je clos.
