### ISSUE TITLE
UGAP : Mise à jour des tarifs de gestion parc - Accord cadre n° 770516

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#51]
Nous venons d'avoir une mise à jour des tarifs des prestations de gestion de parc pour le mois de novembre 2016 (Uniquement pour l'accord cadre n° 770516).

Tu trouveras en pièce jointe la nouvelle table de tarification. 

[Tarif gestion de parc (Mise à jour 10-2016).xlsx](https://github.com/groupe-gac/FleetOne/files/599286/Tarif.gestion.de.parc.Mise.a.jour.10-2016.xlsx)

Il faut que la mise à jour soit effectuée **avant le 25/11/2016.**

Merci

**Comment by MamboJoel** [comment]
On l'a intégré.
