### ISSUE TITLE
Journal des transactions FleetOne

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#52]
http://f2.sdpv.com/Home/Navigate/#url=/Client/Index/&CompanyID=c.9453&VisitProcess=20&VehicleID=40147&AlertID=&VisitID=819050&FromDate=01/01/2016&ToDate=31/12/2016&Display=&tab=Visits&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=60110841&VisitReference=816126&VehicleTab=Equipment-63713&EquipmentID=63713&ClientTab=Users&MemberTab=Users&VehicleTS=1479454201804&MessageID=&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&ProfileCategories=1,291,284,315,283,50,54,51,52,288,289,290&categoryID=290&articleID=

![image](https://cloud.githubusercontent.com/assets/22617815/20423245/900ce06e-ad6f-11e6-9fdb-352d73b56dfd.png)

**Comment by MamboJoel** [comment]
C'est bon. Je travaille sur le problème. C'est un problème d'espace disque.
