### ISSUE TITLE
Reporting : problème dans l'onglet "Factures / Synthèse"

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#55]
Dans l'onglet Factures / Synthèse du reporting, les coûts s’arrêtent en février 2016 : 
http://rep.gestionparc.com/Ugap/GlobalCost.aspx 

![image](https://cloud.githubusercontent.com/assets/22617815/20488948/2b04cf28-b009-11e6-925f-9e9924ac715a.png)

Cette partie est visible du client

**Comment by AlainPierreSDPV** [comment]
pour reproduire

login: alexandre.beurdeley@intradef.gouv.fr
PW:  sea

**Comment by Portekoi** [comment]
J'ai l'impression que le problème a été corrigé depuis. Je vois bien tous les mois pour 2016

**Comment by AlainPierreSDPV** [comment]
Oui c'est corrigé
