### ISSUE TITLE
Profil FleetOne : Disparition de l'opération dans la visite

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#58]
Lorsqu'on modifie un paramètre d'une opération d'un profil dans V2, l'opération disparaît de la visite et des  alertes. 

Exemple : 
http://f2.sdpv.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=c.15438&VisitProcess=20&VehicleID=52425&AlertID=&VisitID=828058&FromDate=01/01/2016&ToDate=31/12/2016&Display=&tab=Visits&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=235BTE83&VisitReference=763451&VehicleTab=Equipment-64127&EquipmentID=64127&ClientTab=Info&MemberTab=Profiles&VehicleTS=1479823271705&MessageID=&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&ProfileCategories=1,291,284,315,283,50,54,51,52,288,289,290&categoryID=290&articleID=&ProfileCategoryID=288&ProfileID=9621&AlertFromDate=01/01/1900&AlertToDate=22/12/2016

Nous avons modifié le paramètre de prise en compte de l'opération "Ctrl pollution VU" et l'opération a disparue de la visite. 

or elle apparaît toujours dans la fiche véhicule mais sans date d'estimation : 

![image](https://cloud.githubusercontent.com/assets/22617815/20526761/ca5dadf8-b0c5-11e6-8d32-39b34a6943cb.png)

**Comment by MamboJoel** [comment]
On ne reproduit pas l'anomalie.

Lorsque l'on modifie une programmation l'alerte ne disparaît pas du planning.

**Comment by MamboJoel** [comment]
Pour reproduire :

- Modifier la date de prise en compte de la programmation.
-> Constater que l'opération disparaît du planning.

**Comment by MamboJoel** [comment]
@Portekoi  j'ai corrigé l'anomalie.
C'est de ma faute, je t'ai pas précisé la gestion de la ProfileProgrammation.ToValue. Sur les écrans on affiche "0=infini", c'est uniquement à destination des utilisateurs. Car la programmation des alertes attend la valeur Null pour considérer qu'il n'y a pas de limite. Si on lui présente 0, il considère que c'est 0. Et donc ne recalcule pas l'alerte. J'ai modifié l'implémentation de ProfileProgrammation.ToValue et commité.

@PIEGAY C'est corrigé. Il y avait 4 profils avec ce problème. Je l'ai ai remis. De votre coté il faudrait recalculer les alertes en "Sauvegardant" les visites.
