### ISSUE TITLE
Profils : lien pour passer de "Consuter" à "Modifier"

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#59]
En particulier lorsqu'un utilisateur arrive sur "Consulter" depuis la fiche d'un véhicule.
On voudrait pouvoir "Modifier" un profil.
Sans ce lien on est obligé d'actualiser la page, dérouler à nouveau l'arbo, et sélectionner "Modifier" pour le profil en question.

**Comment by Portekoi** [comment]
L'arborescence s'ouvre normalement seule. Sinon, un fichier n'a peut être
pas été livré  (read.cshtml)
Je vais voir pour le lien.

**Comment by MamboJoel** [comment]
J'avais publié Read.cshtml.

En définitive, lorsque depuis la fiche véhicule l'utilisateur arrive sur la fiche "Consulter" il doit :
- Cliquer sur la catégorie dans l'arbo.
- Cliquer sur "Modifier" du profil en question.

C'est ça ?

**Comment by Portekoi** [comment]
Exactement :)
Mais je vais voir pour modifier directement via un bouton.

**Comment by Portekoi** [comment]
Boutons mis en place

**Comment by Portekoi** [comment]
@MamboJoel Dans le dernier commit, tu as cet ajout
