### ISSUE TITLE
Reporting client : Onglet planning des alertes

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#6]
**Situation**

Dans le reporting client / onglet planning : http://rep.gestionparc.com/Full/Planning.aspx 
Login : pierre.mauvais@intradef.gouv.fr

**Actuel**

L'ensemble des alertes de plus de deux mois sont "blanchies" et laisse paraître le véhicule comme étant clean alors que ce n'est pas le cas. 

**Demande**

Les alertes de plus de deux mois doivent réapparaître. 
Éventuellement dans une colonne unique  avec une mention particulière (Ex : Périmée)

**Comment by MamboJoel** [comment]
Je me plonge dans le code de Jacques et j'ai peut-être trouvé une astuce.
Il y a désormais une colonne avec année = 0 et mois = 0.
Elle contient les alertes dépassées.
Je précise bien "alertes dépassées", cela signifie par exemple qu'une alerte du 4 octobre se trouvera dans la colonne 0/0 et non dans 10/2016 (nous sommes le 5 octobre).
Ça vous va ?

**Comment by MamboJoel** [comment]
Est-ce que cette modification répond à votre demande ?
Est-ce que le problème des alertes est réglé ?

**Comment by PIEGAY** [comment]
Oui c'est parfait ! 

Il reste plus qu'a afficher l'ensemble des opérations à réaliser. 
Nous avons actuellement uniquement la 1ère réglementaire et la 1ère maintenance. 
Nous ne pouvons pas cacher la vérité au client comme indiqué en réunion

Merci

**Comment by MamboJoel** [comment]
C'est une nouvelle demande ou cet état remplacerait l'état actuel ?

**Comment by PIEGAY** [comment]
En remplacement de l'état actuel (pas de nouvelle page).

**Comment by MamboJoel** [comment]
J'ajoute Jacques à cette demande car cela change profondément cet état.

@meillere le besoin est le suivant :
Pour chaque véhicule présenter toutes ses alertes, quelque soit le type. Actuellement l'état ne présente que la prochaine réglementaire et la prochaine non réglementaire.

**Comment by MamboJoel** [comment]
Doublon #167
