### ISSUE TITLE
Activer les différents niveaux de reporting

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#62]
Ces valeurs sont paramétrées déjà au niveau de la fiche client

- 0 : pas de reporting
- 1 : 
- 2 :
- 3 : full [voir](http://rep.gestionparc.com/Full/tdb.aspx)

**Comment by MamboJoel** [comment]
On attend d'Alain qu'il décrive les pages accessibles poru chaque niveau.

**Comment by AlainPierreSDPV** [comment]
0 : pas de reporting
1 : reporting 3 pages   http://rep.gestionparc.com/full/tdb.aspx  avec les graphes Parc / entrées et sorties de gestion / Réglementaire
                                     http://rep.gestionparc.com/Full/ReportParcDetail.aspx
                                     http://rep.gestionparc.com/full/Alertes.aspx uniquement  sur le réglementaire
2 : idem 1  Plus les opérations du profil uniquement (règlementaires et non réglementaires)
3 : idem 2  plus historique de toutes les opérations saisies hors profil dans les visites
4 : idem 3 plus les informations financières  codifiées selon les critères de la visite  (financier version V1)
5 : Idem 3 plus les informations financières  codifiées et liées aux opérations
