### ISSUE TITLE
Historique des interventions d'un véhicule

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#63]
Avoir un onglet historique à côté de « suivi » avec le détail de l’ensemble des visites (avoir la possibilité de trier par date + par mots clés)

**Comment by MamboJoel** [comment]
Décrire les filtres.

**Comment by PIEGAY** [comment]
On est en train de faire le cahier des charges.
Il est en validation avec les GP.
Ne pas commencer les développements

**Comment by PIEGAY** [comment]
Ci-joint le cahier des charges validés lors de l'audio. 

[Cahier des charges FleetOne - Historique véhicules.docx](https://github.com/groupe-gac/FleetOne/files/753891/Cahier.des.charges.FleetOne.-.Historique.vehicules.docx)

**Comment by MamboJoel** [comment]
@PIEGAY j'établis le devis pour ce projet. A la lecture du cahier des charges m'est venue une interrogation, et j'aimerais une précision. Cela concerne le prototype de la page 5.
Qu'entends-tu par "Bloc Recherche" ? N'est-ce pas la même chose que "Bloc Filtres" ?

![image](https://cloud.githubusercontent.com/assets/3832009/22885765/1a687032-f1fb-11e6-88f9-5e3627257d85.png)

**Comment by PIEGAY** [comment]
Le bloc **FILTRE** comporte l'ensemble des filtres demandés : 
- Filtre « véhicule »
- Filtre « Nature »
- Filtre « Organe »
- Filtre « Facturation »
- Filtre « Date »

Le bloc **RECHERCHE** comporte : 
La barre de recherche par "Mots Clés" sur les tables suivantes : 
- Liste des opérations, 
- N° Bon de commande, 
- Fournisseur,
- N° de devis,
- N° d’OR, 
- N° Facture, 
- Mémo privé, 
- Mémo public

**Comment by MamboJoel** [comment]
Merci pour ces précision.
A quoi correspond le filtre " véhicule " ? C'est la liste des équipements du véhicule ?

**Comment by PIEGAY** [comment]
Filtre « véhicule » possède 3 choix  : 
-	Main Equipement + Equipements,
-	Main Equipement seul, 
-	Equipements seuls,

**Comment by MamboJoel** [comment]
Voici une estimation : 
[NTLM Technologies - Devis #20170201 - Recherche et historique d’interventions.pdf](https://github.com/groupe-gac/FleetOne/files/771415/NTLM.Technologies.-.Devis.20170201.-.Recherche.et.historique.d.interventions.pdf)

**Comment by MamboJoel** [comment]
@PIEGAY  @AlainPierreSDPV  vous pouvez tester un premier jet. Onglet "Historique" au niveau du véhicule.

![image](https://cloud.githubusercontent.com/assets/3832009/25287155/982106f2-26c0-11e7-9d4b-299bd0810f7a.png)

**Comment by Portekoi** [comment]
N'oubliez pas de faire un Ctrl + F5 pour rafraîchir vos fichiers ou videz votre cache si vous pouvez.

**Comment by Portekoi** [comment]
Avez-vous un retour à nous faire sur ce projet @PIEGAY ou @AlainPierreSDPV ?

**Comment by AlainPierreSDPV** [comment]
Les premiers échos sont très positifs

une seule demande m'a été faite pour que la requête par mot se fasse aussi sur les libellés des opérations de la visite

**Comment by MamboJoel** [comment]
C'est ce qui était prévu et ce que j'avais implémenté. 

J'avais écrit le test unitaire `Search_KW_Operation()` pour tester la fonctionnalité et il passait avec succès. @Portekoi tu peux reproduire l'anomalie ? Et corriger le test le cas échéant, s'il n'est pas censé passer. @AlainPierreSDPV tu peux peut-être nous donner un véhicule et un mot clé pour reproduire l'anomalie.

**Comment by AlainPierreSDPV** [comment]
Il manque également après application des filtres dans l'exposition des visites l'information du montant de l'opération

**Comment by Portekoi** [comment]
Je viens de corriger pour la recherche par mot-clé ainsi que le montant.
J'ai aussi mis en évidence les mots-clés trouvés :
![image](https://cloud.githubusercontent.com/assets/1560754/25490205/64ca4dc6-2b6c-11e7-9817-2da5b7ae4153.png)

Exemple :
http://membre.force-reseau-gp.com/mj/#url=/Vehicle/Display/&CompanyID=c.375&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=44546&tab=VisitSearchForm&VVS_VehicleID=44546&VVS_OrganIDs=0&VVS_NatureIDs=0&VVS_Accounts=&VVS_VehicleType=AllEquipments&VVS_FromDate=27/01/2015&VVS_ToDate=10/04/2017&VVS_Tags=suite_&ddd=dddd&VisitID=743517&MessageID=&AlertID=&Display=

**Comment by AlainPierreSDPV** [comment]
C'est Ok  pour moi.  je laisse Cyril clore cette issue à son retour de congés

**Comment by PIEGAY** [comment]
@MamboJoel : Est-il possible que le résultat des recherches apparaissent du plus récent au plus ancien ? 
Merci

**Comment by Portekoi** [comment]
Oui c'est possible. Je peux aussi classer par la date d'entrée ou de sortie du véhicule. Comme vous voulez.

**Comment by PIEGAY** [comment]
Il faudrait classer du plus récent au plus ancien par rapport à la date d'entrée de la visite FleetOne

**Comment by Portekoi** [comment]
C'est corrigé et publié.

**Comment by Portekoi** [comment]
Est ce que l'on peut clôturer ce projet?

**Comment by PIEGAY** [comment]
Ok pour moi
