### ISSUE TITLE
Modification du composant de saisie de dates

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#66]
A la manière dont les utilisateurs entrent des dates dans leurs DMS ou des systèmes ancien : 

pouvoir saisir une date sans les « / » : exemple : 01012016 pour 01/01/2016

**Comment by Portekoi** [comment]
Il semble que les champs dates sont nommés "StartDate" ou "EndDate". J'en ai trouvé à 2 endroits : dans les factures et dans le budget. J'ai donc fait la modification et contrôlé sur ces 2 écrans.

Dis moi si tu vois d'autres endroits.

**Comment by Portekoi** [comment]
Commité

**Comment by MamboJoel** [comment]
Il me semble qu'il y a aussi [la page de la visite](http://f2.sdpv.com/Home/Navigate/#url=/Vehicle/Display/&CompanyID=m.867&VisitProcess=20&VehicleID=51490&AlertID=&VisitID=&FromDate=01/01/2016&ToDate=31/12/2016&Display=&tab=Visits&HasAlert=false&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=de513&VisitReference=763451&VehicleTab=Equipment-64127&EquipmentID=64127&ClientTab=Info&MemberTab=Profiles&VehicleTS=1479823271705&MessageID=&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&ProfileCategories=1,291,284,315,283,50,54,51,52,288,289,290&categoryID=290&articleID=&ProfileCategoryID=288&ProfileID=9623&AlertFromDate=01/01/1900&AlertToDate=22/12/2016)
Les champs entrée et sortie. Si tu peux l'implémenter là en particulier.
Je le teste en local.

**Comment by Portekoi** [comment]
@MamboJoel ma modification impacte tous les champs "StartDate" et "EndDate" et dans visite, les champs se nomment ainsi. Donc ok

**Comment by MamboJoel** [comment]
Ça fonctionne bien. Le top ce serait qu'au focus tu sélectionnes tout le texte. Par défaut une date est rentrée dans ces champs et dans l'esprit des GP ils voudront aller très vite en un clic et direct taper la date sans "/".

**Comment by Portekoi** [comment]
Fait et commité.

**Comment by MamboJoel** [comment]
@AlainPierreSDPV , @PIEGAY  vous pouvez annoncer jolie nouvelle aux gestionnaires de parc, on a implémenté l'outil de saisie de date à la manière des DMS. Je clos cette entrée.
