### ISSUE TITLE
Profils : Anomalie remontée par Xavier Petit

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#69]
@Portekoi , peux-tu regarder cette anomalie.
Elle ne comporte pas de scénario pour la reproduire, j'essaie d'en savoir plus auprès de l'utilisateur.

Posté par Xavier Petit :

> Expéditeur: Xavier Petit <xavier.petit@escudier-sas.com>
> Date: 1 décembre 2016 18:34:37 UTC+8
> Destinataire: PIERRE <alain.pierre@sdpv.com>
> Objet: Profils erreur
> 
> Bonjour Alain,
>  
> J'ai voulu modifier des profils pour BRONZO BOM. Cela fonctionnait jusqu'à aujourd'hui mais maintenant j’ai un message d’erreur
> Impossible de sauvegarder cet équipement
> Je suis bloqué peux-tu voir ce soucis
> Appelle-moi quand tu peux merci
>  
>  
>  
> Cordialement Xavier PETIT
> Gestionnaire du parc
> 471 Avenue des Paluds 13782 Aubagne Cedex
> Tel.: 04.42.70.02.99
> Port : 06 03 22 17 02
> Fax: 04.42.70.04.39
> Email :xavier.petit@escudier-sas.com
> http://www.escudier-sas.fr
> cid:image003.jpg@01D1E10C.5ABA7000

**Comment by Portekoi** [comment]
Je regarde de suite

**Comment by Portekoi** [comment]
Je ne reproduis pas le cas. Ce message apparait sur les équipements et non les profils. J'ai créé un profil sans problème.

**Comment by Portekoi** [comment]
Est-il possible d'avoir une impression écran avec les données saisies?

**Comment by MamboJoel** [comment]
L'utilisateur ne répond pas.
Est-ce que tu as localisé un profil qui s'appellerait BRONZO BOM ?

**Comment by Portekoi** [comment]
Non plus :(

**Comment by Portekoi** [comment]
Peut être le 2023? 
http://localhost:58093/Home/Navigate/#url=/Member/Index/&CompanyID=m.1938&VehicleID=35526&AlertID=&VisitID=&MemberTab=Profiles&Display=&tab=Visits&VehicleTab=Equipment-64667&EquipmentID=64667&VehicleTS=1480601111458&ProfileCategoryID=297&ProfileID=2023

**Comment by MamboJoel** [comment]
Je penche plutôt pour un de des profils issus de cette requête :

``` SQL
SELECT        dbo.ProfileCategory.Name AS Catégorie, dbo.Profile.Name AS Profil, dbo.Profile.ModificationDate, dbo.Profile.ID AS ProfileID, dbo.Member.Name AS Membre
FROM            dbo.Profile INNER JOIN
                         dbo.Member ON dbo.Profile.MemberID = dbo.Member.ID INNER JOIN
                         dbo.ProfileCategory ON dbo.Profile.ProfileCategoryID = dbo.ProfileCategory.ID
WHERE        (dbo.Profile.Name LIKE '%bronzo%')
```

![image](https://cloud.githubusercontent.com/assets/3832009/20796993/3f6ca6a2-b7d9-11e6-9800-937869075e3d.png)

Xavier Petit a des accès à SAUVILOC. Ca écarte le premier profil. C'est sûrement le 5420 car il a été modifié hier. Je vais essayer de l'affecter à un équipement test.

**Comment by Portekoi** [comment]
Le message d'erreur "Impossible de sauvegarder cet équipement" ne vient pas des profils: 

fleet-widget.js => ligne 2365

**Comment by Portekoi** [comment]
Mais je ne vois pas comment recréer cette erreur

**Comment by MamboJoel** [comment]
- En effet, fleet-widget.js ligne 2365
- Mais j'obtiens une [erreur 500](http://f2.sdpv.com/Profile/ProfileInit/?ProfileID=5420&EquipmentID=1725) quand depuis [la page de l'équipement](http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.499&HasAlert=true&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=2011&AlertID=&VisitID=&MemberTab=Profiles&Display=&tab=Edit&VehicleTab=Equipment-1725&EquipmentID=1725&VehicleTS=1480602395787) je clique sur Sauvegarder.

**Comment by Portekoi** [comment]
OK je regarde

**Comment by Portekoi** [comment]
Member.OrganTree est null dans Client.vb ligne 769 mais je ne sais pas pourquoi

**Comment by MamboJoel** [comment]
J'a apporté un correctif (commité plus haut).
Le problème venait de Client.MemberID qui était null. AlertFactory.GetQuery() ne le remontait pas.
Je m'étonne que le problème ne survienne que maintenant.

Comme je ne connais pas l'anomalie rencontrée par l'utilisateur je ne sais pas si ce correctif la règle. Je laisse l'entrée ouverte.

**Comment by Portekoi** [comment]
Je pense avoir recréé l'erreur : aller dans un équipement > ajouter un profil > choisir "Test  Nicolas" > "Test Jm2" > "pasdoperation" 

Exception levée sur VehicleController.cs > ligne 597 car un split est fait sur OperationID qui semble nul

**Comment by Portekoi** [comment]
Est il possible d'affecter un profil sans opération à un équipement ou doit on le filtrer?

**Comment by MamboJoel** [comment]
Je reproduis pas l'erreur sur le controller mais des erreurs js :
![image](https://cloud.githubusercontent.com/assets/3832009/20835127/20c8afdc-b899-11e6-91ce-34d1de87a4ee.png)

De plus je n'ai pas "Impossible de sauvegarder cet équipement" comme le signale l'utilisateur.

**Comment by MamboJoel** [comment]
J'ai enfin eu l'utilisateur. Voici le scénario pour reproduire l'anomalie :

- Aller sur la [La page de l'équipement BL-614-FB](http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.499&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=27850&AlertID=&VisitID=&MemberTab=Profiles&Display=&tab=Edit&VehicleTab=Equipment-32879&EquipmentID=32879&VehicleTS=1480603022927&ProfileCategoryID=297&ProfileID=5420&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=bl614fb)
- Choisir comme profil : BOM CONTRAT BRONZO  BVA ALLISON (ProfileID=5420)
- Cliquer sur Sauvegarder.
- Constater "Impossible de sauvegarder cet équipement"

**Comment by MamboJoel** [comment]
J'ai trouvé. Je corrige.

**Comment by MamboJoel** [comment]
Le problème survenait lorsqu'un équipement possédant un profil à l'heure se voyait affecté un profil travaillant au km ou vice versa.

**Comment by AlainPierreSDPV** [comment]
Fleet est fait pour gérer à minima les opérations réglementaires donc pas de profil vide sauf avis contraire de Cyril par exemple sur les équipements UGAP où il n'y a pas forcément d opération réglementaire


Envoyé de mon iPhone

Le 2 déc. 2016 à 20:09, Portekoi <notifications@github.com<mailto:notifications@github.com>> a écrit :


Est il possible d'affecter un profil sans opération à un équipement ou doit on le filtrer?

-
