### ISSUE TITLE
Reporting client : Onglet planning - Problème avec "Type"

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#7]
**Situation**

Dans le reporting client / onglet planning : http://rep.gestionparc.com/Full/Planning.aspx 
Login : pierre.mauvais@intradef.gouv.fr

**Actuel**

Lorsque nous descendons le champs "Type" devant "Opérations" nous avons des incohérences entre ces deux champs. 

Exemple : 

L'opération "VGP LEVAGE 6 MOIS" possède le "Type" = "Contrôle technique" alors que nous devrions avoir "Type" = "Réglementaire".

![image](https://cloud.githubusercontent.com/assets/22617815/19111631/e56ddf22-8b00-11e6-9da7-cc2ea602ad56.png)

**Comment by MamboJoel** [comment]
Je regarde cette anomalie.
Pour le moment, dans github je ne recommande pas de publier des login/mdp. J'attends d'eux un devis pour sécuriser entièrement cet espace.

**Comment by MamboJoel** [comment]
OK j'ai trouvé une inversion 'Réglementaire' et 'Controle technique' dans une requête de Jacques (FleetDW.dbo.FormatAlerts) et je l'ai corrigée.
Il est possible qu'elle impacte d'autres états de reporting. Est-ce que tu peux vérifier avant de clore cette anomalie ?

**Comment by PIEGAY** [comment]
Cela s'est amélioré, je n'ai plus de VGP en "Contrôle Technique" .
En revanche, certaines opérations "Contrôle technique" apparaissent avec le type "Contrôle technique" + "réglementaire" : 

![image](https://cloud.githubusercontent.com/assets/22617815/19114687/4ada4900-8b0f-11e6-8a28-4477980f3d76.png)

Et d'autres uniquement en "Contrôle technique" : 

![image](https://cloud.githubusercontent.com/assets/22617815/19114694/5bba3348-8b0f-11e6-9ab1-dec1abee3037.png)

**Résultat attendu**

Opération "Contrôle Technique" = Type "Contrôle Technique" uniquement

**Comment by MamboJoel** [comment]
C'est un peu technique puisque l'ensemble "Contrôle Technique" appartient à l'ensemble "Réglemantaire".
Et si nous supprimions le type "Contrôle Technique" ?
Comme ça l'opération "Contrôle Technique PL" apparaît dans "Réglementaire" et pas une seconde fois dans "Contrôle Technique" (qui de plus est redondant avec le nom même de l'opération).
Est-ce que ça t'irait ?

**Comment by PIEGAY** [comment]
Je viens d'avoir Alain au téléphone. 
Nous validons le fait de conserver dans la dimension "Type" uniquement : 
-"Réglementaire"
-"Maintenance" 

Si nous souhaitons faire un trie sur "Contrôle technique" nous le ferons dans la dimension "Opérations"

**Comment by MamboJoel** [comment]
Ok j'ai fait la modif. Je clos cette entrée.
