### ISSUE TITLE
Profils : Bugs sur l'utilisation des profils

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#70]
Bonjour 

Nous rencontrons plusieurs difficultés avec les profils dans V2 sur la plateforme centrale : 

**Nouveau profil créé intégralement sous V2 devient vierge :** 

Nous avons créé un profil sur V2 le 23/11/2016, nous l'avons utilisé et depuis hier il est vierge... 
Plus aucune opération dans le profil : 

http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.867&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=36220&AlertID=&VisitID=828347&HasIncomingVisit=false&IsStoped=false&HasLicence=true&Licence=cn-136&Display=&tab=Visits&ClientTab=Vehicles&MessageID=207889&ProfileCategoryID=288&ProfileID=8104&MemberTab=Profiles&VehicleTab=Equipment-42643&EquipmentID=42643&VehicleTS=1480610430194&IsHot=false

**Modification de périodicité dans le profil s'annule lors de la routine de nuit**

Lorsqu'on modifie les périodicités d'une opération dans un profil existant, les modifications disparaissent à la routine de nuit. Le profil revient à l'état original.  
Ex : Profil SIMMT/PL MIDLINER M160 AVEC LIMITEUR et TACHY 

http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.867&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=41810&AlertID=&VisitID=&HasIncomingVisit=false&IsStoped=false&HasLicence=true&Licence=69031138&Display=&tab=Visits&ClientTab=Vehicles&MessageID=207889&ProfileCategoryID=288&ProfileID=8104&MemberTab=Profiles&VehicleTab=Equipment-42643&EquipmentID=42643&VehicleTS=1480610430194&IsHot=false

**Mise à jour d'un profil**

Lorsqu'on modifie un profil nous sommes obligés d'aller sur chaque véhicule et le sauvegarder pour voir apparaître les modifications dans la visite (recalcule de l'échéance). 
Ce n'est pas pratique surtout sur des parcs importants.

**Comment by MamboJoel** [comment]
J'ai éclaté cette issue en trois issues : #72, #73, #74. Je clos celle-ci.
