### ISSUE TITLE
Urgent UGAP : Modification double arborescence

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#71]
Nicolas, 

Le client UGAP COMMUNAUTE DE COMMUNES DE LA VALLEE DU GAPEAU (ID : 15438) est actuellement en gestion à la plateforme centrale (Parent ID : 7604)

A partir de lundi, la gestion bascule chez IPPOLITO. 

Par conséquent, il faudrait créer la double arborescence avec un rattachement chez IPPOLITO MARCHE UGAP (Parent ID : 13867)

Merci d'avance

Cyril

**Comment by MamboJoel** [comment]
J'ai effectué cette modification. Est-ce que tu peux vérifier ?

**Comment by PIEGAY** [comment]
Le client est bien apparu chez IPPOLITO mais le gestionnaire de parc ne peut pas rentrer dans les véhicules. 
Quand il clic sur l'immatriculation = page blanche
Ex : CP-953-NN
Gestionnaire de parc : Magali ROBINET

**Comment by MamboJoel** [comment]
Pour être honnête, je n'avais plus effectué cette procédure (_SDPV Grands Comptes > Franchisé_) depuis un moment et je me demande si c'est possible. Je ne retrouve pas de trace.
Pour accéder à un véhicule il faut avoir le droit GP sur au moins un membre de son arborescence. C'est le cas de Magali qui est GP directement sur 13867. Alors je m'étonne qu'elle n'accède pas au véhicule.

Est-ce que t'as en mémoire un cas de transfère _SDPV Grands Comptes > Franchisé_ dont je pourrais m'inspirer ?

**Comment by PIEGAY** [comment]
On l'a fait en Février 2016 pour St Etienne Métropole : 
- Id Client (St Etienne Métropole) : 13990 

Nous avions eu le même problème.

**Comment by MamboJoel** [comment]
Merci. Je regarde.

**Comment by MamboJoel** [comment]
J'ai retrouvé les mails. J'archive ici ma réponse du 3 février 2016

> J'ai l'impression que tu cherches à déplacer des client déclarés jusqu'alors coté UGAP vers un franchisé. C'est une opération différente de celle que demande habituellement Alain : un client d'un franchisé vers l'UGAP. Elle demande plus de travaux, et des récursifs, parce qu'il faut faire une déclaration de nouveau membre sur chacun des sous clients du client, afin que le GP qui a accès au membre puisse faire valoir ses droits. A l'avenir faudra le savoir. Quand on déplace un client dans le sens UGAP > Franchise c'est un traitement spécifique.

J'ai donc effectué cette modif (le traitement récursif). En revanche je ne peux pas tester car je ne connais pas les codes coservices de Magali ROBINET.

**Comment by AlainPierreSDPV** [comment]
Il me semble que ?a ?t? le cas avec le groupe BERNIS

Envoy? de mon iPhone

Le 2 d?c. 2016 ? 23:50, Nicolas Taret <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Pour ?tre honn?te, je n'avais plus effectu? cette proc?dure (SDPV Grands Comptes > Franchis?) depuis un moment et je me demande si c'est possible. Je ne retrouve pas de trace.
Pour acc?der ? un v?hicule il faut avoir le droit GP sur au moins un membre de son arborescence. C'est le cas de Magali qui est GP directement sur 13867. Alors je m'?tonne qu'elle n'acc?de pas au v?hicule.

Est-ce que t'as en m?moire un cas de transf?re SDPV Grands Comptes > Franchis? dont je pourrais m'inspirer ?

-

**Comment by PIEGAY** [comment]
C'est bon - Parfait
