### ISSUE TITLE
Profil vierge

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#72]
issu de #70

> Nouveau profil créé intégralement sous V2 devient vierge :
> 
> Nous avons créé un profil sur V2 le 23/11/2016, nous l'avons utilisé et depuis hier il est vierge...
> Plus aucune opération dans le profil :
> 
> http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.867&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=36220&AlertID=&VisitID=828347&HasIncomingVisit=false&IsStoped=false&HasLicence=true&Licence=cn-136&Display=&tab=Visits&ClientTab=Vehicles&MessageID=207889&ProfileCategoryID=288&ProfileID=8104&MemberTab=Profiles&VehicleTab=Equipment-42643&EquipmentID=42643&VehicleTS=1480610430194&IsHot=false

**Comment by MamboJoel** [comment]
Je pense que les dispositions prises dans #73 régleront ce cas. La routine nocturne de synchronisation devait mettre à jour ce nouveau profil avec des données vierges puisqu'il n'existe pas au sens V1.

**Comment by Portekoi** [comment]
J'ai commité la désactivation du traitement de nuit

**Comment by MamboJoel** [comment]
Je l'ai publié. Je clos.
