### ISSUE TITLE
Profils : périodicité s'annule lors de la routine de nuit

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#73]
issu de #70

> Modification de périodicité dans le profil s'annule lors de la routine de nuit
> 
> Lorsqu'on modifie les périodicités d'une opération dans un profil existant, les modifications disparaissent à la routine de nuit. Le profil revient à l'état original.
> Ex : Profil SIMMT/PL MIDLINER M160 AVEC LIMITEUR et TACHY
> 
> http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.867&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=41810&AlertID=&VisitID=&HasIncomingVisit=false&IsStoped=false&HasLicence=true&Licence=69031138&Display=&tab=Visits&ClientTab=Vehicles&MessageID=207889&ProfileCategoryID=288&ProfileID=8104&MemberTab=Profiles&VehicleTab=Equipment-42643&EquipmentID=42643&VehicleTS=1480610430194&IsHot=false

**Comment by MamboJoel** [comment]
Pour palier à ce problème j'ai pris deux initiatives :

- Retiré la mise à jour nocturne des profils V2 en fonction des profils V1.
- Débranché l'interface des profils coté V1.

Est-ce que ça te convient @PIEGAY ? Si oui, on tu peux clore cette issue.

**Comment by PIEGAY** [comment]
Pas de soucis si tout fonctionne dans les profils V2

**Comment by MamboJoel** [comment]
On suit ça de près. Je clos.
