### ISSUE TITLE
Profil : Calcul des alertes lors de la modification d'un profil

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#74]
Issu de #70, par Cyril Piegay @PIEGAY :

> Lorsqu'on modifie un profil nous sommes obligés d'aller sur chaque véhicule et le sauvegarder pour voir apparaître les modifications dans la visite (recalcule de l'échéance).
> Ce n'est pas pratique surtout sur des parcs importants.

**Comment by MamboJoel** [comment]
Ce cas n'est pas un bug mais une amélioration.
En effet cette fonctionnalité n'existait pas dans V1. C'est une des responsabilités de la routine nocturne, elle recalcule les alertes des véhicules ayant un équipement auquel on a affecté un profil qui a été modifié.
Le problème est que ces calculs concernent un nombre incontrôlable d'équipements. Et l'utilisateur, à chaque modification d'un simple paramètre d'un profil pourrait attendre de longues minutes le temps que l'application mette à jour chaque équipement concerné.

Il existe des solutions, comme :

- Le multi-threading (la requête de l'utilisateur entame un nouveau process qui se charge des calculs et le process père poursuit ses traitements sans attendre leur terme pour renvoyer rapidement une réponse au navigateur)
- La refactorisation aussi du calcul des alertes.

Je voudrais faire des recherches à ce titre, en discuter avec @jlenormant et @Portekoi aussi car c'est assez sensible, voir périlleux en terme de charge processeur.

**Comment by MamboJoel** [comment]
Aux solutions on peut ajouter :

- @Portekoi  propose d'implémenter un daemon. Un processus exécuté en arrière plan. L'utilisateur en modifiant un profil l'ajoute à une table des profils à modifier. Le daemon interroge cette table et effectue les traitements sur tous les véhicules concernés puis nettoie la table.
👍 La mise à jour est immédiate
👎 On n'a pas de retour de la mise à jour

- @jlenormant  propose d'afficher, pour chaque profil, une page des véhicules concernés. Et un outil pour recalculer leurs alerte en batch. Via une série de requêtes asynchrones. 
👍 L'utilisateur a un visu sur les traitements
👎 Pas de mise à jour immédiate

Qu'est-ce que vous en pensez ?

Pour info, voici la liste des trente profils les plus répandus : 

![image](https://cloud.githubusercontent.com/assets/3832009/20836172/74d86b62-b89e-11e6-9787-138455c63a9a.png)
Obtenue via :
``` SQL
Select 
        TOP 30
	Count(*) N,
	p.Name
From 
	[Profile] p
	Inner Join Equipment e On p.ID = e.ProfileID
Group By
	p.Name
Order By
	Count(*) Desc
```
Typiquement la modification d'un profil peut enclencher le traitement de cent véhicules.

**Comment by PIEGAY** [comment]
Pour ma part j'opterais pour la solution @Portekoi  : 
si la mise à jour est réalisée immédiatement plus besoin d'avoir de retour sur la mise à jour faite ou non

**Comment by MamboJoel** [comment]
@Portekoi tu peux me faire une estimation du temps pour implémenter un daemon ? Et checker aussi la faisabilité sur le serveur de page. Tx !

**Comment by MamboJoel** [comment]
@PIEGAY j'ai écrit un devis pour répondre à cette demande :

[NTLM Technologies - Devis Mise à jour automatique des plannings FleetOne.pdf](https://github.com/groupe-gac/FleetOne/files/631389/NTLM.Technologies.-.Devis.Mise.a.jour.automatique.des.plannings.FleetOne.pdf)

Je mets @B-Serthelon en copie.

**Comment by MamboJoel** [comment]
La demande a été exprimé encore via  #81.

**Comment by MamboJoel** [comment]
Le devis est validé par Pierre Ippolito.

**Comment by MamboJoel** [comment]
Nous lançons le développement.
Nous visons le 4 janvier pour déploiement et tests sur le serveur en production.

**Comment by MamboJoel** [comment]
On a effectué les premiers tests avec succès.
Il nous reste à câbler quelques éléments entre les actions des utilisateurs et le lancement du traitement.
@Portekoi  le point 3.1.13 du devis.

**Comment by PIEGAY** [comment]
@MamboJoel 
Est-ce que le développement a été publié pour test ? 

Merci

**Comment by MamboJoel** [comment]
Nous avons avancé sur les tests.
La routine sera en place à partir de ce soir minuit. Tu peux effectuer des tests de ton coté :
- Modifier un profil (par exemple en ajout une opération)
- Attendre quelques minutes
- Constater que le planning du véhicule a été mis à jour

**Comment by PIEGAY** [comment]
Merci on va faire des tests

**Comment by PIEGAY** [comment]
Véhicule non mise à jour : 213FVN92

Sur le profil : LEVALLOIS / CABSTAR 
http://f2.sdpv.com/mj/#url=/Member/Index/&CompanyID=m.867&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=51744&AlertID=&VisitID=&ClientTab=Vehicles&FromDate=01/01/2016&ToDate=31/12/2016&VisitReference=831955&Display=&tab=Visits&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=213FVN92&MessageID=&VehicleTab=VehicleInfo&EquipmentID=&VehicleTS=1483970929324&MemberTab=Profiles&ProfileCategoryID=288&ProfileID=9332&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017

On a fait la modification suivante : 
Nous avons ajouté que l'opération "Contrôle Technique PL" valide l'opération "Ctrl pollution VU" 

![image](https://cloud.githubusercontent.com/assets/22617815/21769356/89d64e96-d67e-11e6-883d-d7fc0c14620e.png)

Sur le véhicule : 213FVN92 
http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=c.8893&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=51744&AlertID=&VisitID=&ClientTab=Vehicles&FromDate=01/01/2016&ToDate=31/12/2016&VisitReference=831955&Display=&tab=Visits&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=213FVN92&MessageID=&VehicleTab=VehicleInfo&EquipmentID=&VehicleTS=1483970929324&MemberTab=Users&ProfileCategoryID=288&ProfileID=9332&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017

Le contrôle technique a été réalisé le 20/12/2016, par conséquent le "Ctrl pollution VU" devrait être prolongé jusqu'au 20/12/2017 or il est resté en 2009 : 

![image](https://cloud.githubusercontent.com/assets/22617815/21769422/e900d0f8-d67e-11e6-87c7-8e4057e339c9.png)

**Comment by MamboJoel** [comment]
@Portekoi je reproduis l'anomalie de @PIEGAY 

Le VehicleID=51744 a ProfileID=9332

Or cette requête ne renvoie aucun enregistrement. 
```SQL 

```

**Comment by MamboJoel** [comment]
@Portekoi j'ai ajouté un appel à `DirtyProfile.Dirty()` dans `Profile.Save()` dans le dernier [commit](https://github.com/ntlm-technologies/sdpv-fleet2/commit/9c82fb50c804856d267d436887b405b829c975a4).

Mais je doute que le problème vienne de là. Le test de Cyril consiste à ajouter une validation d'opération par une autre. Peut-être que cet événement a été omis dans la liste des événements du devis. Est-ce que tu sais localiser la méthode qui effectue cette tâche ? Et y appeler DirtyProfile.Dirty() ?

**Comment by Portekoi** [comment]
Je regarde ça

**Comment by Portekoi** [comment]
Corrigé. J'ai aussi corrigé un bogue sur l'IHM, OperationController.cs

**Comment by MamboJoel** [comment]
Impeccable, merci. Je publie.
Cyril, tu peux continuer à tester.

**Comment by Portekoi** [comment]
@MamboJoel Par contre, faudrait prendre la main sur le serveur car la tâche ne semble pas (plus) tourner.

**Comment by MamboJoel** [comment]
@Portekoi la tâche tournait bien mais levait une `ReferenceNullException` sur l'accès à la propriété `DirtyProfile.Profile`. C'est parce que le profil a été supprimé entre temps. @PIEGAY peux-tu confirmé que vous avez créé puis supprimé un profil ? Cela dit, cela peut-être le fait de n'importe quel GP hors plateforme.

J'ai traité le cas dans le dernier [commit](https://github.com/ntlm-technologies/sdpv-fleet2/commit/d928616f15960d49df930b312bceb92b42337d7f).

Par ailleurs subsiste un scénario qui me tracasse : 
- La routine va effectuer un travail, passe le mouchard à 2.
- La routine plante.
- Le mouchard reste à 2.
- Plus aucun travail n'est effectué puisqu'il faudrait que le mouchard soit à 1.

Je pense qu'il faut intégrer une alerte mail en cas d'erreur. On implémentera un `Try Catch` sur l'ensemble au dernier moment quand on aura terminé. Il enverra l'alerte à Cyril et à moi.

**Comment by PIEGAY** [comment]
Aucun profil de supprimé sur la plateforme centrale aujourd'hui. 
Quelle action dois-je mener en cas de message d'erreur ?

On peux continuer le test ?

**Comment by MamboJoel** [comment]
Nous n'avons pas encore implémenté le message email qui nous signalera à toi et à moi que la routine a échoué. Pour l'instant nous préférons suivre en live son comportement et ses échecs, ça nous facilite la tâche pour affiner et déboguer.
Et oui vous pouvez continuer les tests.

**Comment by PIEGAY** [comment]
**Problème dans la modification d'un profil :** 

Lorsque nous modifions ou créons un paramètre dans un problème l'unité choisie n'est pas conservée. 

Exemple : http://f2.sdpv.com/mj/#url=/Member/Index/&CompanyID=m.867&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=49167&AlertID=&VisitID=&ClientTab=Vehicles&FromDate=01/01/2016&ToDate=31/12/2016&VisitReference=713813&Display=&tab=Visits&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=dy853&MessageID=&VehicleTab=Equipment-65093&EquipmentID=65093&VehicleTS=1484063626033&MemberTab=Profiles&ProfileCategoryID=54&ProfileID=9011&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017

Lorsque nous modifions la périodicité de la vidange moteur à 12 mois au lieu de 24 mois, l'unité "mensuel" devient "kilométrage" : 

![image](https://cloud.githubusercontent.com/assets/22617815/21813591/15c6d384-d757-11e6-9cd3-aaefcb295f2f.png)

![image](https://cloud.githubusercontent.com/assets/22617815/21813609/26845d40-d757-11e6-8466-fa02db48a3d4.png)

Remarque : A chaque fois que je clique sur "modifier" l'unité change...

**Comment by Portekoi** [comment]
C'est corrigé normalement

**Comment by PIEGAY** [comment]
Ok ça fonctionne

Merci

**Comment by MamboJoel** [comment]
Oui je pense que c'est fonctionnel. Voici un état des traitements depuis le 9.

La première colonne représente le jour de janvier. La seconde le profil. La troisième le nombre de calculs automatiques de planning d'équipements.

![image](https://cloud.githubusercontent.com/assets/3832009/21987149/936651b6-dc02-11e6-97fa-2177efb1bed0.png)

Je peux donc cette issue.

La source SQL :
```SQL
Select 
	Day(ServiceDate) Jour,
	ProfileID,
	Sum(EquipmentsTreated) As Equipements
from 
	DirtyProfile c
Group By 
	ProfileID, Day(ServiceDate)
Having 
	Sum(EquipmentsTreated) > 0
```

**Comment by MamboJoel** [comment]
Suite à notre conversation téléphonique, @PIEGAY , où je te signalais qu'un travail courrait depuis ce matin pour le traitement de 1500 véhicules du profil 139, voici les profils attendant un recalcul des plannings. Ils ont donc été modifiés aujourd'hui :

![image](https://cloud.githubusercontent.com/assets/3832009/22652099/624034f6-ec85-11e6-8dbc-245649620862.png)

**Comment by MamboJoel** [comment]
(La colonne de gauche désignant le nombre d'équipements à traiter)

**Comment by MamboJoel** [comment]
Je referme cette issue car les calculs sont allés à terme.

Toutefois j'émets la possibilité de référencer les équipements à traiter plutôt que les profils des équipements à traiter. 

- Dans cette seconde solution, celle implémentée aujourd'hui, lorsqu'il y a de nombreux équipements à traiter que le traitement échoue, la routine doit recommencer à zéro, et certainement échouer sur le même équipement, pour les mêmes raisons, et sans que l'on connaisse l'équipement incriminé. 

- Dans la première solution, à mesure qu'ils sont traités, les équipements sortiraient du lot à traiter. Et l'on aviserait tout de suite l'équipement posant problème. Aussi, cela nous permettrait, via le simple enregistrement de l'équipement à traiter, de couvrir tous les autres cas de figure nécessitant un calcul du planning, comme [la mise à jour en batch des index](https://github.com/groupe-gac/FleetOne/issues/53).
