### ISSUE TITLE
UGAP : Intégration visite BOM - AZUR TRUCKS

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#75]
Bonjour Nicolas, 

Comme il y a 3 mois, il faudrait intégrer les visites réglementaires pour le client NCA / COLLECTE (Id : 14129)
Tu trouveras le fichier d’intégration en pièce jointe. 

Est-ce que tu as tous les éléments nécessaires ? 

Merci d’avance. 

[Intégration visite BOM - FleetOne - AZUR TRUCKS - SEPT 2016.xlsx](https://github.com/groupe-gac/FleetOne/files/627358/Integration.visite.BOM.-.FleetOne.-.AZUR.TRUCKS.-.SEPT.2016.xlsx)

**Comment by MamboJoel** [comment]
Oui, j'ai tout ce qu'il me faut.
@Paulhac peux-tu intégrer ce fichier dans la base Fleet, une table tmp_bom
Et j'effectuerai les traitement quand tu auras fini.

**Comment by MamboJoel** [comment]
C'est intégrer.

Note pour dans trois mois :
``` C#
Waybis.SDPV.Fleet.Helper.CreateVisitFromBatch()
```
