### ISSUE TITLE
FLEETONE : Extraction de la table des contacts 

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#76]
Est-ce que tu peux m'extraire la table des contacts ayant un droit de reporting ? 
Modèle en pièce jointe. 
[Contacts SIMMT.xlsx](https://github.com/groupe-gac/FleetOne/files/630488/Contacts.SIMMT.xlsx)

Tu m'avais déjà fait cette extraction il y a un an environ.

**Comment by MamboJoel** [comment]
[Contacts SIMMT.xlsx](https://github.com/groupe-gac/FleetOne/files/630939/Contacts.SIMMT.xlsx)

Info technique : 

`SQL
Select * from SIMMT_CONTACTS
`
