### ISSUE TITLE
Profil : Problème sur le paramétrage "mensuel"

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#77]
Dans le paramétrage des profils, si nous indiquons une fréquence de 24 mois pour une opération, nous sommes rejetés avec le message suivant : 

![image](https://cloud.githubusercontent.com/assets/22617815/20878102/1d3b328c-bacd-11e6-9955-64475d5ddcbb.png)

**Comment by MamboJoel** [comment]
C'est corrigé.

**Comment by PIEGAY** [comment]
Nous avons toujours le problème pour les mois

**Comment by MamboJoel** [comment]
Je ne reproduis pas : 

![image](https://cloud.githubusercontent.com/assets/3832009/20890164/36e0da6e-bb06-11e6-8cc6-a750a3d91c47.png)

**Comment by PIEGAY** [comment]
C'est bon après suppression des caches
