### ISSUE TITLE
Profil : problème "type nombre" dans le paramétrage

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#78]
Lorsque nous modifions le paramétrage d'une opération, nous sommes obligés d'enlever le ",00" sur l'ensemble des paramètres sinon nous avons le message d'erreur suivant : 

![image](https://cloud.githubusercontent.com/assets/22617815/20878162/92be1b82-bacd-11e6-8999-63a3cdc7049a.png)

Apparemment il ne prend pas en charge la virgule.

**Comment by Portekoi** [comment]
Je ne reproduis pas ce bogue en test. Je regarde ce qu'il manque.

**Comment by MamboJoel** [comment]
@Portekoi les TryParse de ton Controller attendent peut-être des points à la place des virgules. Tu peux faire un Replace.

Note que pour résoudre la #77 j'ai été amené à modifié ce Controller précisément. [Ce commit](https://github.com/ntlm-technologies/sdpv-fleet-mvc/commit/6abccc5abfebf15b24b87edf9dfa88aefe8115da). Il te faut d'abord synchroniser.

**Comment by Portekoi** [comment]
Je pense à un problème d'encodage de la vue elle-même "EditProgrammation.cshtml" (views/operation)
Peut être lors du transfert ftp?

**Comment by Portekoi** [comment]
Non, je remplace bien dans mon contrôleur la "," par des "."
Je n'ai pas ce problème en dev.

**Comment by Portekoi** [comment]
Tu peux me donner l'encodage sur le serveur de production?

![image](https://cloud.githubusercontent.com/assets/1560754/20884603/7af02940-baec-11e6-8c16-57270e84fbf9.png)

**Comment by MamboJoel** [comment]
@PIEGAY  : c'est corrigé.

@Portekoi  :

J'ai inversé points et virgules dans tes replaces et ça fonctionne. Il est peut-être plus élégant d'utiliser decimal.TryParse() ou int.TryParse() que des instructions Try/Catch. On peut imaginer un design comme ça dans OperationController :

```C#
        private List<String> errors = new List<string>();

        private decimal getDecimal(string formValue, decimal defaultValue, string errorMessage)
        {
            decimal value = defaultValue;
            if (!decimal.TryParse(formValue, out value))
                errors.Add(errorMessage);
            return value;
        }
```

Et l'assignation dans OperationController.CreateOrUpdateProgrammation()

```C#
            _profileProgrammation.FromValue = getDecimal(
                datas["Tolerance"], 
                0, 
                "Début incorrecte : doit être un nombre"
                );
```

... à l'issu delaquelle tu testes :

```C#
            if (!errors.Count() > 0)
                _profileProgrammation.Save();
```

C'est une réflexion comme ça. Il n'y a pas d'urgence à refactoriser quoique ce soit dans ce secteur de l'application.

**Comment by Portekoi** [comment]
Je pense qu'il y a un autre problème : aucun souci en dev. J'ai testé 10 fois. Un problème du séparateur des  décimales entre mon pc et le serveur? Je vais creuser. Ce problème ne se posait pas encore la semaine dernière.

**Comment by Portekoi** [comment]
Cela ne fonctionne plus chez moi. Le 'CultureInfo' doit être différent au niveau du IIS.

**Comment by MamboJoel** [comment]
D'ailleurs, @Portekoi :

Peut-être plus élégant, sans variable errors déclarée au niveau de la class :

```C#
        private decimal getDecimal(string formValue, decimal defaultValue, Action onError)
        {
            decimal value = defaultValue;
            if (!decimal.TryParse(formValue.Replace(".", ","), out value))
                onError();
            return value;
        }
```

Et l'assignation :

```C#
            List<string> errors = new List<string>();

            _profileProgrammation.FromValue = getDecimal(datas["Tolerance"], 
                0, 
                () => errors.Add("Valeur incorrecte")
                );
```

**Comment by Portekoi** [comment]
C'est factorisé et commité. J'ai aussi enlevé la partie décimal quand celle-ci était à 0
exemple : 2.00 devient *2* / 2.54 => *2.54* (ne change pas)

**Comment by MamboJoel** [comment]
Merci.
A ce titre, je me demande pourquoi la variable "Fin" (ToValue) n'est pas formatée comme "Début" (FromValue), avec deux chiffres après la virgule, alors qu'elles sont décimales toutes les deux.

**Comment by Portekoi** [comment]
@MamboJoel Je ne sais pas. FromValue est Décimal et ToValue est int?

**Comment by Portekoi** [comment]
Dans la base, ce sont 2 décimaux. Mais pas dans l'objet ProfileProgrammation0 Je corrige.

**Comment by MamboJoel** [comment]
@Portekoi j'ai vu que tu avais refactorisé les assignations de `OperationController`. Je les ai refactorisées à mon tour avec un modèle plus pérenne. `GetDecimal()` n'appartient pas logiquement à un `Controller`. J'ai ajouté un module `StringExtensions` dans un nouveau namespace de Misc : `Waybis.Misc.Forms` (tu dois synchroniser waybis-common du coup).

Ce module contient des méthode qui étendent le type `String` et qui seront utile pour sortir des données de formulaire avec la gestion d'erreur qu'on a mise au point. Dans l'intellisense d'une `String` tu trouveras ces méthodes, elles commencent par `To`, comme `ToBoolean`. Ca fonctionne comme ton `GetDecimal()` mais ces méthodes seront désormais atteignables par n'importe quel `Controller` pour peu qu'il importe `Waybis.Misc.Forms` :

```C#
using Waybis.Misc.Forms;
```

Ensuite l'assignation se passe comme ça :

Pour un décimal :
```C#
// Surcharge avec une avec une valeur par défaut
myVariable = form["myVariable"].ToDecimal(0, () => _errors.Add("error"));

// Surcharge sans valeur par défaut (elle est alors 0)
myVariable = form["myVariable"].ToDecimal(() => _errors.Add("error"));

// Surcharge sans gestion d'erreur et de valeur par défaut, la plus directe :
myVariable = form["myVariable"].ToDecimal();
```

Pour un décimal nullable :
```C#
// Surcharge avec une avec une valeur par défaut
myVariable = form["myVariable"].ToNullableDecimal(() => _errors.Add("error"));

// Surcharge sans gestion d'erreur, la plus directe :
myVariable = form["myVariable"].ToNullableDecimal();
```

Selon le même design, j'ai aussi implémenté et mis à disposition les méthodes :
- `ToInteger()`
- `ToNullableInteger()`
- `ToDateTime()`
- `ToNullableDateTime()`
- `ToBoolean()`
- `ToNullableBoolean()`

Je propose qu'on utilise ce design pour les projets MVC à venir, ou tout projet qui reçoit des données de formulaire au format `String`. En particulier la gestion des pneumatiques qui fera l'objet de création/ajout/suppression de profils spécifiques à ses règles métier.
