### ISSUE TITLE
UGAP : Problème tarification DOMTOM suite #51

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#79]
Suite à l'intégration de la nouvelle grille de tarification lors du ticket #51 les clients "DOMTOM" sont devenus en tarification classique. 
Client DOMTOM : 
- GSBDD LA REUNION MAYOTTE
- GSBDD GUYANE
- GSBDD ANTILLES

Exemple : le véhicule 60610112 doit être facturé 44 € au lieu de 24.81 €

**Comment by MamboJoel** [comment]
C'est corrigé.

**Comment by PIEGAY** [comment]
le problème est toujours présent ; 

![image](https://cloud.githubusercontent.com/assets/22617815/20890208/5d3835c2-bb06-11e6-8613-662e9a5193cd.png)

![image](https://cloud.githubusercontent.com/assets/22617815/20890254/7e10fa5e-bb06-11e6-8ae2-bf582a1e9643.png)

**Comment by MamboJoel** [comment]
D'où est issu le premier printscreen ? Tu peux me passer l'url ?

**Comment by MamboJoel** [comment]
Ah ! Je pense avoir trouvé. J'ai apporté un correctif. Tu peux vérifier directement. Pour ton véhicule surligné j'obtiens 44.

**Comment by PIEGAY** [comment]
J'ai toujours le problème : http://comptabilite.sdpv.com/Public/factureservice.aspx?year=2013&Month=5&ClientID=8963

**Comment by MamboJoel** [comment]
Merci pour le lien. Je regarde.

**Comment by MamboJoel** [comment]
Je ne reproduis pas :
![image](https://cloud.githubusercontent.com/assets/3832009/20892954/5c010030-bb10-11e6-9270-a049c86aa46c.png)

Dans le formulaire de recherche j'ai entrée 11 / 2016.

J'obtiens donc pour ce véhicule :
IVECO DAILY (VEH1 (39,00€) PNEU (5,00€) )	30,80
Quels chiffres attends-tu ?

Je cherchais 44€ en fait. Mais en regardant le code de Jacques, je vois qu'il applique un coefficient défini au niveau client de 0,7. 44 x 0,7 = 30,8.
Ce calcul n'est pas une erreur, il semble clairement intentionnel.
