### ISSUE TITLE
Credel : Signalement des véhicules en gestion de parc

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#80]
Outil qui permet d'ouvrir le mail du gestionnaire de parc au moment de la réception.
Adaptation de la requête.

**Comment by MamboJoel** [comment]
Le but est de retourner pour chaque véhicule un ParkManagerID, en retournant par priorité :

1. Vehicle.ParkManagerID si l'utilisateur est actif.
2. Le premier ParkManager du membre du client auquel appartient le véhicule sinon.

@meillere j'avais implémenté la function scalaire GetFirstParkManagerID() comme convenu au téléphone ce midi. Seulement elle donne de très mauvaise performance.

J'ai implémenté la vue VehicleLastParkManagerID qui donne de bien meilleurs résultats.

```SQL
select 
    *
from
    VehicleLastParkManagerID
```

Retourne la liste de tous les véhicules et leur ParkManagerID selon les priorité listées plus haut. Tu peux donc la croiser avec la table Vehicle.

**Comment by meillere** [comment]
effectivement la première version j'ai arrêté à 40 minutes sans résultat la
seconde impécable.


Le 7 décembre 2016 à 15:13, Nicolas Taret <notifications@github.com> a
écrit :
