### ISSUE TITLE
Incohérence entre "qualification" du reporting et de FleetOne

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#82]
@YvesMadec  remonte des incohérences entre les déroulants de la visite FleetOne et celui du reporting.

Il faudrait pour la clarté que les déroulants soient les mêmes d'un coté comme de l'autre.

**Comment by AlainPierreSDPV** [comment]
Utiliser le login suivant: norbert.harchen@developpement-durable.gouv.fr  PW: harchen
sélectionner le reporting financier http://rep.gestionparc.com/Full/ReportFindem.aspx
dans les champs cachés "show liste des champs" descendre à coté de l'onglet véhicule les filtres:
cause - qualification - nature - organe

cause et qualification sont des champs relatifs à la visite  Nature et Organe sont relatifs aux opérations

Dans Fleet le champ cause a pour valeurs possibles 7 Item par défaut c'est  : Arrêt programmé qui proposé

Constater que le champ "cause " dans le reporting ne reprend pas le menu déroulant du champ "cause" de Fleet mais celui de "Qualification" qui comporte 4 item " Réglementaire - Maintenance - Réparation - Dépannage"
 Constater que l'item Maintenance devient  "Entretiens planifiés" dans le reporting
 Constater que le champ "qualification" dans le reporting reprend le menu déroulant du champ "cause" dans Fleet.
Après la correction de cette erreur, Je suis d'accord avec Yves pour préciser dans le reporting que les champs Cause et Qualification sont relatifs à la raison de la création de la visite (= raison de l'arrêt"). 

Yves peux tu nous donner les libellés que tu souhaites pour ces 2 champs dans le reporting ? et le quel tu souhaites garder entre "Entretiens planifiés" et "Maintenance"

**Comment by MamboJoel** [comment]
Merci d'avoir défriché ces incohérences. @meillere il y avait peut-être des raisons à l'origine ?
