### ISSUE TITLE
Récupération du contact Ludovic Penot

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/FleetOne#83]
Le contact Ludovic Penot a été supprimé par inadvertance. On souhaite le récupérer.
On restaure la sauvegarde de BDD d'hier. On analyse la propagation des UserID, ContactID, IndividualID parmi les différentes tables et on réaffecte le contact recréé à ces tables.

@Paulhac peux-tu restaurer la base de données Fleet d'hier dans une base nommée Fleet_20161216 ? Je me charge de l'analyse et de la récupération via les UPDATE/INSERT. Merci.

**Comment by Paulhac** [comment]
Ok. Je regarde ça.

**Comment by Paulhac** [comment]
La restauration est bonne.

Tiens moi au jus

**Comment by Portekoi** [comment]
La restaure est obligatoire? Dans une base d'avril : 
![image](https://cloud.githubusercontent.com/assets/1560754/21260567/d5a81058-c386-11e6-8a20-f3dffea7ee1b.png)

`/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP 1000 [ID]
      ,[Civility]
      ,[FirstName]
      ,[LastName]
      ,[BirthDate]
      ,[BirthPlace]
      ,[Telephone]
      ,[CellPhone]
      ,[Fax]
      ,[PersonalEmail]
      ,[AddressID]
      ,[Comment]
  FROM [Fleet14042016__].[dbo].[Individual]
  where personalEmail = 'ludovic.penot@intradef.gouv.fr'`

**Comment by MamboJoel** [comment]
Je crains que oui. Pour les clés étrangères.

**Comment by MamboJoel** [comment]
Merci @Paulhac

**Comment by MamboJoel** [comment]
D'ailleurs @Portekoi le UserID a changé depuis avril manifestement. J'ai voulu faire mes recherches avec UserID=3237 de ton printscreen, mais cette clé est désormais affectée à un autre utilisateur. Etrange.

```SQL
Use Fleet_20161215
Declare @LastName varchar(max) Set @LastName = 'Penot'
Declare @UserID int
Declare @IndividualID int

Select * From [User] Where LastName Like '%' + @LastName + '%'
Select @UserID = ID, @IndividualID = IndividualID From [User] Where LastName Like '%' + @LastName + '%'
Select * From Individual Where ID = @IndividualID
Select * From Contact Where IndividualID = @IndividualID
Select * From UserAuthorization Where UserID = @UserID
```

**Comment by Portekoi** [comment]
Ah ok, je t'avais envoyé un mail pour en savoir plus... bizarre que la clef soit réattribuée...

**Comment by Portekoi** [comment]
Si je compare les deux BDD (restore hier et avril), je n'ai pas d'écart 
UserID = 3610 pour les deux
IndividualID = 3237  pour les deux
Je ne vois pas d'écart à moins que tu es fais les modifs sur la base restaurée? 
`Use Fleet_20161215
Declare @LastName varchar(max) Set @LastName = 'Penot'
Declare @UserID int
Declare @IndividualID int

Select 'hier' as t, * From [Fleet14042016__].[dbo].[User] Where LastName Like '%' + @LastName + '%'
Select 'avril' as t, * From [User] Where LastName Like '%' + @LastName + '%'
Select @UserID = ID, @IndividualID = IndividualID From [User] Where LastName Like '%' + @LastName + '%'
Select 'hier' as t,* From Individual Where ID = @IndividualID
Select @UserID = ID, @IndividualID = IndividualID From [Fleet14042016__].[dbo].[User] Where LastName Like '%' + @LastName + '%'
Select 'avril' as t,* From [Fleet14042016__].[dbo].Individual Where ID = @IndividualID`

**Comment by PIEGAY** [comment]
Pour l'instant il n'est pas réapparu dans Fleetone

**Comment by Portekoi** [comment]
Effectivement, le 3610 a bien été réattribué su Fleet. Je viens de comprendre.

**Comment by MamboJoel** [comment]
@PIEGAY le contact a été recréé. Tu peux confirmer que c'est ok pour toi ?

**Comment by PIEGAY** [comment]
Apparemment c'est OK
le contact est revenu et le lien avec les véhicules aussi... Ouuffff...

Merci
