### ISSUE TITLE
Pas de remonté d'alerte rouge véhicule EC-323-DL Ican 786

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/FleetOne#84]
C'est mon véhicule. 
J'ai provoqué une alerte tableau de bord  rouge "crevaison roue ARD " c'est le log de 15h05 du 19/12

Je n'ai pas récupéré l'alerte "véhicule hot" via Fleet . L'Ican est correctement paramétré  dans l'application Actia. Les données GPS remontent également

Peux tu regarder ?

**Comment by AlainPierreSDPV** [comment]
j'ai remis le pneu à la  bonne pression c'est le log de 17h34

**Comment by MamboJoel** [comment]
Je ne trouve aucun véhicule dans Fleet ayant pour immatriculation EC-323-DL.

**Comment by AlainPierreSDPV** [comment]
erreur d 'immat
http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=m.421&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=3&VehicleID=52955&AlertID=&VisitID=&HasIncomingVisit=false&IsStoped=false&HasLicence=true&IsHot=false&Licence=EC-223-DL&Display=&tab=Visits

**Comment by MamboJoel** [comment]
Le log correspondant à cette date et ce véhicule est le suivant :

> MSG;585802C9;66;153=869103026461253;202=191216;203=155146;206=191216;207=155449;15=VF1JZ89AH55010959;151=312;152=V2.3.0;20066=REN_MEG3;208=16c5d44;209=16c60fa;212=1;215=56;216=b;217=fa0;218=35;219=4f;220=9f7;245=2b77;246=2f1f;252=2;253=2;254=43;516=0;517=0;518=0;255=2560;256=25e0;524=0;525=0;526=0;267=2b77;268=3bde;542=0;543=0;544=0;2010=3b6;20044=0;500=0;501=0;502=0;503=0;504=0;505=0;506=0;507=0;508=0;513=0;512=0;600=50;601=8c;602=bb8;603=32;604=19;606=5;607=96;612=96;630=1f40;617=3;618=3;619=5;20138=29.545313;20=17ea;2000=1fb;285=1c0;286=1bf;159=UNKNOWN_DRIVER;160=8;20069=0;20070=0;20071=.9287;20072=83;20073=2;20074=0;20075=863;20076=72;20077=0;20081=169;20082=5;20083=0;11004=3cb;11005=1c;11006=0;336=3c;337=130;200=43.983377;204=43.983315;201=4.909928;205=4.909975;291=5;292=8;289=47.500000;290=-8.300000;287=1;288=1;32767=102;20084=8;20096=1800;20097=500;20090=0;20117=0;20118=0;20092=2;20093=9;20098=1;20119=0;20120=0;20121=0;20122=0;20123=0;20124=0;20125=0;20126=2;20068=110;20177=45;20161=88;20176=90;20162=18;273=134;272=3b;20157=1668;20158=2551;20159=204;20160=33;20165=552;20166=68;221=1f;223=bf;222=1f;20179=1352;20180=1;400=be:46:16:c:2:0:0:0:0:0;4011=87:53:4d:0:0:0:0:0:0:0;4021=5a:b4:19:0:0:0:0:0:0:0;460=0:0:0:128:0:0:0:0:0:0;4051=0:0:0:0:0:2d:18:a3:3f:1;461=0:0:0:0:127:0:0:0:0:0;462=0:0:0:127:0:0:0:0:0:0;243=F0FFFFFFFFFFFFFFF18FFFFFFFFFFFFFF2FFFFFFFFFFFFFF;**244=F0FFFFFFFFFFFFFFF18FFFFFFFFFFFFFF2FFFFFFFFFFFFFF**;20103=2024:0:0:0:0:0:0:0:0:0;7F3C

En gras le FMS (code 244) auquel est assigné la valeur hexa suivante :
> F0FFFFFFFFFFFFFFF18FFFFFFFFFFFFFF2FFFFFFFFFFFFFF**

Elle est interprétée par notre programme selon [cette documentation technique](https://github.com/groupe-gac/FleetOne/files/663994/extractFMS.pdf). 

Le "Disfonctionnement pneus" attendu par @AlainPierreSDPV est situé sur le `Status No = 10` du `Block ID=1`. Et le programme retourne `111` qui correspond à `not available`.

Je soumets à ACTIA.

**Comment by MamboJoel** [comment]
La réponse de Jérôme GUILHAS :

> Bonjour,
>  
> Il n’est pas nécessaire de vous replonger dans l’analyse des messages FMS.
> En effet à ce jour, seuls certains voyants du tableau de bord sont remontés par iCAN pour certains véhicules, et la marque RENAULT n’en bénéficie pas pour l’instant (cf « Dashboard alarms » dans le contenu en pièce jointe). En l’état actuel des développements, il est cohérent que rien ne soit remonté.
> Nous sommes en train d’étudier la faisabilité et la couverture que nous pourrons atteindre sur les véhicules PSA et RENAULT MEGANE III (et cousins SCENIC III, CLIO IV, LAGUNA III, DACIA, ….). La liste de contenu évoluera en conséquences.
>  
> En revanche nous pouvons d’ores et déjà proposer les informations de lecture absolue de la pression des pneus, tels que les outils de diagnostic constructeur les déroulent. Ces informations sont remontées sur les identifiants de messages 2001 à 2004.
> Les diagnostics iCAN sont réalisés dans des conditions autres que celles d'un garage (cf moteur démarré, véhicule potentiellement roulant) et pourraient ne pas être remontées systématiquement car on s'interdit toute opération de diagnostic au-delà d'un certain seuil de vitesse (cf sécurité/intégrité du comportement véhicule). Si l’information ne peut pas être lue sur un trajet donné, alors elle sera reportée telle qu’elle a été lue au précédent trajet.
>  
> Cordialement,
>  
> Jérôme GUILHAS
> Project Manager
