### ISSUE TITLE
Reporting : Cas de la double arborescence UGAP / Franchisé

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#85]
Nicolas, 

Tout apparaît en double dans le reporting : http://rep.gestionparc.com/Full/ReportFindem.aspx

![image](https://cloud.githubusercontent.com/assets/22617815/21428203/2cdbfff2-c859-11e6-8854-fc37d34a5c7a.png)

 Login : srouyer@cc-lunevillois.fr
Mdp : ***********

Cela est vrai pour tout les clients ayant plusieurs niveaux d'arborescence. 
Problème de récursivité ?

**Comment by MamboJoel** [comment]
J'ai effectué des modifs. Est-ce que ça va ?

L'embêtant c'est de trouver la bonne arborescence pour un client quand il en a plusieurs. J'ai voulu au début sélectionner parmi toutes ses arborescences la plus profonde. Seulement "Assanissement" avait pour profondeur 5 et @PIEGAY le reporting que tu présentes en printscreen est limité à 3...

@meillere :
J'ai modifié `[GetReportingVehiclesClientUser]()`.
Et sauvegardé l'ancienne version dans `[GetReportingVehiclesClientUser_save]()`.

La nouvelle version s'appuie sur deux vues que j'a créées :

- `CustomerBreadcrumbs`
Liste toutes les arborescences, pour chaque profondeur, d'un client. Par exemple :
```SQL
Select * from CustomerBreadcrumbs Where CustomerID = 7643
```
Donne : 
![image](https://cloud.githubusercontent.com/assets/3832009/21435470/63988ff8-c87a-11e6-9ba2-d3f4c6062329.png)

- `CustomerBreadcrumb`
Pour chaque client l'arborescence la plus profonde, mais avec un niveau maximum de 3 (comme sur le printscreen de @PIEGAY) Par exemple :
```SQL
Select * from CustomerBreadcrumb Where CustomerID = 7643
```
Donne : 
![image](https://cloud.githubusercontent.com/assets/3832009/21435519/9eb93b1e-c87a-11e6-8c06-783659e396a9.png)

**Comment by PIEGAY** [comment]
J'ai testé sur plusieurs clients et c'est bon
merci
