### ISSUE TITLE
FLEETONE : Ajout de marques dans la fiche équipement

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#89]
http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=c.8885&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=38697&AlertID=&VisitID=&ClientTab=Users&FromDate=01/01/2016&ToDate=31/12/2016&VisitReference=812476&Display=&tab=Edit&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=60330281&MessageID=&VehicleTab=Equipment-46323&EquipmentID=46323&VehicleTS=1482426111653&MemberTab=Users&ProfileCategoryID=54&ProfileID=9132&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017

Merci de rajouter les marques suivantes dans la fiche équipement : 
- TRONAIR
-  JUNGHEINRICH

![image](https://cloud.githubusercontent.com/assets/22617815/21587781/5b8fb796-d0e0-11e6-9dc5-b7d17f628ae7.png)

**Comment by PIEGAY** [comment]
+ la marque DHOLLANDIA

**Comment by MamboJoel** [comment]
OK !
