### ISSUE TITLE
FLEETONE : Modification des coordonnées d'un contact

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#9]
**Situation**

http://f2.sdpv.com/Home/Navigate/#url=/Client/Index/&CompanyID=c.8310&VisitProcess=12&VehicleID=&AlertID=&VisitID=&FromDate=01/01/2016&ToDate=31/12/2016&Display=&tab=Visits&HasAlert=true&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=61010105&VehicleTab=VehicleInfo&EquipmentID=&HasMandatoryAlert=true&MonthsForAlert=1&AlertFromDate=01/01/1900&AlertToDate=05/11/2016&ClientTab=Users&VisitReference=804743

Onglet Administration / Utilisateur

**Problème**

Si nous modifions les éléments suivants de la fiche contact : 
- Nom
- Prénom
- Mobile
- Téléphone

Le lendemain, ces éléments reviennent comme avant la modification.

![image](https://cloud.githubusercontent.com/assets/22617815/19112358/b4b37794-8b04-11e6-8281-92f52ba3136b.png)

Dans cet exemple, nous avions modifié le NOM en "jeancolas" et le lendemain il est revenu en "Bories"...

**Comment by MamboJoel** [comment]
Voir synchro nocturne F1.

**Comment by Portekoi** [comment]
Désactivé dans chargement nuit

**Comment by MamboJoel** [comment]
Merci @Portekoi bien vu.
@PIEGAY on a débrancher l'outil de synchronisation entre V1 et V2 concernant les Users et qui faisait partie du lot de traitement la nuit. Je pense que ce phénomène ne se reproduira plus. Alors je clos l'issue, mais si tu constates l'erreur à nouveau tu peux la réouvrir.
