### ISSUE TITLE
FleetOne : Changement d'affectation 304 matériels (A faire avant le 05/01 - Facturation)

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#92]
**_Modification à faire avant le 05/01/2017 - Facturation_**

@MamboJoel tu trouveras en pièce jointe une table avec 304 immatriculations et le nouvel Id Parent (Changement d'affectation). 

[SIMMT Transfert parc génie.xlsx](https://github.com/groupe-gac/FleetOne/files/681883/SIMMT.Transfert.parc.genie.xlsx)

Merci

**Comment by PIEGAY** [comment]
Après le mouvement des véhicules, est-ce que tu pourras masquer les clients suivants (avec leurs enfants) : 
- GENIE AIR : Id 8969 avec l'ensemble de ses enfants
- GENIE COMBAT : Id 8971 avec l'ensemble de ses enfants
- GENIE SOUTIEN TERRE : Id 8972 avec l'ensemble de ses enfants

Merci

**Comment by MamboJoel** [comment]
Ok pour ça.

**Comment by MamboJoel** [comment]
Ok, j'ai caché 56 clients et sous-clients.

**Comment by PIEGAY** [comment]
Est-ce qu'il y a des véhicules archivés sur ces clients ? 
Si oui, est-ce que tu peux me donner la liste de ceux-ci afin que je les réaffecte aux nouvelles unités pour l'historique financier.

**Comment by MamboJoel** [comment]
Oui. [Ces véhicules](https://github.com/groupe-gac/FleetOne/files/684478/Vehicules.des.clients.rendus.invisibles.xlsx).

**Comment by PIEGAY** [comment]
@MamboJoel tu trouveras ci-joint les nouveaux Id Client pour ces véhicules afin qu'ils apparaissent dans Fleetone et le reporting financier. 

[Vehicules.des.clients.rendus.invisibles.xlsx](https://github.com/groupe-gac/FleetOne/files/684651/Vehicules.des.clients.rendus.invisibles.xlsx)

Merci

**Comment by PIEGAY** [comment]
@MamboJoel 
Est-ce que tu as pu réaffecter les véhicules archivés ? 
Merci

**Comment by PIEGAY** [comment]
@MamboJoel est-ce que tu pourrais me réaffecter les véhicules pour Mercredi ? 
J'ai besoin de faire des bilans financier pour l'assemblée générale. 

Merci

**Comment by MamboJoel** [comment]
Ok !

**Comment by PIEGAY** [comment]
parfait !!
merci
