### ISSUE TITLE
FleetOne : Problème bouton "nouvelles opérations" dans visite FleetOne (Urgent)

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#94]
Impossible de créer une nouvelle opération dans une visite FleetOne. 

http://f2.sdpv.com/mj/#url=/Vehicle/Display/&CompanyID=c.8962&HasAlert=false&HasMandatoryAlert=true&MonthsForAlert=1&VehicleID=41075&AlertID=&VisitID=836345&ClientTab=Users&FromDate=01/01/2016&ToDate=31/12/2016&VisitReference=713813&Display=&tab=Visits&HasIncomingVisit=false&IsStoped=false&HasLicence=false&IsHot=false&Licence=69031176&MessageID=&VehicleTab=Equipment-47343&EquipmentID=47343&VehicleTS=1483365671984&MemberTab=Users&ProfileCategoryID=54&ProfileID=7602&VisitProcess=20&HasPendingGACInvoice=false&HasInvoiceDelta=false&OrganID=0&NatureID=0&Account=&AlertFromDate=01/01/1900&AlertToDate=19/01/2017

![image](https://cloud.githubusercontent.com/assets/22617815/21759769/1d0d5f02-d647-11e6-92e3-2f98c0f01d21.png)

Nous restons bloqué sur "Veuillez patienter..."

![image](https://cloud.githubusercontent.com/assets/22617815/21759759/0f61edbe-d647-11e6-80be-f2694a01e23f.png)

C'est assez urgent car bloquant pour la création des bons de commande

Merci

**Comment by Portekoi** [comment]
Je n'ai pas la main pour corriger mais @MamboJoel  :
GET 404 Not Found - http://f2.sdpv.com/Operation/Operations/

Et si je regarde le controleur "Operation", j'avais une méthode "JsonResult Operations" en GET qui est maintenant en POST

**Comment by Portekoi** [comment]
Je pense avoir corrigé. Pouvez vous réessayer?

**Comment by PIEGAY** [comment]
C'est bon !! 
Merci pour la réactivité
