### ISSUE TITLE
FleetOne :Impossible d'envoyer un bon de commande

### ISSUE THREAD

**Issue by PIEGAY** [groupe-gac/FleetOne#96]
Bonjour, 

Nous avons une erreur "f2.sdpv.com indique : Erreur : Internal Server Error" lors de l'envoi d'un bon de commande : 
- Visite 836125
- Destinataire : olivier.loty@simmt.terre-net.defense.gouv.fr
- Pièce jointe : 25268 modifier (voir la pièce jointe)

http://f2.sdpv.com/Visit/Document2/836125

[25268 modifier.pdf](https://github.com/groupe-gac/FleetOne/files/698436/25268.modifier.pdf)

![image](https://cloud.githubusercontent.com/assets/22617815/21843190/5c5de966-d7ea-11e6-87a8-f3430a0e2a7a.png)

**Comment by MamboJoel** [comment]
Cyril. Peut-être que le nom importune le serveur. Peux-tu retirer le point ? Simplement nommer le fichier `25268modifier.pdf` ? Cette hypothèse écartée nous entameront des recherches.

**Comment by PIEGAY** [comment]
Cela fonctionne.
Nous allons éviter les espaces et caractères spéciaux dans les noms de pj
